### ISSUE TITLE
How to cope with a lot of RequestTimeout errors and what could be causing that?

### ISSUE THREAD

**Issue by hanoii** [aws/aws-sdk-php#1013] opened 2016-06-05 18:58 UTC
I am using aws sdk php 2.8.30. The choice for 2.8.x is because it's being used in a php framework whose requirement is PHP 5.3+ so I needed to maintain that.

I am attempting to upload an 900mb file. I am using the multipart upload and I've tried several maximum part size combinations. In the end, I settled with the default 5m because that seems the most reliable, however, by using a debug plugin for Gizzle and I can still see a lot of those errors appearing. The default (and hardcoded) max retries sometimes work, but sometimes it doesn't, and I need this to work reliably.

So first, do you have any idea what could be making this many RequestTimeout errors? I am inclined that this is some network error where the server is hosted (which is behind a government network which could have some issues but attempt to fix/debug any networking issues is 100% beyond me).  

Because of this and noticing that even when it works I am almost hitting the retry limit of 3, I created #1012. Which I think it's a nice addition.

Regardless of that, I would like to see if you can help me/recommend steps to follow or make this work more reliable. I even thought of lowering the part size even more, but you have a limit of 1000 parts, so a too little part size will eventually limit the file size.

**Comment by cjyclaire** [comment] 2016-06-06 17:17
I'd also consider the networking might be causing this error, while there is limitations in networking enhancing and SDK version upgrade, it seems like working with retry configuration is not a bad choice.
If you think there could other factors that might causing this trouble and could be reproduced, I'd more than happy to help to dig more into the issue :)

Then, for multipart upload, it's true that a part is in the range from 5MB to 5GB, 10000 parts per upload.

**Comment by hanoii** [comment] 2016-06-06 17:28
Oh, it;s 10000, I thought they were just 1000. That should be fine. You can still configure a minimum below 5MB, couldn't you?

Right now I have it configured (with my PR) for 5mb and 6 retries and the uploaded ended fine. Logging to a file a spotted quite a few of these requestimeouts, but the transfer completed fine. It should happen automatically every 2 days, so will monitor.

**Comment by cjyclaire** [comment] 2016-06-06 17:39
@hanoii, Cool, that's true, yet in SDK, by default, there is [limit](https://github.com/aws/aws-sdk-php/blob/2.8/src/Aws/S3/Model/MultipartUpload/AbstractTransfer.php#L63) in the min size of file part due to performance consideration.

**Comment by cjyclaire** [comment] 2016-06-14 21:03
I'm going to close this issue while keep PR #1021 open. Feel free to reopen this issue if you have further monitoring information :)

**Closed by cjyclaire** 2016-06-14 21:03 UTC
Labels: question

**Comment by hanoii** [comment] 2016-07-08 22:41
I am again facing a lot of <Error><Code>RequestTimeout</Code>, no even more than before. Do you know how much is that timeout on AWS side?

I am unsure how to debug further. I shouldn't have that bad of a network for a 5m part to be retried 6+ times until properly sent.

Any ideas?

**Comment by cjyclaire** [comment] 2016-07-08 23:41
@hanoii , so just to confirm the information, are you still on SDK v2.8 and PHP 5.3? Could you provide more information on SDK related usage? (Still with same file multipart upload issue?) Could you provide some code snippets that might help reproduce the issue? Or will you consider it to be a service side issue that I might communicate with service team perhaps?

**Comment by hanoii** [comment] 2016-07-11 12:50
Yes, all the same. The usage is very simple actually, just a file upload an a scheduled cron task on a php web app and yes, it is still the same multipart upload issue.

Unfortunately I don't think I am doing anything out of the ordinary for this, I suspect it's some kind of networking issue but I would be great to know what happens on your side. I know I am getting ReequestTimeout, how long is that? Is it that the network is uploading too slow? or is it that the communication is reset. Any more insight would really help.

**Comment by hanoii** [comment] 2016-07-11 14:29
@cjyclaire 

Have a look at this, right now I have it configured at 12 retries.

Format is part number, http response, AWS request ID (For if its useful)
```
Part number 3,200 OK,E29045090A479E70
Part number 1,200 OK,C0735B3AC0A24E33
Part number 2,400 Bad Request,550F063BFE6F43FC
Part number 2,400 Bad Request,531E8EA05FFE24E4
Part number 2,400 Bad Request,F45FBA2AF70F52CE
Part number 2,400 Bad Request,AF9D7F92B6863ED8
Part number 2,400 Bad Request,2278FF6ED2013467
Part number 2,200 OK,E0227F6D47E66F6C
Part number 4,200 OK,24139C41952CACEC
Part number 5,400 Bad Request,DF9A7E58B20679E6
Part number 6,400 Bad Request,08CE9A928C986754
Part number 5,400 Bad Request,325A1F03E248695D
Part number 6,400 Bad Request,D56E5A5F2DA2E660
Part number 5,400 Bad Request,9790D3DD80708E25
Part number 6,400 Bad Request,C36E39E901A31291
Part number 5,400 Bad Request,39907E5F4AE56449
Part number 6,400 Bad Request,0255C13E0C075809
Part number 5,400 Bad Request,F3BFD3B9843DB4F6
Part number 6,400 Bad Request,76DA70BFAE431700
Part number 5,400 Bad Request,4BE0615A0A3E2C91
Part number 6,400 Bad Request,ED0BEC47A82B5707
Part number 5,400 Bad Request,390074A84402B550
Part number 6,400 Bad Request,554EC93B2C02C56A
Part number 5,400 Bad Request,0F5BB1F7E1EC98FD
Part number 6,400 Bad Request,AB6E00A14B3FAEB4
Part number 5,200 OK,DEB3FA9716291469
Part number 6,400 Bad Request,1BF320DA1C6CAA81
Part number 6,400 Bad Request,8AD1934F7D5E121E
Part number 6,400 Bad Request,9011A15DDD87D18B
Part number 6,403 Forbidden,6F8E28862CF71D41
```

The last one is the first time I saw it, the XML response of the Forbidden one is:

```xml
<Error><Code>RequestTimeTooSkewed</Code><Message>The difference between the request time and the current time is too large.</Message><RequestTime>Mon, 11 Jul 2016 14:02:29 +0000</RequestTime><ServerTime>2016-07-11T14:19:36Z</ServerTime><MaxAllowedSkewMilliseconds>900000</MaxAllowedSkewMilliseconds><RequestId>6F8E28862CF71D41</RequestId><HostId>I13o31+HqFkn93XJlyBHptsCWaoKTSvtsZ06thJza7p3zPwiLOvdCQAYrkOcMTFgRZZ4GDXeahQ=</HostId></Error>
```

It was the 12th attempt, but I think that's a coincidence. Maybe the request time is fixed as the initiate time rather than the retried time? That could be another fix but still it really strikes me why that many timeouts.

Sometimes I up to 50x parts, this was timeout really soon.

**Comment by cjyclaire** [comment] 2016-07-11 16:50
@hanoii thanks for the information inputs, good to know the response details.

With Error 400, it might have to do with malformed syntax, any thoughts on this perhaps? It's interesting that some 400 bad request could make it to 200 after retries without making changes while some end in 403. Could you double check your credentials and access with this file just in case? May I know which guzzle version is used? Could you try update guzzle version as well? In looking more into the wire, could you try [`request.option`](http://docs.aws.amazon.com/aws-sdk-php/v2/guide/configuration.html?#client-configuration-options) here with parameters like [`on-stats`](http://docs.guzzlephp.org/en/latest/request-options.html#on-stats) (Not sure your guzzle version for this)?

Another quick question for this issue, are those retries happened with this particular 900mb files only? Or this happens with whatever is uploaded?

**Comment by hanoii** [comment] 2016-07-11 17:27
It's not malformed syntax, all of the 400 errors are the same:

```xml
<Error>
  <Code>RequestTimeout</Code><Message>Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.</Message>
  <RequestId>325A1F03E248695D</RequestId>
  <HostId></HostId>
</Error>
```

The guzzle version is the one shipped with latest version of AWS SDK 2.8 and as far as Guzzle/Common/Version.php goes, it's 3.9.3.

It's certainly not a credentials issue. Updating guzzle, sure, I guess I could try. Would it work with any latest version of guzzle? No internal API changes? Any version in particular?

I searched project-wise for `on-stats` and found nothing, so probably not supported in the version shipped.

The retries happen with this particular 900mb file. It's not always the same file, it's a backup of a directory that happens every two days, and once the backup is finished, it attempts to upload it to AWS. So it's a temporary tar file made of that directory which is always growing a bit overtime.

On the same site/server/code I have also another file being backed up, which is a database dump, short of 6mb. There are some of those missing (which means the upload failed, but some still there, recent ones, so this one sometimes goes through).

With each of this files a very small info file is also generated and uploaded, the info file is always uploaded to s3. It's around 500 bytes.

**Comment by cjyclaire** [comment] 2016-07-11 17:50
@hanoii thanks for the information, sounds it has more to do networking, since socket connection made to server-side is failed due to timeout, I couldn't think of how service team could help look more into that, however, please feel free to ask questions on AWS [forum](https://forums.aws.amazon.com/forum.jspa?forumID=24) if you would like to communicate with service team directly. 

I understand that those retries are frustrating, yet there is nothing on SDK side could help with that. 
More information about configuration for socket timeout in v2, it defaults to 60 seconds and is configurable via the default_socket_timeout in `php.ini` setting.

**Comment by hanoii** [comment] 2016-07-11 17:59
@cjyclaire but isn't the timeout on AWS side? I mean, how would AWS give me a 400 RequestTimeout error at a different moment that the one I set with something like `default_socket_timeout`?

**Comment by cjyclaire** [comment] 2016-07-11 18:14
@hanoii S3 respond with that error [when a client hasn't sent any bytes for 20 seconds.](when a client hasn't sent any bytes for 20 seconds.) Since retries have been exhausted and error still surfaced, you might be experiencing a lot of contention on your local network.

**Comment by hanoii** [comment] 2016-07-11 18:16
What about updating guzzle, do you think is a good idea? what version should I update to?

**Comment by cjyclaire** [comment] 2016-07-11 18:33
@hanoii Apology for the confusion, I'm afraid that v2 is using `guzzle/guzzle` (Guzzle v3), which is abandoned. 
I understand it might be difficult for you to move to SDK v3 right now, yet I strongly recommend doing so in the long run, SDK v3 has more flexible configurations both for retry and http stats, it uses `guzzlehttp/guzzle` ([Guzzle v6](http://docs.guzzlephp.org/en/latest/)) instead, which introduces up-to-date fix and enhancement.
