### ISSUE TITLE
filterArn parameter not applied in Personalize getRecommendations

### ISSUE THREAD

**Issue by dael** [aws/aws-sdk-php#2134] opened 2020-11-02 11:22 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
filterArn parameter is included to apply a filter to the result value of the Personalize campaign.
but result that the filter is not applied to the response result is returned.
checking the debug message, filterArn is not included in the API request body generated.

**Version of AWS SDK for PHP?**
3.130.3
**Version of PHP (`php -v`)?**
7.1.33

**Screenshots**
```
-> Entering step init, name 'idempotency_auto_fill' --------------------------------------------------- command was set to
  /var/www/vendor/aws/aws-sdk-php/src/TraceMiddleware.php:261:
  array (size=3)
    'instance' => string '000000007e1399a400000000745ed5d1' (length=32)
    'name' => string 'GetRecommendations' (length=18)
    'params' =>
      array (size=5)
        'campaignArn' => string 'arn:aws:personalize:ap-northeast-2:xxxxxxxxxxxx:campaign/campaign1' (length=77)
        **_'filterArn' => string 'arn:aws:personalize:ap-northeast-2:xxxxxxxxxxxx:filter/filter-dev' (length=74)_**
        'userId' => string '109' (length=3)
        '@http' =>
          array (size=1)
            'debug' => resource(13, stream)
        '@context' =>
          array (size=0)
            empty
  
request was set to
  /var/www/vendor/aws/aws-sdk-php/src/TraceMiddleware.php:261:
  array (size=0)
    empty
  
-> Entering step validate, name 'validation' -------------------------------------------- no changes -> Entering step build, name 'builder' -------------------------------------- request.instance was set to 000000007e13987200000000745ed5d1 request.method was set to POST request.headers was set to
  /var/www/vendor/aws/aws-sdk-php/src/TraceMiddleware.php:261:
  array (size=3)
    'X-Amz-Security-Token' => string '[TOKEN]' (length=7)
    'Host' =>
      array (size=1)
        0 => string 'personalize-runtime.ap-northeast-2.amazonaws.com' (length=48)
    'Content-Type' =>
      array (size=1)
        0 => string 'application/json' (length=16)
  
request.body was set to **_{"campaignArn":"arn:aws:personalize:ap-northeast-2:xxxxxxxxxxxx:campaign\/campaign1","userId":"109"}_** request.scheme was set to https

```

**Comment by ajredniwja** [comment] 2020-11-06 04:26
Hey @dael I am not sure if I understand your question correctly, are you concluding that the `filterArn` parameter that you use is not working as expected? 

Can you share the reproduction code?

**Comment by dael** [comment] 2020-11-06 06:09
Yes. I have requested including filterArn but Received a response with no filter applied.

The screenshot above is a debug report for the request.

In the log, filterArn exists in params, 
but filterArn is missing in request body.

My code;
```
$client = new PersonalizeRuntimeClient([
    'region' => 'ap-northeast-2',
    'credentials' => $credentials,
    'version' => '2018-05-22',
]);
$result = $client->getRecommendations([
    'campaignArn' => 'arn:aws:personalize:ap-northeast-2:xxxxxxxxxxxx:campaign/campaign1',
    'filterArn' => 'arn:aws:personalize:ap-northeast-2:xxxxxxxxxxxx:filter/filter-dev',
    'userId' => '109',
]);
```

**Comment by ajredniwja** [comment] 2020-11-12 03:49
Hey @dael Sorry for the delay here, I was not able to reproduce the problem as I get: 

```
  request.body was set to {"campaignArn":"arn:aws:personalize:us-west-xxxxxxx:campaign\/mycompaign","filterArn":"arn:aws:personalize:us-xxxxx791:filter\/test2","userId":"1"}

```

This is because the feature to [use the filters](https://github.com/aws/aws-sdk-php/blob/master/CHANGELOG.md#31402---2020-06-05) was introduced in PHP SDK version: `3.140` and you are on `3.130`, bumping up the SDK version should fix the problem, I have tested it. 

Closing this issue now, please reach out if that doesnt solve the problem or if you have any other questions.

**Closed by ajredniwja** 2020-11-12 03:49 UTC
Labels: guidance
