### ISSUE TITLE
AWS Elastic Transcoding Signature Expired

### ISSUE THREAD

**Issue by arvindgt** [aws/aws-sdk-php#537] opened 2015-04-17 18:12 UTC
I am using PHP SDK for AWS Elastic Transcoding. When I am creating a transcoding job, it gives me an error, Like:

Signature expired: 20150411T064107Z is now earlier than 20150411T064135Z (20150411T064635Z - 5 min.)

I am using region US-WEST-2.
Can any body guide me please how to solve this issue.

**Comment by mtdowling** [comment] 2015-04-17 18:18
Can you check to ensure that your machine's clock is relatively in sync with the service's clock?

**Comment by mtdowling** [comment] 2015-04-21 23:44
If this is caused by clock skew, then using something like NTP to keep your clock in sync would be the solution. If this is not clock skew related, then seeing some example code on how error was triggered may help.

**Comment by arvindgt** [comment] 2015-04-22 07:12
Yes Mtdowling, your previous comment was helpful. thank you for your answer.
My ubuntu server's click was delaying by 6-7 minutes from UTC. Issue resolved..

**Comment by jeremeamia** [comment] 2015-04-22 07:14
Glad it's working now. Thanks for the update. We'll go ahead and close this.

**Closed by jeremeamia** 2015-04-22 07:14 UTC
Labels: awaiting-reply
