### ISSUE TITLE
Bucket name appending to protocol causing curl errors

### ISSUE THREAD

**Issue by robertmarney** [aws/aws-sdk-php#2209] opened 2021-03-21 00:50 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**

Bucket name is being used as the protocol, same issue as #2189 which was closed.

```
exception: "Aws\S3\Exception\S3Exception"
file: "/home/[redacted]/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php"
line: 195
message: "Error executing "ListObjects" on "[redacted bucket name].[redacted]"; AWS HTTP error: cURL error 1: Protocol "[redacted bucket name].https" not supported or disabled in libcurl (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for [redacted bucket name].[redacted]"

```

**Version of AWS SDK for PHP?**
3.175.0
**Version of PHP (`php -v`)?**
7.4.4 and 8.0.3

**Work Around**
Downgrading to 3.173.23 resolves the issue for me.

**Comment by SamRemis** [comment] 2021-03-22 14:02
Hi all, this should be fixed with #2214

**Comment by EmilMoe** [comment] 2021-03-23 10:39
Thanks. I had the same issue yesterday but for DigitalOcean Spaces, not sure that it would have been relevant to fix here, but glad the issue is been fixed.

Do you know when the patch goes live, @SamRemis ? I need to stop enforcing `3.174.2` again at the point.

**Comment by TARichardWashington** [comment] 2021-03-24 13:16
Hi All.  @EmilMoe Yes exactly the same problem here.

**Comment by TARichardWashington** [comment] 2021-03-24 13:36
@EmilMoe using  "version": "3.175.2" now all working.

**Comment by ajredniwja** [comment] 2021-04-05 21:58
I'd close this issue now, please reach out if you any more questions.

**Closed by ajredniwja** 2021-04-05 21:58 UTC
Labels: bug, needs-triage
