### ISSUE TITLE
stream_context_create and copy()

### ISSUE THREAD

**Issue by angrycyborg** [aws/aws-sdk-php#500] opened 2015-03-04 22:10 UTC
In the following function, the object is copied but the ACL does not get applied.

```php
function s3copy( $source, $destination ){
	$context = stream_context_create( array( 's3' => array( 'ACL' => 'public-read' ) ) );
	copy( $source, $destination, $context );
}
```

If I swap out copy() for fopen() fwrite() fclose(), the file is copied *and* ACL is applied:

```php
function s3copy( $source, $destination ){
	$context = stream_context_create( array( 's3' => array( 'ACL' => 'public-read' ) ) );
	$fp = fopen( $destination, 'w', false, $context );
	fwrite( $fp, file_get_contents( $source ) );
	fclose( $fp );
}
```
I added the SDK's wire logger and get no errors.

Is this working as intended?

**Comment by mtdowling** [comment] 2015-03-07 01:28
Interesting. When you call the copy function with a wire logger attached, what HTTP request is sent over the wire? Does it have the ACL parameter set as a header?

**Comment by mtdowling** [comment] 2015-04-22 05:16
I'm not able to reproduce this problem. When I provide a context to `copy`, I'm able to set an ACL.

Here's my script:

```php
<?php
require 'vendor/autoload.php';

$s3 = Aws\S3\S3Client::factory([
    'region'  => 'us-east-1',
    'version' => 'latest',
    'curl.options' => [CURLOPT_VERBOSE => true]
]);

\Aws\S3\StreamWrapper::register($s3);

$ctx = stream_context_create([
    's3' => ['ACL' => 'foo']
]);

copy('s3://t1234/channel-copy.xml', 's3://t1234/channel.xml', $ctx);
```

As you can see, I've set the ACL to "foo", which should trigger a failure.

Here's the output:

```
* Hostname was NOT found in DNS cache
*   Trying 54.231.8.121...
* Connected to t1234.s3.amazonaws.com (54.231.8.121) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
* Server certificate: *.s3.amazonaws.com
* Server certificate: VeriSign Class 3 Secure Server CA - G3
* Server certificate: VeriSign Class 3 Public Primary Certification Authority - G5
* Server certificate: Class 3 Public Primary Certification Authority
> HEAD /channel-copy.xml HTTP/1.1
Host: t1234.s3.amazonaws.com
User-Agent: aws-sdk-php2/2.8.1 Guzzle/3.9.3 curl/7.39.0 PHP/5.6.3
Date: Wed, 22 Apr 2015 05:13:00 +0000
Authorization: AWS ***:***

< HTTP/1.1 200 OK
< x-amz-id-2: SpPpizdeq0XI7rvMuIB7TdEZ4o5G6V1SOmpC8Iu0tJh/IETMTf3vizzHVXi39kPh
< x-amz-request-id: 0C0C0D7198865344
< Date: Wed, 22 Apr 2015 05:13:02 GMT
< Last-Modified: Wed, 22 Apr 2015 05:08:18 GMT
< ETag: "4c6820d314fd005212fcd46192302de7"
< Accept-Ranges: bytes
< Content-Type: application/xml
< Content-Length: 867
< Server: AmazonS3
< 
* Connection #0 to host t1234.s3.amazonaws.com left intact
* Found bundle for host t1234.s3.amazonaws.com: 0x7f9e629a4510
* Re-using existing connection! (#0) with host t1234.s3.amazonaws.com
* Connected to t1234.s3.amazonaws.com (54.231.8.121) port 443 (#0)
> HEAD /channel.xml HTTP/1.1
Host: t1234.s3.amazonaws.com
User-Agent: aws-sdk-php2/2.8.1 Guzzle/3.9.3 curl/7.39.0 PHP/5.6.3
Date: Wed, 22 Apr 2015 05:13:01 +0000
Authorization: AWS ***:***

< HTTP/1.1 404 Not Found
< x-amz-request-id: 5A06B1F44758F0BB
< x-amz-id-2: Ul6zZG8lTt6B9sO6LSiiPxte5lgO8a4fOns7tk6jZQxfDT1kgiEIJzK4riDxHRpA
< Content-Type: application/xml
< Transfer-Encoding: chunked
< Date: Wed, 22 Apr 2015 05:13:00 GMT
< Server: AmazonS3
< 
* Connection #0 to host t1234.s3.amazonaws.com left intact
* Rebuilt URL to: https://t1234.s3.amazonaws.com/?max-keys=1&prefix=channel.xml%2F
* Found bundle for host t1234.s3.amazonaws.com: 0x7f9e629a4510
* Re-using existing connection! (#0) with host t1234.s3.amazonaws.com
* Connected to t1234.s3.amazonaws.com (54.231.8.121) port 443 (#0)
> GET /?max-keys=1&prefix=channel.xml%2F HTTP/1.1
Host: t1234.s3.amazonaws.com
User-Agent: aws-sdk-php2/2.8.1 Guzzle/3.9.3 curl/7.39.0 PHP/5.6.3
Date: Wed, 22 Apr 2015 05:13:01 +0000
Authorization: AWS ***:***

< HTTP/1.1 200 OK
< x-amz-id-2: WoNwmeqhER3YNpDR54s1fSiHc5CnKrXWrOdJWZTBjEDEwDlH1POv078MJMsLMVVH
< x-amz-request-id: D5BB659199609875
< Date: Wed, 22 Apr 2015 05:13:03 GMT
< Content-Type: application/xml
< Transfer-Encoding: chunked
< Server: AmazonS3
< 
* Connection #0 to host t1234.s3.amazonaws.com left intact
* Found bundle for host t1234.s3.amazonaws.com: 0x7f9e629a4510
* Re-using existing connection! (#0) with host t1234.s3.amazonaws.com
* Connected to t1234.s3.amazonaws.com (54.231.8.121) port 443 (#0)
> PUT /channel.xml HTTP/1.1
Host: t1234.s3.amazonaws.com
User-Agent: aws-sdk-php2/2.8.1 Guzzle/3.9.3 curl/7.39.0 PHP/5.6.3
x-amz-acl: foo
Content-Type: application/xml
Content-MD5: TGgg0xT9AFIS/NRhkjAt5w==
Date: Wed, 22 Apr 2015 05:13:02 +0000
Authorization: AWS ***:***
Content-Length: 867

* We are completely uploaded and fine
< HTTP/1.1 400 Bad Request
< x-amz-request-id: 01ABB7C3A85742B1
< x-amz-id-2: 5XstUWat+GQwRr2WOL59dcyI2TRjpE4RlUiSiPC1vhGr12oo5aKSmV8ljc4yoWj3
< Content-Type: application/xml
< Transfer-Encoding: chunked
< Date: Wed, 22 Apr 2015 05:13:02 GMT
< Connection: close
< Server: AmazonS3
< 
* Closing connection 0
```

As you can see, it tried to send a PutRequest with my bogus ACL and triggered a 400 response. You can also see that using the stream wrapper to perform a copy is far less efficient that using CopyObject directly, so I definitely recommend that over using the stream wrapper.

I'm going to go ahead and close this issue. If you can provide more information on why this is not working for you, then I'd be happy to help.

**Closed by mtdowling** 2015-04-22 05:16 UTC
Labels: awaiting-reply
