### ISSUE TITLE
SDK v2.8.* S3 Memory Leak

### ISSUE THREAD

**Issue by pinguo-shenqiang** [aws/aws-sdk-php#957] opened 2016-04-08 02:18 UTC
Sorry, I test it again in my PHP5.6 machine. It is still present :( 
My memory usage is still climbing. So comfuse .

There is some information about how to reproduce it. Perhaps it is useful for debug.
The context is the [https://github.com/aws/aws-sdk-php/issues/956]

I use Composer to install the AWS SDK (follow as http://docs.aws.amazon.com/aws-sdk-php/v2/guide/installation.html)

PHP Version => 5.6.19

<?php
require 'vendor/autoload.php';
use Aws\Common\Credentials\Credentials;

$strBucket = 'album-analysis-cn';
$strKey = '0000000456ea6e5781937361ea8b/2/0';

$accessKeyId = '...';
$secretAccessKey = '...';
$credentials = new Credentials($accessKeyId, $secretAccessKey);
$client = Aws\S3\S3Client::factory(
     array(
        'credentials' => $credentials,
        'region' => 'cn-north-1',
        'client.backoff' => false
     )
);

var_dump(gc_enabled());
$i = 0;
while ($i++ >= 0) {
     $arrArgs = array(
         'Bucket' => $strBucket,
         'Key'    => $strKey
     );
     $arrHeader = $client->getObject($arrArgs);
     echo $i . "\n";
     gc_collect_cycles(); 
}
Could you help me to resolve it? Thx

BTW, php upgrading is a huge project to me. I can not use the latest SDK because of php version.

**Comment by jeskew** [comment] 2016-04-08 14:16
Running the same script but replacing the last two lines in the loop with `echo memory_get_usage() . "\n";`, I see that memory usage holds at a steady 5,160,840 bytes used for the duration of the script:
```php
$strBucket = 's3eskew';
$strKey = 'keykey';

$client = Aws\S3\S3Client::factory([
    'region' => 'us-west-2'
]);

$client->putObject(['Bucket' => $strBucket, 'Key' => $strKey, 'Body' => 'abc123']);

for ($i = 0; $i < 10000; $i++) {
    $arrArgs = [
        'Bucket' => $strBucket,
        'Key' => $strKey
    ];
    $arrHeader = $client->getObject($arrArgs);
    echo memory_get_usage() . "\n";
}
```

Switching to use hard-coded credentials had no effect on the outcome; memory usage held at a constant  5,159,272 bytes when not using environmental credentials. The memory leak you've detected must be somewhere else in your application.

**Comment by jeskew** [comment] 2016-04-08 22:46
I'm going to go ahead and close this issue, as the memory leak is not reproducible from the posted script, but feel free to reply with questions. We can continue this discussion here even if the issue is closed.

**Closed by jeskew** 2016-04-08 22:46 UTC
Labels: discussion, v2

**Comment by pinguo-ops** [comment] 2016-04-11 01:46
the memory usage held at a constant value what is outputted by php function "memory_get_usage()". However if you use linux command "top", you will see the column "RES" is still increasing. 

I don't know what is the reason.

**Comment by jeskew** [comment] 2016-04-11 02:00
`memory_get_usage`, when called with no parameters, will always tell you how much memory a PHP script is currently using. This is not necessarily the same as how much memory has been allocated by the PHP engine, as PHP may hold onto memory that belonged to freed objects so that it can be allocated to newly created objects. Reassigning memory is cheaper than calling `malloc`, so you may be seeing a PHP engine optimization doing something unexpected. Without knowing any specifics about your system, I would recommend auditing which PHP extensions are installed and checking if any of those have known memory leaks.

If there were an application-level memory leak, you would almost certainly see it in `memory_get_usage`, so application and library code is unlikely to be the culprit. Are you using Elastic Beanstalk, by the way? I saw [a forum issue](https://forums.aws.amazon.com/thread.jspa?threadID=219739&tstart=0) that might be related.

**Comment by pinguo-shenqiang** [comment] 2016-04-12 07:57
thanks to jeskew :+1: . i resolved my question finally. 
The summary is that the use of curl (libcurl version 7.19.7) with ssl_verifyPeer creates a serious memory leak. :(
The document is https://forums.aws.amazon.com/thread.jspa?threadID=72310

So I change my code as bellow:

    <?php
    $accessKeyId = '...';
    $secretAccessKey = '...';
    $credentials = new Credentials($accessKeyId, $secretAccessKey);

    $options = array(
        'credentials' => $credentials,
        'region' => 'cn-north-1',
    );
    $libCurl = curl_version();
    if (version_compare($libCurl['version'], '7.19.7') <= 0) {
        $options = array_merge(
            array('ssl.certificate_authority' => false),
            $options
        );
    }

    $client = Aws\S3\S3Client::factory($options);
    ...

Perhaps it will help other person.
