### ISSUE TITLE
S3 V3 Presigned GET requests - always adds X-Amz-Content-Sha256

### ISSUE THREAD

**Issue by tehscorpion** [aws/aws-sdk-php#954] opened 2016-04-06 21:38 UTC
Hello,
first of all thanks for closing my issue regarding the host header.

The SDK is adding X-Amz-Content-Sha256 even if i want to have a presigned GET request where the content is not known for the client yet.

Your docs are telling me this:
```
You don't include a payload hash in the Canonical Request, because when you create a presigned URL, you don't know the payload content because the URL is used to upload an arbitrary payload. Instead, you use a constant string UNSIGNED-PAYLOAD. 
```

And this:
```
 Unsigned payload option – You include the literal string UNSIGNED-PAYLOAD when constructing a canonical request, and set the same value as the he x-amz-content-sha256 header value when sending the request to S3.
```

Okay, so if i have no payload i should set the URL to: `x-amz-content-sha256=UNSIGNED-PAYLOAD` if im right, or just leave it out but never use it to callculate other hashes.

So i call `createPresignedRequest` from the class `S3Client` like this:
```php
        $command = $client->getCommand('GetObject', [
            'Bucket' => 'myfavoritepics123',
            'Key'    => '5XXXXXXa.jpg'
        ]);
        $request = $client->createPresignedRequest($command, '+20 minutes');
```

Using this, X-Amz-Content-Sha256 will be added to the url regardless if im using GET/PUT/PATCH/POST. But it shouldn't.

```
   /**
     * Always add a x-amz-content-sha-256 for data integrity.
     */
```

As far as i understood your coding, if im using S3 its using the `S3SignatureV3` class and the function is being called from `Middleware.php` which is causing the problem. Please investigate.

**Comment by jeskew** [comment] 2016-04-06 23:09
I'm confused as to what the issue is. S3 requests should always include a checksum for data integrity; for presigned URLs, you can use the string 'UNSIGNED PAYLOAD' instead to allow any or no payload. This is in line with the docs you quote and matches the behavior of S3.

**Comment by harshavardhana** [comment] 2016-04-06 23:32
> I'm confused as to what the issue is. S3 requests should always include a checksum for data integrity; for presigned URLs, you can use the string 'UNSIGNED PAYLOAD' instead to allow any or no payload. This is in line with the docs you quote and matches the behavior of S3.

@tehscorpion can you post the X-Amz-Content-Sha256 here which is generated after createPresignedRequest? need to see if it's "UNSIGNED-PAYLOAD" or an actual sha256?

**Comment by tehscorpion** [comment] 2016-04-07 01:54
@harshavardhana X-Amz-Content-Sha256 is an actual sha256 string
@jeskew if i understand you correctly the sdk produces X-Amz-Content-Sha256 = sha256sum('UNSIGNED-PAYLOAD') since im requesting an object?

**Comment by tehscorpion** [comment] 2016-04-07 02:00
`https://XXXXX.XXX/XXX.XX?X-Amz-Content-Sha256=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=6YHM698SXMHMBTEGT0YM%2F20160407%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20160407T015753Z&X-Amz-SignedHeaders=host&X-Amz-Expires=1200&X-Amz-Signature=f2f62d5b02bce74c15bebe2cf553ca00def36bb8faec416fdaf6d03f622cb96a`

this is the request the newest version of the sdk is producing with:
```
        $command = $client->getCommand('GetObject', [
            'Bucket' => $bucket,
            'Key'    => '5f1e5d9d5f052XXXXX9d62a5d49fa334a.jpg'
        ]);
        $request = $client->createPresignedRequest($command, '+20 minutes');
```

**Comment by harshavardhana** [comment] 2016-04-07 02:00
> @harshavardhana X-Amz-Content-Sha256 is an actual sha256 string
> @jeskew if i understand you correctly the sdk produces X-Amz-Content-Sha256 = sha256sum('UNSIGNED-PAYLOAD') since im requesting an object?

Here is the problem 

```http://localhost:9001/testbucket/bigfile?X-Amz-Content-Sha256=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=WLGDGYAQYIGI833EV05A%2F20160407%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20160407T015905Z&X-Amz-SignedHeaders=host&X-Amz-Expires=600&X-Amz-Signature=cdfa1c72f0ae65e982662c6d55e035e795f979fbbba9530eaaf5bec697628c75
```

The problem is evident here in X-Amz-Content-Sha256 - this is basically sha256 of "empty" string.

**Comment by harshavardhana** [comment] 2016-04-07 02:02
```
<?php
// Include the SDK using the Composer autoloader
date_default_timezone_set('America/Los_Angeles');
require 'vendor/autoload.php';
$client = new Aws\S3\S3Client([
	                          'version' => 'latest',
	                          'region'  => 'us-east-1',
	                          'endpoint' => 'http://localhost:9001'
	                          ]);

// Create S3 client
$command = $client->getCommand('GetObject', [
	                               'Bucket' => 'testbucket',
	                               'Key' => 'bigfile'
	                               ]);

$request = $client->createPresignedRequest($command, '+10 minutes');

$presignedUrl = (string) $request->getUri();
echo $presignedUrl;
```

**Comment by tehscorpion** [comment] 2016-04-07 02:59
The body is `UNSIGNED-PAYLOAD` but `X-Amz-Content-Sha256` is `sha256('')`.
```
$ cat /dev/null|sha256sum
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  -
$ 
```

its this function:
`return Psr7\hash($request->getBody(), 'sha256');` `SignatureV4.php` Line 146

Double checked with my request above
@jeskew is this normal? please clarify.

**Comment by harshavardhana** [comment] 2016-04-07 08:14
Moving to aws-sdk-go and testing . I don't see X-Amz-Content-Sha256 being added when there is a payload.

```
$ go run presign-get.go
2016/04/07 00:02:01 The URL is http://localhost:9000/testbucket/bigfile?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=WLGDGYAQYIGI833EV05A%2F20160407%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20160407T070201Z&X-Amz-Expires=900&X-Amz-SignedHeaders=host&X-Amz-Signature=293fd94fff4b8f68781593836654d7f558e6b67f3aa3c637c03203fbbc889761
```

Sample program

```
package main

import (
	"log"
	"time"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/credentials"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/s3"
)

func main() {
	newSession := session.New()
	s3Config := &aws.Config{
		Credentials:      credentials.NewStaticCredentials("WLGDGYAQYIGI833EV05A", "BYvgJM101sHngl2uzjXS/OBF/aMxAN06JrJ3qJlF", ""),
		Endpoint:         aws.String("http://localhost:9000"),
		Region:           aws.String("us-east-1"),
		DisableSSL:       aws.Bool(true),
		S3ForcePathStyle: aws.Bool(true),
	}
	// Create an S3 service object in the default region.
	s3Client := s3.New(newSession, s3Config)

	req, _ := s3Client.GetObjectRequest(&s3.GetObjectInput{
		Bucket: aws.String("testbucket"),
		Key:    aws.String("bigfile"),
	})
	urlStr, err := req.Presign(15 * time.Minute)
        if err != nil {
		log.Println("Failed to sign request", err)
	}
	log.Println("The URL is", urlStr)
}
``

**Comment by jeskew** [comment] 2016-04-07 18:54
It looks like requests are being signed and then presigned, which is where that extra X-Amz-Content-Sha256 is coming from. S3 accepts the request either way, so I will need to investigate whether this can be fixed without affecting other presigned requests.

**Closed** 2016-04-14 20:13 UTC

**Comment by winston-ke** [comment] 2020-08-25 10:28
it should be 'PutObject'
