### ISSUE TITLE
SDK assuming an incorrect Role

### ISSUE THREAD

**Issue by PSiAU** [aws/aws-sdk-php#672] opened 2015-07-03 04:43 UTC
I'm hitting the CloudFormation API from an instance which has a Role attached to it, but the SDK is assuming the wrong Role when performing DescribeStackResources. I had a colleague try the same thing with the Node.js SDK and he wasn't seeing the same problem, i'm assuming it's specific to the PHP SDK.
```
$result = $cfclient->describeStackResources([
    'LogicalResourceId' => 'AutoScaleGroup',
    //'PhysicalResourceId' => '<string>',
    'StackName' => $stackname,
]);
$resources = $result->get('StackResources');
```
Is anyone else seeing this issue?

**Comment by jeremeamia** [comment] 2015-07-07 15:13
The SDK gets the role and role's credentials from the instance itself, so I'm not sure how it could be assuming the wrong role. How are you determining if it is incorrect? What version of the SDK are you using and how are you instantiating the client?

**Comment by PSiAU** [comment] 2015-07-08 03:15
Maybe the SDK isn't getting a role at all. As a test i'm doing a simple describe instances operation and it's getting a UnauthorisedOperation back. The instance definitely has a role attached with pretty much god access (* on everything).
Here's the code, it doesn't get any simpler.
```
require "aws.phar";

date_default_timezone_set('Australia/Sydney');

$ec2client = new Aws\Ec2\Ec2Client([
    'version' => 'latest',
    'region' => 'ap-southeast-2'
]);
$result = $ec2client->describeInstances([
    'InstanceIds' => ['i-xxxxxxxx'],
]);
$ip = $result['Reservations'][0]['Instances'][0]['PrivateIpAddress'];
echo "$ip";
```
Here's what I get back:
PHP Fatal error:  Uncaught exception 'Aws\Ec2\Exception\Ec2Exception' with message 'Error executing "DescribeInstances" on "https://ec2.ap-southeast-2.amazonaws.com"; AWS HTTP error: Client error: 403 UnauthorizedOperation (client): You are not authorized to perform this operation. - <?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>UnauthorizedOperation</Code><Message>You are not authorized to perform this operation.</Message></Error></Errors><RequestID>730ef2e3-3ccc-4c8e-863b-05016f8b9995</RequestID></Response>'

exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: 403' in phar:///home/bambooagent/tmp/blah/aws.phar/GuzzleHttp/Middleware.php:68
Stack trace:
#0 phar:///home/bambooagent/tmp/blah/aws.phar/GuzzleHttp/Promise/Promise.php(199): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#1 phar:///home/bambooagent/tmp/blah/aws.phar/GuzzleHttp/Promise/Promise.php(165): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#2  in phar:///home/bambooagent/tmp/blah/aws.phar/Aws/WrappedHttpHandler.php on line 152

**Comment by jeskew** [comment] 2015-07-08 17:28
By default, the `InstanceProfileProvider` is only used if no credentials are detected in the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables or in an ini file located at `~/.aws/credentials`. Are you sure there's nothing in that file or in those environment variables?

The Node SDK uses the same environment variables and credentials filepath, but node and PHP might be reading different values if there are any `putenv` calls in your PHP code or if there's a `.aws/credentials` file in the home directory of the apache or fpm user (node would look in the home directory of whatever user launched the node process).

**Comment by PSiAU** [comment] 2015-07-09 00:28
I've double checked and there's definitely no credentials in the access and secret key environment variables, nor in ~/.aws/credentials.

**Comment by jeskew** [comment] 2015-07-09 18:12
You could check what key is being used by using [the `debug` configuration option](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#debug) when instantiating your client (make sure to set `scrub_auth` to `false`) and comparing this to what is returned by [curling `http://169.254.169.254/latest/meta-data/iam/security-credentials/<role name>`](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#instance-metadata-security-credentials) on your EC2 instance.

**Comment by PSiAU** [comment] 2015-07-10 01:59
I get a straight up Access Denied running that code:
PHP Fatal error:  Uncaught exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "ListBuckets" on "https://s3-ap-southeast-2.amazonaws.com/"; AWS HTTP error: Client error: 403 AccessDenied (client): Access Denied - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>11EF0336C2D7FA65</RequestId><HostId>dahAjv7uDfhfi1ojed28/8sNMyJSUyeoc0xwf6J5t94dNJbyNl50PCDISY2+Tu3gpVdwvhYC0ec=</HostId></Error>'

It didn't even spit out a key.

The curls are returning the correct role for the instance, and also returning a key, secret, and token. If I plug the key secret and token into the code and run it, it runs just fine.

**Comment by jeskew** [comment] 2015-07-10 03:00
The 403 must be getting converted to an exception before the log function is called. Try this script instead:
```php
<?php

require 'vendor/autoload.php';

use Aws\Credentials\CredentialProvider;
use Aws\Credentials\CredentialsInterface;

call_user_func(CredentialProvider::env())
    ->then(function (CredentialsInterface $creds) {
        echo "Found credentials on the environment with key {$creds->getAccessKeyId()}\n";
    })
    ->otherwise(function () {
        call_user_func(CredentialProvider::ini())
            ->then(function (CredentialsInterface $creds) {
                echo "Found credentials on the filesystem with key {$creds->getAccessKeyId()}\n";
            })
            ->otherwise(function () {
                call_user_func(CredentialProvider::instanceProfile())
                    ->then(function (CredentialsInterface $creds) {
                        echo "Found credentials on the instance with key {$creds->getAccessKeyId()}\n";
                    })
                    ->otherwise(function () { echo "No credentials found.\n"; });
            });
    });

$s3 = new \Aws\S3\S3Client([
    'version' => 'latest',
    'region' => 'us-west-2',
]);

try {
    $s3->listBuckets();
} catch (\Aws\Exception\AwsException $e) {
    $matches = [];
    if (preg_match(
        '@AWS4-HMAC-SHA256 Credential=([^/]+)/@',
        $e->getRequest()->getHeaderLine('Authorization'),
        $matches
    )) {
        echo "Request sent with key: {$matches[1]}\n"; die;
    }
}
```

**Comment by PSiAU** [comment] 2015-07-10 03:13
Nice that worked.
It's returning a different key each time I run it. The curl returns the same key if I run it a few times consecutively, but not that PHP code. Not sure what that means....

**Comment by jeskew** [comment] 2015-07-10 03:55
Does it always say "Found credentials on the instance"?

**Comment by PSiAU** [comment] 2015-07-10 03:59
The only output is "Request sent with key: xxxxxxxxx" (substituted the real key with xxx's).

**Comment by jeskew** [comment] 2015-08-18 23:11
Closing, as we were never able to reproduce. Please feel free to reopen if you have any further questions.

**Closed by jeskew** 2015-08-18 23:11 UTC

**Comment by PSiAU** [comment] 2015-08-27 05:03
Found the cause of this.
We use proxies in our environment. The SDK was talking to the AWS API through the proxies, and it was thus returning the role information of the proxy servers.

**Comment by jeskew** [comment] 2015-08-27 06:25
Thanks for tracking down the root cause, @PSiAU. We were all stumped by this one.
