### ISSUE TITLE
Version 3 Preview Feedback

### ISSUE THREAD

**Issue by jeremeamia** [aws/aws-sdk-php#368] opened 2014-10-16 16:26 UTC
We [recently announced the preview of Version 3 of the SDK](http://blogs.aws.amazon.com/php/post/Tx3RR28K9AAHPD1/Version-3-Preview-of-the-AWS-SDK) and tagged `3.0.0-beta.1`.

I'd like to use this issue as a thread to collect your thoughts, feedback, and ideas related to Version 3, so we can make improvements (and changes, if necessary) before our stable release (TBD, but probably in a couple of months).

We hope are excited! :smiley:

**Comment by mtdowling** [comment] 2015-01-05 23:06
@iwai That looks like it's likely a bug in the React RingPHP adapter. I suggest opening a small reproducible test case on that repository: https://github.com/WyriHaximus/ReactGuzzleRing

**Comment by mtdowling** [comment] 2015-01-28 20:00
Thanks for all the feedback we've received so far.

I'm going to close this issue, but please feel free to continue to provide v3 feedback on this issue.

**Closed by mtdowling** 2015-01-28 20:00 UTC
Labels: discussion, v3
