### ISSUE TITLE
Documentation and Api2.json missmatch for Sqs::receiveMessage

### ISSUE THREAD

**Issue by jderusse** [aws/aws-sdk-php#2007] opened 2020-05-10 20:18 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
In `SqsClient::receiveMessage`, The api2.json define that [AttributeNames](https://github.com/aws/aws-sdk-php/blob/master/src/data/sqs/2012-11-05/api-2.json#L905) is a list of enum defined by [QueueAttributeName](https://github.com/aws/aws-sdk-php/blob/master/src/data/sqs/2012-11-05/api-2.json#L310-L317). While the values defined is the documentation are more likely a list of `MessageSystemAttributeName`.

I'm not sure this repository is the right place for this issue, but I can't find what is generating those json files.

The fix should be something like:
```diff
     "ReceiveMessageRequest":{
       "type":"structure",
       "required":["QueueUrl"], 
       "members":{
         "QueueUrl":{"shape":"String"},
-        "AttributeNames":{"shape":"AttributeNameList"},
+        "AttributeNames":{"shape":"MessageSystemAttributeNameList"},
         "..."
       }
     },
+    "MessageSystemAttributeNameList":{
+      "type":"list",
+      "member":{
+        "shape":"MessageSystemAttributeName",
+        "locationName":"AttributeName"
+      },
+      "flattened":true
+    },
     "MessageSystemAttributeName":{
       "type":"string",
       "enum":[
+        "All",
         "SenderId",
         "SentTimestamp",
         "..."
       ]
     },
```

**Version of AWS SDK for PHP?**
Example: v3.133.6
* get SDK version by printing the output of `Aws\Sdk::VERSION` in your code 
* if the SDK was installed via composer you can see the version installed with `composer show -i` 

**Version of PHP (`php -v`)?**
not relevant

**To Reproduce (observed behavior)**
not relevant

**Expected behavior**
calling ReceiveMessage with a value defined in the documentation (ie. `ApproximateFirstReceiveTimestamp`) match the the schema

**Screenshots**

**Additional context**

nb: This is probably the root issue of https://github.com/aws/aws-sdk-cpp/issues/83 and https://github.com/boto/boto3/issues/1820

**Comment by diehlaws** [comment] 2020-05-14 22:02
Hi @jderusse, thanks for reaching out to us about this.  The API model is provided to us by the service team, which is then used by the AWS SDKs to generate the service client. Looking at the [ReceiveMessage](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html) page of the SQS API Reference it doesn't look like the attributes documented for `AttributeName` matches up with the list of valid values at the bottom of this parameter, which lines up with the discrepancy you've mentioned in the API model. I've reached out to the SQS team internally about this mismatch, once I hear back from them I'll update the issue accordingly.

That being said, I tested issuing a `ReceiveMessage` call with the AWS SDKs for PHP and Go including `ApproximateFirstReceiveTimestamp` and `SenderId` in the `AttributeName` parameter. In both cases the service included each of these attributes in the response.

**Comment by Nyholm** [comment] 2020-05-27 14:11
Just a friendly ping. When do we expect an answer from the service team?

**Comment by diehlaws** [comment] 2020-05-28 18:41
Hi @Nyholm, unfortunately the SQS team has not yet responded to my request. I've reached out to them again and will update the issue once they respond.

**Comment by Nyholm** [comment] 2020-06-30 12:54
Did we ever get any response from the SQS team?

**Comment by Nyholm** [comment] 2020-08-08 10:10
Friendly ping

**Comment by SamRemis** [comment] 2021-09-10 22:32
Thank you for bringing this up and keeping this issue alive with a comment.  It looks like they never responded to Alex, I'll escalate it how I'm able

**Comment by Nyholm** [comment] 2022-09-11 00:50
This should still be open

**Comment by stobrien89** [comment] 2023-03-22 16:12
Hi all,

Apologies for the delay here.  We have since moved issues of this nature to a more central `aws-sdk` repository— this issue is the result of incorrect SQS documentation upstream and it affects multiple SDKs.  I'm going to close this as a duplicate of https://github.com/aws/aws-sdk/issues/56 and escalate this with the SQS team.

**Closed by stobrien89** 2023-03-22 16:12 UTC
Labels: service-api
