### ISSUE TITLE
PHP Fatal error:  Allowed memory size of x bytes exhausted when upload a lage file in multiple parts using PHP SDK Low-Level API

### ISSUE THREAD

**Issue by Xylane** [aws/aws-sdk-php#1572] opened 2018-06-24 10:40 UTC
Hello,

When using the example given on the official documentation (see below) to upload large files (for example 6GB), the script ends with a PHP fatal error PHP Fatal error:  "Allowed memory size of 1073741824 bytes exhausted (tried to allocate 104857632 bytes)" on the $s3->uploadPart(...) line.

I noticed that the memory usage is increasing at each call of $s3->uploadPart(...) until it reaches the PHP memory limit, which crashes the script.

The only way that I found to bypass this issue is to manually call gc_collect_cycles() after each uploadPart(...), which keeps the memory usage to a stable level.

According to some forums, the low level API creates temporary files of the chosen chunk size and so eats up the memory (even you destroy the s3_client object).

Expected behaviour : free the memory space used by the temporary file once the specified part is uploaded.

Official documentation : https://docs.aws.amazon.com/AmazonS3/latest/dev/LLuploadFilePHP.html

**Comment by kstich** [comment] 2018-06-25 16:49
Closing as duplicate of #1273

**Closed by kstich** 2018-06-25 16:49 UTC
Labels: duplicate

**Comment by jschwarzwalder** [comment] 2018-06-25 20:37
@Xylane Can you help me understand what needs to be changed in the code example?

When I look at the code in the [S3 docs](https://github.com/awsdocs/amazon-s3-developer-guide/blob/master/doc_source/LLuploadFilePHP.md)  it is using a normal s3 client instead of a multipartUploader like is included in the [SDK for PHP Docs](https://github.com/awsdocs/aws-php-developers-guide/blob/master/doc_source/s3-multipart-upload.rst) example. 

It was my understanding that if a file is larger than 5GB, then you need to use a MultipartUploader.

**Comment by Xylane** [comment] 2018-06-26 07:00
@jschwarzwalder Of course :)

The documentation I mentioned in my initial post (https://docs.aws.amazon.com/AmazonS3/latest/dev/LLuploadFilePHP.html) IS using MultipartUploader (line 16). uploadPart is just a low-level function used to manually define which part you want to upload once you initiated the multipartUpload using $s3->createMultipartUpload(). 

The following page mentions clearly that "You can upload large files to Amazon S3 in multiple parts. You must use a multipart upload for files larger than 5 GB. [...] If you need to pause and resume multipart uploads, vary part sizes during the upload, or do not know the size of the data in advance, use the low-level PHP API. For more information, see Using the AWS PHP SDK for Multipart Upload (Low-Level API). 

And this AWS PHP SDK for Multipart Upload (Low-Level API) is exactly what I use.

Regarding the changes to make in the documentation, one basic workaround is to manually call gc_collect_cycles() after using uploadPart().

So the code will look like : 

`<?php

require 'vendor/autoload.php';

use Aws\S3\S3Client;

$bucket = '*** Your Bucket Name ***';
$keyname = '*** Your Object Key ***';
$filename = '*** Path to and Name of the File to Upload ***';

$s3 = new S3Client([
    'version' => 'latest',
    'region'  => 'us-east-1'
]);

$result = $s3->createMultipartUpload([
    'Bucket'       => $bucket,
    'Key'          => $keyname,
    'StorageClass' => 'REDUCED_REDUNDANCY',
    'ACL'          => 'public-read',
    'Metadata'     => [
        'param1' => 'value 1',
        'param2' => 'value 2',
        'param3' => 'value 3'
    ]
]);
$uploadId = $result['UploadId'];

// Upload the file in parts.
try {
    $file = fopen($filename, 'r');
    $partNumber = 1;
    while (!feof($file)) {
        $result = $s3->uploadPart([
            'Bucket'     => $bucket,
            'Key'        => $keyname,
            'UploadId'   => $uploadId,
            'PartNumber' => $partNumber,
            'Body'       => fread($file, 5 * 1024 * 1024),
        ]);
        $parts['Parts'][$partNumber] = [
            'PartNumber' => $partNumber,
            'ETag' => $result['ETag'],
        ];
        $partNumber++;
        gc_collect_cycles();

        echo "Uploading part {$partNumber} of {$filename}." . PHP_EOL;
    }
    fclose($file);
} catch (S3Exception $e) {
    $result = $s3->abortMultipartUpload([
        'Bucket'   => $bucket,
        'Key'      => $keyname,
        'UploadId' => $uploadId
    ]);

    echo "Upload of {$filename} failed." . PHP_EOL;
}

// Complete the multipart upload.
$result = $s3->completeMultipartUpload([
    'Bucket'   => $bucket,
    'Key'      => $keyname,
    'UploadId' => $uploadId,
    'MultipartUpload'    => $parts,
]);
$url = $result['Location'];

echo "Uploaded {$filename} to {$url}." . PHP_EOL;`

Please note that THERE IS a memory leak, but GC mechanism is able to detect it and to free the memory when you call it.

The best would be to find what is causing this memory consumption and fix it inside the SDK. I guess that you forgot to unset some variable somewhere in the uploadPart() function...
Please note that PHP garbage collection mechanism is just there to assist in memory management, but if your code is well written it shouldn't be necessary.

Regards,

Lionel
