### ISSUE TITLE
Allow passing the private key as a string for CloudFrontClient::getSignedUrl

### ISSUE THREAD

**Issue by ntzm** [aws/aws-sdk-php#1930] opened 2019-12-17 16:13 UTC
### Is this related to a problem?

We store secrets as environment variables, but `getSignedUrl` requires a path to the private key.

### Feature description

I would like to be able to pass in a string that contains the private key instead of the path

### Describe alternatives you've considered

Perhaps a new key, like `private_key_string`

**Comment by srchase** [comment] 2019-12-17 16:53
Related issue: https://github.com/aws/aws-sdk-php/issues/1928

**Comment by diehlaws** [comment] 2019-12-18 19:16
Hi @ntzm, thanks for reaching out to us. Since this is a duplicate of #1928 I'll be closing this issue to keep communication on this feature request on a single issue. Please refer to that issue for updates on this feature.

**Closed by diehlaws** 2019-12-18 19:16 UTC
Labels: duplicate, feature-request
