### ISSUE TITLE
Upload issue with cname settings

### ISSUE THREAD

**Issue by yellow1912** [aws/aws-sdk-php#810] opened 2015-10-31 05:35 UTC
Hello,

I'm running into issue with cname style url which I have found a few related tickets but since they do not address the exact issue I'm seeing I will open a new one here.

I'm using the latest v3 sdk php version, my setup is that I have my domain docked on CloudFlare, I have created a CNAME record on CloudFlare which points to a bucket with the exact same name on my S3 bucket US East 1 region

My settings when creating new S3Client looks like this:

```
$client = new S3Client([
    "credentials" => [
        "key"    => ...,
        "secret" => ...,
    ],
    "region"   => ...,
    "version"  => ...,
    "bucket_endpoint" => true,
    "endpoint" => "http://my.bucket.name.domain.com"
]); 
```
(I take this settings from https://github.com/aws/aws-sdk-php/issues/692)

The client works fine when retrieving object url (I haven't tested the presigned option yet). However, when I attempt to put new object I always run into this:

```
[Aws\S3\Exception\S3Exception] 
Error executing "PutObject" on "http://my.bucket.name.domain.com/26e1437d1fd24d34b81d0c4500279d01/assets/bootstrap.css"; AWS HTTP error: cURL error 7: Failed to connect to my.bucket.name.domain.com port 80: Connection timed out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)


[GuzzleHttp\Exception\ConnectException] 
cURL error 7: Failed to connect to my.bucket.name.domain.com port 80: Connection timed out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

I'm struggling to find a solution for this issue, any pointer is really appreciated.

Edit: after further checking, this could be an issue with CloudFlare, I will keep this issue updated

**Comment by jeskew** [comment] 2015-10-31 16:58
Since the exception message provided indicates that a cURL "failed to connect" error was encountered, I think you're probably right in the assumption that the problem is in how the CNAME URL is forwarding to S3. Did you follow the instructions on the S3 documentation concerning [how to set up CNAME access to buckets](http://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html#VirtualHostingCustomURLs)?

**Comment by jeskew** [comment] 2015-11-06 01:41
Closing, as the issue doesn't seem to lie with the SDK. Please feel free to reopen if you have any questions or concerns.

**Closed by jeskew** 2015-11-06 01:41 UTC
Labels: awaiting-reply
