### ISSUE TITLE
SQS.createQueue does not allow FifoQueue attribute for non-FIFO queues

### ISSUE THREAD

**Issue by holtkamp** [aws/aws-sdk-php#1331] opened 2017-07-18 08:43 UTC
When creating an SQS Queue, it seems the `FifoQueue` attribute is only allowed for queues that end in `.fifo`. 

```php
//works
$result = $sqsClient->createQueue([
    'QueueName' => 'foo_queue.fifo',
    'Attributes' => [
        'FifoQueue' => 'true',
    ]
]);

//fails
$result = $sqsClient->createQueue([
    'QueueName' => 'bar_queue',
    'Attributes' => [
        'FifoQueue' => 'false',
    ]
]);
```

This makes it impossible to use something like:

```php
$result = $sqsClient>createQueue([
    'QueueName' => $queueName,
    'Attributes' => [
        'FifoQueue' => $this->isFifoQueue($queueName) ? 'true' : 'false',
    ],
]);
```
For queues that do not end in `.fifo`, 'FifoQueue' => 'false' is used, resulting in:

```
Message: Error executing "CreateQueue" on "https://sqs.eu-west-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://sqs.eu-west-1.amazonaws.com` resulted in a `400 Bad Request` response: SenderI (truncated...) InvalidAttributeName (client): Unknown Attribute FifoQueue. - SenderInvalidAttributeNameUnknown Attribute
```

Is this expected behaviour? This forces a user to [implement it a bit like this](https://github.com/holtkamp/bernard/blob/3caf8c857c1a39da255693aab464e69957bf4062/src/Driver/SqsDriver.php#L67-L77), which seems overkill...

**Comment by kstich** [comment] 2017-07-18 17:57
@holtkamp That error message is being surfaced from SQS, not the SDK. I've reached out to the service team regarding the issue. You can also try to engage with them on the [AWS forums](https://forums.aws.amazon.com/forum.jspa?forumID=12)

**Comment by holtkamp** [comment] 2017-07-18 22:24
@kstich thanks for the swift response... did not know there was a difference between the SDK and SQS support section 😊 . This is not a big issue, but I hope it now appears on a certain "radar" at Amazon.

**Comment by kstich** [comment] 2017-08-29 20:06
The service team has acknowledge this issue and is working on an update. Not sending the `'FifoQueue'` attribute if it is false, like in your workaround, is the recommended course of action until an update is released.

I am closing this issue as we have confirmed it is not related to the PHP SDK specifically.

**Closed by kstich** 2017-08-29 20:06 UTC
Labels: API-Issue

**Comment by jpopadak** [comment] 2017-12-18 23:05
Has there been any progress update on this? It has been a few months now.

**Comment by JTCozart** [comment] 2019-07-31 20:24
@kstich Is there another open issue that we can reference to see if and when this is fixed in the API?

**Comment by ssanpietro-gr** [comment] 2020-02-12 00:10
I would also like to know if there is another open issue for this -- this still appears to bee an issue.

**Comment by artit91** [comment] 2020-02-22 22:23
I can confirm, it still happens.

**Comment by oliversalzburg** [comment] 2023-01-05 09:55
> The service team has acknowledged this issue and is working on an update.
I really hope those guys don't work themselves to death over this fix. 5 years in the making and still no solution. This seems to be a real tough one. Best of luck!
