### ISSUE TITLE
S3 StreamWrapper ignores HTTP error response code

### ISSUE THREAD

**Issue by UlrichEckhardt** [aws/aws-sdk-php#609] opened 2015-06-04 10:50 UTC
If you don't have permissions to access a particular file, the function `file_get_contents()` returns the wrong content. Instead of the content, the data retrieved is just an error response like `<?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>123456789</RequestId><HostId>garblebase64digook=</HostId></Error>`. I have debugged this to `openReadStream()`, which returns `true`, while the HTTP response says "403 Forbidden" (in `$this->body->customData->response_headers`).

I'm using version 2.8.8 of the SDK, btw.

**Comment by jeremeamia** [comment] 2015-06-08 23:12
Thanks for reporting this. We'll look into it.

**Comment by mtdowling** [comment] 2015-06-25 22:43
Fixed in https://github.com/aws/aws-sdk-php/issues/657

**Closed by mtdowling** 2015-06-25 22:43 UTC
Labels: bug, streamwrapper, v2

**Comment by UlrichEckhardt** [comment] 2015-06-26 06:47
I just looked over the changes and the test surprises me. `file_get_contents()` there seems to be expected to throw an exception, is that right? Reason I ask is that that's a breaking interface change when compared to PHP's implementation, which returns `false` in case the files isn't present or not readable.

**Comment by mtdowling** [comment] 2015-06-26 06:56
It's only throwing because PHPUnit is turning warnings into exceptions. It just emits a warning in practice and returns false.

**Comment by UlrichEckhardt** [comment] 2015-06-26 11:54
Oh, yes, that makes sense. Thank you!

**Comment by billwhitney** [comment] 2015-07-27 15:17
I am having problems with Stream Wrapper file_get_contents not returning FALSE on an error. In this case the error is "file does not exist". file_get_contents throws an exception, or if I use @file_get_contents it does not return FALSE but instead returns empty file contents. Am I missing something? The above comment by UlrichEckhardt still seems to be an issue.

**Comment by UlrichEckhardt** [comment] 2015-07-28 08:08
Which version are you using? This issue was only fixed in version 2.8.13 of the 2.x branch and I'm not sure about the 3.x branch at all, neither whether the bug as present there nor whether it was fixed there.

**Comment by billwhitney** [comment] 2015-07-28 15:41
I am using 2.8.14. When I used an earlier version it did not even throw an exception, so I assume I am using a "fixed" version.

**Comment by jeskew** [comment] 2015-07-28 18:49
@billwhitney An exception should only be thrown if you have an error handler that converts errors to exceptions, as PHPUnit's error handler does. All the StreamWrapper is doing is calling `trigger_error`.

I was able to reproduce the issue with `@file_get_contents` returning an empty string instead of false and believe #707 should fix it.
