### ISSUE TITLE
SqsClient sends requests to QueueUrl regardless of endpoint parameter when creating client

### ISSUE THREAD

**Issue by mariusgrigaitis** [aws/aws-sdk-php#1009] opened 2016-06-03 08:20 UTC
Testcase:

```
<?php

require "vendor/autoload.php";

use Aws\Sqs\SqsClient;
$sqs = new SqsClient(["version" => "latest", "region" => "us-east-1", "endpoint" => "http://192.168.99.100:81"]);
$sqs->sendMessage(["QueueUrl" => "http://sqs.us-east-1.amazonaws.com/123456789012/test", 'MessageBody' => 'test']);
```

Got:
sendMessage request sent to http://sqs.us-east-1.amazonaws.com

Expected:
sendMessage request sent to http://192.168.99.100:81

**Comment by cjyclaire** [comment] 2016-06-03 17:14
@mariusgrigaitis, `$sqs->sendMessage()` delivers a message to the specified `QueueUrl`. For configuration in Client [Endpoint](http://docs.aws.amazon.com/general/latest/gr/rande.html), here are endpoints that are [supported](http://docs.aws.amazon.com/general/latest/gr/rande.html#sqs_region) in SQS.

**Comment by mariusgrigaitis** [comment] 2016-06-06 07:29
What I'm trying to achieve is mock SQS by providing different endpoint.

Strange thing is that different SDKs behave differently. I looked into boto3, boto2 and wasn't able to replicate such case.

**Comment by cjyclaire** [comment] 2016-06-07 04:13
@mariusgrigaitis , thanks for clarification. Double checked with boto team, so both our SDKs use default service behavior. And with your code snippets, `endpoint` is configured in client correctly and sqs works fine. 

AWS endpoint is the entry point for web service to make the request. I couldn't reproduce any issue, could you provide more information? For example, what boto behavior did you observe?

**Comment by mariusgrigaitis** [comment] 2016-06-07 07:33
That's the different behavior I'm talking about:

```
➜  /tmp cat php/test.php
<?php

require "vendor/autoload.php";

use Aws\Sqs\SqsClient;
$sqs = new SqsClient(["version" => "latest", "region" => "us-east-1", "endpoint" => "http://192.168.99.100:81"]);
$queueUrl = $sqs->getQueueUrl(["QueueName" => "test"]);
print $queueUrl->get("QueueUrl");
print $sqs->sendMessage(["QueueUrl" => $queueUrl->get("QueueUrl"), 'MessageBody' => 'test']);

➜  /tmp cat python/test.py
import boto3

sqs = boto3.client('sqs', endpoint_url="http://192.168.99.100:81")

queue = sqs.get_queue_url(QueueName="test")
print queue.get("QueueUrl")
print sqs.send_message(QueueUrl=queue.get("QueueUrl"), MessageBody='test')
➜  /tmp aws --endpoint=http://192.168.99.100:81 sqs create-queue --queue-name test
{
    "QueueUrl": "http://sqs.us-east-1.amazonaws.com/123456789012/test"
}
➜  /tmp python python/test.py
http://sqs.us-east-1.amazonaws.com/123456789012/test
{u'MD5OfMessageBody': '\n            098f6bcd4621d373cade4e832627b4f6\n        ', 'ResponseMetadata': {'HTTPStatusCode': 200, 'RequestId': '\n            27daac76-34dd-47df-bd01-1f6e873584a0\n        '}, u'MessageId': '\n            ca1c8579-bd21-43c2-a9a7-cbf4ec51f959\n        '}
➜  /tmp php php/test.php
http://sqs.us-east-1.amazonaws.com/123456789012/testPHP Fatal error:  Uncaught exception 'Aws\Sqs\Exception\SqsException' with message 'Error executing "SendMessage" on "http://sqs.us-east-1.amazonaws.com/123456789012/test"; AWS HTTP error: Client error: `POST http://sqs.us-east-1.amazonaws.com/123456789012/test` resulted in a `403 Forbidden` response:
<?xml version="1.0"?><ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Type>Sender</Type><Code>E (truncated...)
 ExpiredToken (client): The security token included in the request is expired - <?xml version="1.0"?><ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Type>Sender</Type><Code>ExpiredToken</Code><Message>The security token included in the request is expired</Message><Detail/></Error><RequestId>9d8418fe-dc5a-5790-b1bd-572ea7598154</RequestId></ErrorResponse>'

exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `POST http://sqs.us-east-1.amazonaws.com/123456789012/test` resulted in a `403 Forbidden` response:
<?xml version="1.0"?><ErrorResponse xmlns in /private/tmp/php/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 192

Fatal error: Uncaught exception 'Aws\Sqs\Exception\SqsException' with message ' in /private/tmp/php/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 192

GuzzleHttp\Exception\ClientException: Client error: `POST http://sqs.us-east-1.amazonaws.com/123456789012/test` resulted in a `403 Forbidden` response:
<?xml version="1.0"?><ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Type>Sender</Type><Code>E (truncated...)
 in /private/tmp/php/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 107

Call Stack:
    0.0001     230528   1. {main}() /private/tmp/php/test.php:0
    0.0269    3273240   2. Aws\Sqs\SqsClient->sendMessage() /private/tmp/php/test.php:9
    0.0269    3273592   3. Aws\AwsClient->__call() /private/tmp/php/test.php:9
    0.0270    3274440   4. Aws\AwsClient->execute() /private/tmp/php/vendor/aws/aws-sdk-php/src/AwsClientTrait.php:78
    0.0275    3308616   5. GuzzleHttp\Promise\Promise->wait() /private/tmp/php/vendor/aws/aws-sdk-php/src/AwsClientTrait.php:59
    0.0276    3308664   6. GuzzleHttp\Promise\Promise->waitIfPending() /private/tmp/php/vendor/guzzlehttp/promises/src/Promise.php:62
    0.0276    3308664   7. GuzzleHttp\Promise\Promise->invokeWaitList() /private/tmp/php/vendor/guzzlehttp/promises/src/Promise.php:225
    0.0281    3336416   8. GuzzleHttp\Promise\Promise->waitIfPending() /private/tmp/php/vendor/guzzlehttp/promises/src/Promise.php:269
    0.0281    3336416   9. GuzzleHttp\Promise\Promise->invokeWaitList() /private/tmp/php/vendor/guzzlehttp/promises/src/Promise.php:225
    0.0281    3336464  10. GuzzleHttp\Promise\Promise->waitIfPending() /private/tmp/php/vendor/guzzlehttp/promises/src/Promise.php:266
    0.0281    3336464  11. GuzzleHttp\Promise\Promise->invokeWaitFn() /private/tmp/php/vendor/guzzlehttp/promises/src/Promise.php:223
    0.0281    3336560  12. GuzzleHttp\Handler\CurlMultiHandler->execute() /private/tmp/php/vendor/guzzlehttp/promises/src/Promise.php:246
    1.5296    3340808  13. GuzzleHttp\Handler\CurlMultiHandler->tick() /private/tmp/php/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php:123
    1.5296    3340856  14. GuzzleHttp\Promise\TaskQueue->run() /private/tmp/php/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php:96
    1.5297    3335944  15. GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() /private/tmp/php/vendor/guzzlehttp/promises/src/TaskQueue.php:61
    1.5297    3336248  16. GuzzleHttp\Promise\Promise::callHandler() /private/tmp/php/vendor/guzzlehttp/promises/src/Promise.php:156
    1.5297    3336296  17. GuzzleHttp\Middleware::GuzzleHttp\{closure}() /private/tmp/php/vendor/guzzlehttp/promises/src/Promise.php:203

Aws\Sqs\Exception\SqsException: Error executing "SendMessage" on "http://sqs.us-east-1.amazonaws.com/123456789012/test"; AWS HTTP error: Client error: `POST http://sqs.us-east-1.amazonaws.com/123456789012/test` resulted in a `403 Forbidden` response:
<?xml version="1.0"?><ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Type>Sender</Type><Code>E (truncated...)
 ExpiredToken (client): The security token included in the request is expired - <?xml version="1.0"?><ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Type>Sender</Type><Code>ExpiredToken</Code><Message>The security token included in the request is expired</Message><Detail/></Error><RequestId>9d8418fe-dc5a-5790-b1bd-572ea7598154</RequestId></ErrorResponse> in /private/tmp/php/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 192

Call Stack:
    0.0001     230528   1. {main}() /private/tmp/php/test.php:0
    0.0269    3273240   2. Aws\Sqs\SqsClient->sendMessage() /private/tmp/php/test.php:9
    0.0269    3273592   3. Aws\AwsClient->__call() /private/tmp/php/test.php:9
    0.0270    3274440   4. Aws\AwsClient->execute() /private/tmp/php/vendor/aws/aws-sdk-php/src/AwsClientTrait.php:78
    0.0275    3308616   5. GuzzleHttp\Promise\Promise->wait() /private/tmp/php/vendor/aws/aws-sdk-php/src/AwsClientTrait.php:59
    1.5323    3498032   6. GuzzleHttp\Promise\RejectedPromise->wait() /private/tmp/php/vendor/guzzlehttp/promises/src/Promise.php:65
```

**Comment by cjyclaire** [comment] 2016-06-07 17:42
@mariusgrigaitis thanks for the information! Yet I still couldn't reproduce the issue, I can see that request is send to customized endpoint. 

Meanwhile, referred in your error message: `ExpiredToken (client): The security token included in the request is expired`, could you double check your credentials? You would normally see a 403 when you're using the wrong credentials. Are you using environment variables, an ini file, or the EC2 metadata service?

**Comment by mariusgrigaitis** [comment] 2016-06-08 06:45
Credentials are not checked by fake endpoint, so any request to mocked request should pass credentials check. Expired token error means code hit the real endpoint.

You can create fake endpoint using moto (to test the case):
```bash
pip install moto
moto_server sqs
```

**Comment by cjyclaire** [comment] 2016-06-09 04:19
@mariusgrigaitis ,thanks,  I'm able to reproduce the issue right now, and working on investigation.

Since my error is different from the credential error that you received, and as you mentioned, credentials are not checked by the faked endpoint, could you try add `'credentials' => false` in client configuration? I'm proposing this because the SDK tries to source credentials from the environment to sign request by default, I'm curious whether disabling this behavior would help?

**Comment by mariusgrigaitis** [comment] 2016-06-09 13:48
As I have mentioned, it's not a problem with credentials. Problem is that it hits real AWS endpoint (and I explicitly have wrong credentials set) and this behavior is inconsistent with boto (boto does not hit)

Lets put it the other way:
1) Ensure that SDK is not connecting to real endpoint by changing /etc/hosts: `127.0.0.1 sqs.us-east-1.amazonaws.com`
2) `php php/test.php`
```
http://sqs.us-east-1.amazonaws.com/123456789012/testPHP Fatal error:  Uncaught exception 'Aws\Sqs\Exception\SqsException' with message 'Error executing "SendMessage" on "http://sqs.us-east-1.amazonaws.com/123456789012/test"; AWS HTTP error: cURL error 7: Failed to connect to sqs.us-east-1.amazonaws.com port 80: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)'

exception 'GuzzleHttp\Exception\ConnectException' with message 'cURL error 7: Failed to connect to sqs.us-east-1.amazonaws.com port 80: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in /private/tmp/php/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186
Stack trace:
#0 /private/tmp/php/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /private/tmp/php/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Hand in /private/tmp/php/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 192

Fatal error: Uncaught exception 'Aws\Sqs\Exception\SqsException' with message 'Error executing "SendMessage" on "http://sqs.us-east-1.amazonaws.com/123456789012/test"; AWS HTTP error: cURL error 7: Failed to connect to sqs.us-east-1.amazonaws.com port 80: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in /private/tmp/php/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 192

Aws\Sqs\Exception\SqsException: Error executing "SendMessage" on "http://sqs.us-east-1.amazonaws.com/123456789012/test"; AWS HTTP error: cURL error 7: Failed to connect to sqs.us-east-1.amazonaws.com port 80: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /private/tmp/php/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 192

Call Stack:
    0.0001     230528   1. {main}() /private/tmp/php/test.php:0
    0.0264    3273152   2. Aws\Sqs\SqsClient->sendMessage() /private/tmp/php/test.php:9
    0.0264    3273504   3. Aws\AwsClient->__call() /private/tmp/php/test.php:9
    0.0264    3274352   4. Aws\AwsClient->execute() /private/tmp/php/vendor/aws/aws-sdk-php/src/AwsClientTrait.php:78
    0.0271    3308536   5. GuzzleHttp\Promise\Promise->wait() /private/tmp/php/vendor/aws/aws-sdk-php/src/AwsClientTrait.php:59
    0.3251    3745848   6. GuzzleHttp\Promise\Promise->wait() /private/tmp/php/vendor/guzzlehttp/promises/src/Promise.php:65
    0.3252    3745848   7. GuzzleHttp\Promise\Promise->wait() /private/tmp/php/vendor/guzzlehttp/promises/src/Promise.php:65
    0.3252    3745848   8. GuzzleHttp\Promise\Promise->wait() /private/tmp/php/vendor/guzzlehttp/promises/src/Promise.php:65
    0.3252    3745888   9. GuzzleHttp\Promise\RejectedPromise->wait() /private/tmp/php/vendor/guzzlehttp/promises/src/Promise.php:65
```

**Comment by cjyclaire** [comment] 2016-06-09 22:09
@mariusgrigaitis It's true that PHP and Python behave differently. This is because in PHP SDK, we always use the `QueueUrl`, while in boto, they 'override' the `QueueUrl` with `endpoint_url`.

I've reached out to service team to confirm this behavior. The QueueUrl provided by the service should be taken as the canonical source of truth should the endpoint ever change or be diverted for whatever reason, such as DNS CNAME changes, or queue domain migrations (quite unlikely). It is the unique location for that queue, and using the hardcoded endpoint in an SDK URL in pythons case acts like an 'override'. So PHP would stay the same.

Thank you so much for your patience and respondence!

**Comment by cjyclaire** [comment] 2016-06-10 00:08
So, I'm going to close this issue, yet free free to reopen the issue if you have further questions. ;)

**Closed by cjyclaire** 2016-06-10 00:08 UTC
Labels: question
