### ISSUE TITLE
Intermittent Uncaught exception when uploading large files

### ISSUE THREAD

**Issue by CodeWonderer** [aws/aws-sdk-php#2529] opened 2022-09-22 14:41 UTC
### Describe the bug

I have a daily process which does a multipart upload from EC2 of a large file (~11GB) to S3 Bucket and to retry if any errors. Recently, the process has started to intermittently fail with an "Internal Server Error" response that is uncaught by the retry-mechanism. AWS support suspects the issue to be hitting the AWS request rate limit. To mitigate the issue, I've increase the multi part size to reduce the number of requests (5mb -> 10mb). However, this doesn't solve the problem of the uncaught exception.

Here's an example error:

- Part 759: Error executing "UploadPartCopy" on "https://foo/bar.csv?partNumber=759&uploadId=6FyXX6MDyAxsiuyzQnJqxHh48N8I.SB6m.ocrdTuOpXp6raAG2WJljQoarRRl_cDhJ3uGHwriXM7V9G76_RLbB7_Z0JJ7WtLxmIRIOa6ChPOhIgHTYEHGfrYZVA8r7aNiiI5UddPyOQMCoCEDT.qpKWK.6IrwDsozCyRvYKMVZQ-"; AWS HTTP error: Server error: `PUT https://foo/bar.csv?partNumber=759&uploadId=6FyXX6MDyAxsiuyzQnJqxHh48N8I.SB6m.ocrdTuOpXp6raAG2WJljQoarRRl_cDhJ3uGHwriXM7V9G76_RLbB7_Z0JJ7WtLxmIRIOa6ChPOhIgHTYEHGfrYZVA8r7aNiiI5UddPyOQMCoCEDT.qpKWK.6IrwDsozCyRvYKMVZQ-` resulted in a `500 Internal Server Error` response:
<Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>MVQC6H (truncated...)
 InternalError (server): We encountered an internal error. Please try again. - <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>MVQC6HWKEN1006TE</RequestId><HostId>foobar</HostId></Error>

Here's a similar issue here: https://github.com/aws/aws-sdk-php/issues/912.

Personally, there seems to be 2 issues here:
1. An 5XX response is being returned instead of a 4XX response (assuming 4xx should cover request rate limit)
2. aws-sdk-php doesn't catch InternalError response with \Aws\S3\Exception\S3MultipartUploadException 

If the above 2 issues can't be resolved, what exception should I catch to retry the Internal Server Error response? 

### Expected Behavior

Internal Server Error's to be retried as part of \Aws\S3\Exception\S3MultipartUploadException

### Current Behavior

Internal Server Error is raised as some unknown exception which is uncaught by retry-mechanism.

### Reproduction Steps

Here's sample code similar to daily process (copied and adjusted from application):
```php
<?php

if (!file_exists($file = realpath(__DIR__ . '/vendor/autoload.php'))) {
    throw new \Exception('Unable to load autoloader.');
}


$vendorDir = realpath(__DIR__ . '/vendor/');
require_once($file);

$timesToRetry = 10;
$secondsToSleep = 30;

$client = new Aws\S3\S3Client([
    'version' => '2006-03-01',
    'region'  => 'eu-west-1',
]);
$bucket_name = 'foo';
$key = 'bar';
$content = 'baz';
$acl = 'private';
$options = [
    'ServerSideEncryption' => 'AES256',
    'params' => ['ServerSideEncryption' => 'AES256'],
    'part_size' => 1024 * 1024 * 10, # Increased multipart sizes to avoid upload limits: https://docs.aws.amazon.com/AmazonS3/latest/userguide/qfacts.html
];

$uploaded = false;

for ($i = 0; $i < $timesToRetry; $i++) {
    $retryCount = $i + 1;
    try {
        $uploader = new Aws\S3\ObjectUploader(
            $client,
            $bucket_name,
            $key,
            $content,
            $acl,
            $options
        );

        $uploader->upload();

        $uploaded = true;
        break;
    } catch (\Aws\S3\Exception\S3MultipartUploadException $e) {
        var_dump($e);
        sleep($retryCount * $secondsToSleep);
    }
}

if (!$uploaded) {
    throw new \Exception(sprintf(
        'Failed to upload to s3://%s/%s after %s attempt(s).',
        $bucket,
        $key,
        $timesToRetry
    ));
}

```

### SDK version used

3.235.12

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

EC2: 4.14.51-60.38.amzn1.x86_64. PHP: 7.1.7

**Comment by yenfryherrerafeliz** [comment] 2022-10-02 05:12
Hi @CodeWonderer, thanks for opening this issue. By reviewing the code I think that the exception that is being thrown is instantiated [here](https://github.com/aws/aws-sdk-php/blob/4667dd4b863a8686417e0d2a50da8682d8b68bb5/src/WrappedHttpHandler.php#L195), and it maybe using the default exception class which is set [here](https://github.com/aws/aws-sdk-php/blob/4667dd4b863a8686417e0d2a50da8682d8b68bb5/src/WrappedHttpHandler.php#L50). So, could you please try catching either "Aws\S3\Exception\S3Exception" or "Aws\Exception\AwsException" and see if it works.

Thanks!

**Comment by stobrien89** [comment] 2022-11-03 20:34
Hi @CodeWonderer,

Closing this for now.  Please let us know if you're still having issues.

**Closed by stobrien89** 2022-11-03 20:34 UTC
Labels: bug, response-requested, p2, m

**Comment by tech-122** [comment] 2022-12-02 12:25
Hi @stobrien89  / @yenfryherrerafeliz ,

Sorry for the delayed response. Unfortunately it's an intermittent problem that isn't easily/feasibly reproducible on my side which makes it a waiting game for the error to occur again.

Thank you for your suggestion. Along side applying your suggested fix, I applied suggestions from https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-multipart-upload.html . Sadly, the issue still persists. 

Here's the latest version of the code:

```php
<?php

if (!file_exists($file = realpath(__DIR__ . '/vendor/autoload.php'))) {
    throw new \Exception('Unable to load autoloader.');
}


$vendorDir = realpath(__DIR__ . '/vendor/');
require_once($file);

$timesToRetry = 10;
$secondsToSleep = 30;

$client = new Aws\S3\S3Client([
    'version' => '2006-03-01',
    'region'  => 'eu-west-1',
]);
$bucket_name = 'foo';
$key = 'bar';
$content = 'baz';
$acl = 'private';
$options = [
    'ServerSideEncryption' => 'AES256',
    'params' => ['ServerSideEncryption' => 'AES256'],
    'part_size' => 1024 * 1024 * 10, # Increased multipart sizes to avoid upload limits: https://docs.aws.amazon.com/AmazonS3/latest/userguide/qfacts.html
];

$uploader = new \Aws\S3\ObjectUploader(
    $this->_s3Client,
    $bucket,
    $key,
    $stream,
    $acl,
    $options
);

for ($i = 0; $i < $timesToRetry; $i++) {
    $retryCount = $i + 1;
    try {
        $result = $uploader->upload();
        break;
    } catch (\Aws\S3\Exception\S3MultipartUploadException $e) {
        rewind($stream); # Stop unreadable stream errors. Streams are NOT automatically rewound by $uploader
        var_dump(['error' => $e, 'bucket' => $bucket, 'key' => $key, 'retries' => $retryCount]);
        sleep($retryCount * $secondsToSleep);

        # https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-multipart-upload.html#recovering-from-errors
        $config = ['acl' => $acl, 'state' => $e->getState()] + $options;
        $uploader = new \Aws\S3\MultipartUploader($this->_s3Client, $stream, $config);
    } catch (\Aws\Exception\AwsException $e) {
        rewind($stream); # Stop unreadable stream errors. Streams are NOT automatically rewound by $uploader

        var_dump(['error' => $e, 'bucket' => $bucket, 'key' => $key, 'retries' => $retryCount]);
        sleep($retryCount * $secondsToSleep);
    }
}

if (!isset($result)) {
    throw new \Exception(sprintf(
        'Failed to upload to s3://%s/%s after %s attempt(s).',
        $bucket,
        $key,
        $timesToRetry
    ));
}
```

The only difference I can see from the link provided and previously linked issue with my code is the use of `\Aws\S3\Exception\S3MultipartUploadException` instead of `\Aws\Exception\MultipartUploadException`. I honestly don't think this is the reason it's not catching but I'll change it regardless. 

Any other suggestions to solve this issue?
