### ISSUE TITLE
Allow guzzle/psr-7 2.0 to be installed to fully support Guzzle 7

### ISSUE THREAD

**Issue by antonioribeiro** [aws/aws-sdk-php#2300] opened 2021-08-28 22:30 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
Composer is having trouble resolving package dependencies for Guzzle 7.0, as it's not allowing guzzlehttp/psr7 2.0 to be installed. This package is locked to [guzzlehttp/psr7:^1.7.0](https://github.com/aws/aws-sdk-php/blob/master/composer.json#L21) while Guzzle requirements are ["guzzlehttp/psr7": "^1.7 || ^2.0"](https://github.com/guzzle/guzzle/blob/master/composer.json#L34).

**Solution** 

- Remove `guzzlehttp/psr7:^1.7.0` from composer.json, as it will be required by Guzzle anyway; or
- Allow `guzzlehttp/psr7:^1.7.0 || ^2.0`

**Comment by SamRemis** [comment] 2021-08-30 21:23
closing as a duplicate of #2264

**Closed by SamRemis** 2021-08-30 21:23 UTC
Labels: bug, needs-triage
