### ISSUE TITLE
400 MalformedXML error when using S3 Transfer Manager

### ISSUE THREAD

**Issue by ghost** [aws/aws-sdk-php#653] opened 2015-06-25 17:33 UTC
Using [the example found in the documentation](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-transfer.html), first with 3.0.5 and then with 3.0.6 installed via Composer:
```php
//Here the source and destination are generic values, of course...
$client = new \Aws\S3\S3Client([
    'region'  => 'us-west-2',
    'version' => '2006-03-01',
]);
$source = '/path/to/source/files';
$dest = 's3://bucket';
$manager = new \Aws\S3\Transfer($client, $source, $dest);
$manager->transfer();
```
Results in the Aws\S3\Exception\S3Exception:
> Error executing "PutObject" on "https://s3-us-west-2.amazonaws.com/bucket/"; AWS HTTP error: Client error: 400 MalformedXML (client): The XML you provided was not well-formed or did not validate against our published schema - MalformedXMLThe XML you provided was not well-formed or did not validate against our published schema [...]
(Again, the bucket name in the error has been replaced with a generic...)

...and nothing is being uploaded to S3.

I've investigated the trace:
>[...]/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php(76): Aws\WrappedHttpHandler->parseError(Array, Object(GuzzleHttp\Psr7\Request), Object(Aws\Command)

Though I wasn't able to figure anything out by looking at the __invoke method in WrappedHttpHandler.php (I'm a dummy).

Has something changed recently or is there an issue on my end? I am near certain this was working fine the day before yesterday.

**Comment by jeremeamia** [comment] 2015-06-26 21:08
@ghost Hey, I saw that you closed this. Did you find out something?

**Comment by ethet** [comment] 2015-06-27 11:26
@jeremeamia I wrote this report the other day, but closed it after I received no response (and deleted my account). I figured that it must be a problem on my end, as it seemed to me more people would be complaining if this was actually an issue with the Transfer Manager. 

Are you having problems, too?

I have been using putObject() as a work around, so my frustrations with Transfer Manager haven't disturbed my work too greatly. Though I would much, much prefer that I could get it working as it was a vastly better solution than putObject() for my program.

Oh well.

**Comment by acoulton** [comment] 2015-07-10 13:33
@ethet @jeremeamia I can reproduce this, could you repoen? The issue seems to be when you try (as the example in the docs) to upload to the root of an S3 bucket.

This appears to be because the wrapper attempts to upload all files with an empty `Key` (eg to PUT to the bucket root URL).

```php
$client = new S3Client([
  'region' => 'eu-west-1',
  'version' => '2006-03-01',
]);

$client->uploadDirectory(
    '/tmp/test-dir',
    's3://bucket,
    NULL, // Same error happens with '' and '/'
    [
        'before'      => function (CommandInterface $command) {
            print_r($command->getName().PHP_EOL);
            print_r($command->toArray());
        }
    ]
);
```

gives: 

```
PutObject
Array
(
    [Bucket] => bucket
    [SourceFile] => /tmp/test-dir/some-file
    [Key] =>
    [@http] => Array
        (
        )
)
```

There's some quite confusing handling of leading/trailing `/` characters within the Transfer class, including [normalizePath](https://github.com/aws/aws-sdk-php/blob/master/src/S3/Transfer.php#L207) which is documented as `Normalize a path so that it has a trailing slash` but in fact does the opposite.

It looks like currently:
* the s3 bucket **must** have a trailing `/` otherwise [getS3Args](https://github.com/aws/aws-sdk-php/blob/master/src/S3/Transfer.php#L177) will not parse any base `Key` and so [createS3Key](https://github.com/aws/aws-sdk-php/blob/master/src/S3/Transfer.php#L318) will return an empty string for any filename. This is only the case now if there is a non-empty key prefix.
* local directory paths **must not** have a trailing `/` otherwise both source file name and s3 key end up with a `//` like `/tmp/test-dir//some-file` and `bucket//some-file` - this results in the upload being successful but the files are all uploaded one-level down to an un-named directory.

**Comment by ethet** [comment] 2015-07-10 13:43
@acoulton While this problem has become increasingly frustrating for me, I am pleased to learn that someone else is experiencing difficulty with the Transfer Manager so I feel less crazy about it.

I deleted the account which was used to create the initial issue report, so I cannot reopen it. I feel silly for having closed it, though I felt embarrassed.

@jeremeamia Would you be able to reopen this?

**Closed** 2015-07-22 22:55 UTC

**Comment by jeskew** [comment] 2015-07-22 23:04
@acoulton's fix has been merged into master. Thanks for reporting this, @ethet!
