### ISSUE TITLE
Media Live listChannels not returning results

### ISSUE THREAD

**Issue by samueleastdev** [aws/aws-sdk-php#1547] opened 2018-05-14 11:23 UTC
Hi All,

I have 3 channels in AWS and when running the command below it returns 0.

~~~
try {

	$MediaLiveClient = new MediaLiveClient([
		    'version'     => 'latest',
		    'region'      => 'us-east-1'
	]);
	 
	$ListChannels = $MediaLiveClient->listChannels([])->toArray();

	echo count($ListChannels['Channels']);

} catch (Exception $e) {
	    
      echo 'failed';

}
~~~

Please advise thanks

**Comment by kstich** [comment] 2018-05-14 14:43
Closing as a duplicate of #1533 - See [this comment](https://github.com/aws/aws-sdk-php/issues/1533#issuecomment-384112236) about using a Paginator to get list all of your channels.

**Closed by kstich** 2018-05-14 14:43 UTC
Labels: API-Issue, usage-question

**Comment by samueleastdev** [comment] 2018-05-14 14:56
Hi @kstich 

Yes, we managed to get it working with Paginator call.

But surely this shouldn’t be closed because the listChannels call itself doesn’t work as expected? 

And they way we have to do this is very messy?

```
$MediaLiveClient = new MediaLiveClient(['version' => 'latest', 'region' => 'us-east-1']);
$ListChannels = $MediaLiveClient->getPaginator('ListChannels');
$ChanelsArray = [];

foreach($ListChannels as $Result)
	{
	if (count($Result->get('Channels')) > 0)
		{
		foreach($Result->get('Channels') as $key => $value)
			{
			array_push($ChanelsArray, $value);
			}
		}
	}

echo count($ChanelsArray);
```
It returns empty arrays thats why we have to check for a count and the call is slower beacuse of the multiple iterations.

Please consider reopening and applying a fix.

Thanks
