### ISSUE TITLE
Uncaught exception 'GuzzleHttp\Exception\ClientException'

### ISSUE THREAD

**Issue by tatoshko** [aws/aws-sdk-php#1085] opened 2016-09-15 08:32 UTC
My code
```
$credentials = new \Aws\Credentials\Credentials('<key>', '<secret>');
$client = new \Aws\S3\S3Client([
    'version'     => 'latest',
    'region'      => 'eu-central-1',
    'credentials' => $credentials,
]);

$data = [
    'Bucket' => 'my-bucket',
    'Key'    => 'not/exists/dir/test.png',
];

try {
    $result = $client->getObject($data); // break here

    var_dump($result); die;
} catch (Exception $e) {
    var_dump($e); die;
}
```

Error from php log:
> FastCGI sent in stderr: "PHP message: PHP Warning:  Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `GET https://s3.eu-central-1.amazonaws.com/my-bucket/not/exists/dir/test.png` resulted in a `404 Not Found` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message> (truncated...)
' in /www/ma/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:107

I'am using composer for installing the SDK(also tried dev-master version).

**Comment by cjyclaire** [comment] 2016-09-15 17:17
@tatoshko Could you double check the `Key` parameter? The Error message shows that there is no such key in the bucket.

**Comment by tatoshko** [comment] 2016-09-15 23:38
@cjyclaire I deliberately used a non-existent key. If i use doesObjectExists i have same error.

**Comment by cjyclaire** [comment] 2016-09-15 23:54
@tatoshko I'm a bit confuse, could you explain a bit what is the problem? Are you suggesting that you couldn't catch the exception?

For a non-existent key, the error should be thrown and caught, and `doesObjectExists` should return `false`. Here is my code snippet that matches the behavior described:

```php
try {
   var_dump($client->doesObjectExist('bucket', 'invalid_key.txt'));
   $res = $client->getObject([
       'Bucket' => 'bucket',
       'Key' => 'invalid_key.txt',
  ]);
  var_dump($result);
} catch (\Exception $e) {
  echo $e->getMessage();
}
```
It outputs:
``` php
bool(false)
Error executing "GetObject" on "https://s3-us-west-2.amazonaws.com/s3-bucket-sandbox-test/99401.txt"; AWS HTTP error: Client error: `GET https://s3-us-west-2.amazonaws.com/bucket/invalid_key.txt` resulted in a `404 Not Found` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message> (truncated...)
 NoSuchKey (client): The specified key does not exist. - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>invalid_key.txt</Key><RequestId>65D71CE9721E29ED</RequestId><HostId>+DxYl1X7khosUwlH5oJmYeUrdiN6DjUmpvsh3bRdh30n8SNeSQugVGylL6fDrCYzBha2OcAknKo=</HostId></Error>
```
In addition, when a valid key is used, there is no error.

**Comment by tatoshko** [comment] 2016-09-16 00:07
@cjyclaire 
> should return false

But not.

> should catch

But not catch.(See issue subject `Uncaught exception 'GuzzleHttp\Exception\ClientException'`)

Your example for me calling fatal error, the script stops execution. In php error log i have this:
```
PHP message: PHP  17. GuzzleHttp\Middleware::GuzzleHttp\{closure}($response = class GuzzleHttp\Psr7\Response { private $reasonPhrase = 'Not Found'; private $
2016/09/16 10:01:01 [error] 82552#0: *2677 FastCGI sent in stderr: "PHP message: PHP Warning:  Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `HEAD https://s3.eu-central-1.amazonaws.com/wbncdn/not/exists/dir/test.png` resulted in a `404 Not Found` response:

' in /www/tato/public_html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:107
Stack trace:
#0 /www/tato/public_html/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /www/tato/public_html/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /www/tato/public_html/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /www/tato/public_html/vendor/guzzlehttp/promises/src/TaskQueue.php(61): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /www/tato/public_html/vendor/guzzlehttp/guzzle/src/H...
PHP message: PHP Stack trace:
PHP message: PHP   1. {main}() /www/tato/public_html/index.php:0
PHP message: PHP   2. Aws\S3\S3Client->doesObjectExist($bucket = 'wbncdn', $key = 'not/exists/dir/test.png', $options = *uninitialized*) /www/tato/public_html/index.php:39
PHP message: PHP   3. Aws\S3\S3Client->checkExistenceWithCommand($command = class Aws\Command { private $name = 'HeadObject'; private $handlerList = class Aws\HandlerList { private $handler = class Aws\WrappedHttpHandler { private $httpHandler = class Aws\Handler\GuzzleV6\GuzzleHandler { private $client = class GuzzleHttp\Client { private $config = array ('handler' => class GuzzleHttp\HandlerStack { private $handler = class Closure { public $static = array ('default' => class Closure { public $static = array ('default' => class GuzzleHttp\Handler\CurlMultiHandler { private $factory = class GuzzleHttp\Handler\CurlFactory { private $handles = array (0 => resource(104) of type (curl
2016/09/16 10:01:01 [error] 82552#0: *2677 FastCGI sent in stderr: "fPending() /www/tato/public_html/vendor/guzzlehttp/promises/src/Promise.php:266
PHP message: PHP  11. GuzzleHttp\Promise\Promise->invokeWaitFn() /www/tato/public_html/vendor/guzzlehttp/promises/src/Promise.php:223
PHP message: PHP  12. GuzzleHttp\Handler\CurlMultiHandler->execute(TRUE) /www/tato/public_html/vendor/guzzlehttp/promises/src/Promise.php:246
PHP message: PHP  13. GuzzleHttp\Handler\CurlMultiHandler->tick() /www/tato/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php:123
PHP message: PHP  14. GuzzleHttp\Promise\TaskQueue->run() /www/tato/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php:96
PHP message: PHP  15. GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() /www/tato/public_html/vendor/guzzlehttp/promises/src/TaskQueue.php:61
PHP message: PHP  16. GuzzleHttp\Promise\Promise::callHandler($index = 1, $value = class GuzzleHttp\Psr7\Response { private $reasonPhrase = 'Not Found'; private $statusCode = 404; private $headers = array ('x-amz-request-id' => array (0 => '5DE510A7903B66D7'), 'x-amz-id-2' => array (0 => 'eHdVcXQwGRSTDQhKoDKgDCA4SxDFrFGU20M7QuZczWVfpgsMYrhpTKKJvX45erAshfD/oMKIvig='), 'Content-Type' => array (0 => 'application/xml'), 'Transfer-Encoding' => array (0 => 'chunked'), 'Date' => array (0 => 'Fri, 16 Sep 2016 00:00:55 GMT'), 'Server' => array (0 => 'AmazonS3')); private $headerNames = array ('x-amz-request-id' => 'x-amz-request-id', 'x-amz-id-2' => 'x-amz-id-2', 'content-type' => 'Content-Type', 'transfer-encoding' => 'Transfer-Encoding', 'date' => 'Date', 'server' => 'Server'); private $protocol = '1.1'; private $stream = class GuzzleHttp\Psr7\Stream { private $stream = resource(102) of type (stream); private $size = 0; private $seekable = TRUE; private $readable = TRUE; private $writable = TRUE; private $uri = ...
PHP message: PHP  17. GuzzleHttp\Middleware::GuzzleHttp\{closure}($response = class GuzzleHttp\Psr7\Response { private $reasonPhrase = 'Not Found'; private $
```

**Comment by cjyclaire** [comment] 2016-09-16 00:13
@tatoshko Interesting, I just tried the latest version and still couldn't reproduce the issue.
Does a valid key seeing this issue as well? Could you provide the OS information, php version, guzzle version then I could try to reproduce?

**Comment by tatoshko** [comment] 2016-09-16 00:25
OSX El Capitan 10.11.6
PHP 5.6.18
Guzzle 6.2.1 (from was-sdk required from aws-sdk)

workaround step-by-step:
```
1. mkdir test && cd test
2. composer init
3. composer require aws/aws-sdk-php
4. touch index.php
```

composer.json
```
{
    "name": "test/public_html",
    "authors": [
        {
            "name": "test",
            "email": "t@t.t"
        }
    ],
    "require": {
        "aws/aws-sdk-php": "dev-master"
    }
}
```

In index.php:
```
<?php
require_once __DIR__ . "/vendor/autoload.php";

$credentials = new \Aws\Credentials\Credentials('<key>', '<secret>');

$client = new \Aws\S3\S3Client([
    'version'     => 'latest',
    'region'      => 'eu-central-1',
    'credentials' => $credentials,
]);

try {
    $result = $client->doesObjectExist(
        'my-bucket',
        'not/exists/dir/test.png'
    );

    var_dump($result);
} catch (Exception $e) {
    var_dump($e);
}

echo 'OK';
```

**Comment by tatoshko** [comment] 2016-09-16 03:49
@cjyclaire PHP 7.0.10 installation solved the problem. But what to do with 5.6? i'am should use 5.6 version for some projects.

**Comment by cjyclaire** [comment] 2016-09-16 17:54
@tatoshko I just tried php5.6 and still couldn't reproduce the issue. Could you verify php 5.6 is installed properly and environment by running `compatibility-test` with [guide](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/getting-started/requirements.html#compatibility-test) to see whether they are all properly installed?

Also, instead of `var_dump` entire `Exception`, I'd suggest using `getMessage()` for cleaner message. Furthermore, `getObject` is a API call and SDK doesn't build customization on it.

**Comment by tatoshko** [comment] 2016-09-16 22:39
@cjyclaire it's xdebug problem. Try to enable.
> ...extension will greatly slow down the SDK

Change to "It breaks your app"

Amazing... if i want use SDK i can not use xdebug.

**Comment by cjyclaire** [comment] 2016-09-16 23:57
@tatoshko I tried to enable xdebug, it still doesn't reproduce the issue. Though, if i try to `var_dump` the exception with xdebug turned on, it produce the the same error response structure as you described except that the exception is caught.

**Comment by tatoshko** [comment] 2016-09-17 01:32
@cjyclaire ok. I'am identified the problem.
xdebug.collect_params = 4

All works only if collect_params = 1 or disabled.

**Comment by tatoshko** [comment] 2016-09-17 01:35
@cjyclaire thx, think you may close that issue, likely it's not possible to solve.

**Comment by tatoshko** [comment] 2016-09-17 02:51
finally, i set max_execution_time greater value(3600) and a page was loaded. Weight of the page ~440mb. 440mb stack trace.

**Comment by cjyclaire** [comment] 2016-09-19 16:52
Closing, thanks for all your efforts in those information.

**Closed by cjyclaire** 2016-09-19 16:52 UTC
Labels: awaiting-reply

**Comment by jtpenny** [comment] 2016-10-12 21:59
I am seeing the same problem. 

try {
		$s3Client = $qsrDB->s3connection();
		$result = $s3Client->getIterator('ListObjects',[
			'Bucket'=>$bucket,
			'Prefix'=> $prefix
		]);
	
	} catch(\Exception $e) {
		echo 'There was a problem.';
	}

The code works fine, but when I put in a bad bucket to force the exception, it is not caught. 

Fatal error: Uncaught exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "ListObjects" on "---"; AWS HTTP error: Client error: `GET ---` resulted in a `404 Not Found` response: <?xml version="1.0" encoding="UTF-8"?> <Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Mes (truncated...) NoSuchBucket (client): The specified bucket does not exist - <?xml version="1.0" encoding="UTF-8"?> <Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName><bucket></BucketName><RequestId>D1EDC36CA6DCD448</RequestId><HostId></HostId></Error>' exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `GET --- in phar:///aws.phar/Aws/WrappedHttpHandler.php on line 192

PHP 5.6 using the AWS Phar. Xdebug is not enabled. Any new ideas on this?

**Comment by tatoshko** [comment] 2016-10-12 22:13
@jtpenny, you need to read this first [AWS error handling](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/getting-started/basic-usage.html#synchronous-error-handling)

**Comment by jtpenny** [comment] 2016-10-12 22:43
@tatoshko I tried Aws\S3\Exception\S3Exception but it didn't work. However, getIterator returns a promise, and the asynchronous section helped. Thank you for the help.

**Comment by tatoshko** [comment] 2016-10-13 00:07
@jtpenny, enjoy (=

**Comment by s3bubble** [comment] 2017-04-03 16:54
I am also getting this exact error and I cannot find a fix. 

https://github.com/aws/aws-sdk-php/issues/1237

I have tried everything suggested in this post I am running php 7.0.12
