### ISSUE TITLE
Serverless deploy with laravel broken after 3.245.0

### ISSUE THREAD

**Issue by luan-tavares** [aws/aws-sdk-php#2576] opened 2022-11-21 19:47 UTC
### Describe the bug

When you deploy in serverless lambda and use:

 's3' => [
            'driver' => 's3',
            'root' => '/',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'token' => env('AWS_SESSION_TOKEN'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
            'endpoint' => env('AWS_ENDPOINT'),
            'use_path_style_endpoint' => env('AWS_USE_PATH_STYLE_ENDPOINT', false),
        ],
        
   in v3.244.x works, but after v3.245.x trhow a Aws Exception where dont recognized the 'token'  

### Expected Behavior

It must to connect with the Aws Client in laravel lambda.

### Current Behavior

throw urecognized 'token' error

### Reproduction Steps

works in v3.244.x and before

### SDK version used

v3.246.1

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

8.1.x

**Comment by staudenmeir** [comment] 2022-11-21 20:44
This will be fixed in the next Laravel release:
https://github.com/aws/aws-sdk-php/issues/2567
https://github.com/laravel/framework/pull/44979

**Comment by stobrien89** [comment] 2022-11-21 21:45
Thanks @staudenmeir,

@luan-tavares closing this since it's a duplicate of #2567.

**Closed by stobrien89** 2022-11-21 21:45 UTC
Labels: bug, duplicate
