### ISSUE TITLE
Unable to create virtual-hosted style URLs for S3.

### ISSUE THREAD

**Issue by jpinner-lyft** [aws/aws-sdk-php#692] opened 2015-07-15 18:46 UTC
In v2 of the SDK, the S3Client used the "BucketStyleListener" to automatically transform S3 path-style URLs to virtual-hosted style URLs when possible.

```php
// Switch to virtual hosted bucket
$request->setHost($bucket . '.' . $request->getHost());
$request->setPath(preg_replace("#^/{$bucket}#", '', $request->getPath()));
```

 In v3 of the SDK, this has been removed. Based on the configuration, it is possible to add the "BucketEndpointMiddleware" to the stack; however, this has the affect of modifying the request path to remove the bucket segment but it does not modify the host.

```php
$path = $this->removeBucketFromPath($path, $bucket);
```

Is this a bug in "BucketEndpointMiddleware"? Is there an alternate way to force the SDK to use virtual-hosted style URLs whenever possible?

**Comment by dstevenson** [comment] 2015-07-15 19:48
I think you're looking for the `S3Client` configuration parameter `bucket_endpoint: true`

**Comment by jpinner-lyft** [comment] 2015-07-15 19:54
@dstevenson when setting ```bucket_endpoint: true``` the "BucketEndpointMiddleware" is added to the stack but that does not modify the host header to prepend the bucket name.

**Comment by jeremeamia** [comment] 2015-07-15 19:58
Why do you need to do this?

**Comment by dstevenson** [comment] 2015-07-15 19:59
I see, so you still end up with `host: s3.amazonaws.com` instead of `host: bucket.s3.amazonaws.com`. Not sure if that's a bug or not, but I think you can manually pass in to the `S3Client` `endpoint: https://bucket.s3.amazonaws.com/` and get the behavior you expect

**Comment by jeskew** [comment] 2015-07-15 20:09
I think @dstevenson's suggestion is the way to go: you can instantiate an S3Client to achieve the behavior you want like so:
```php
$s3 = new \Aws\S3\S3Client([
    'version' => <version>,
    'region' => <region>,
    'endpoint' => '<bucketName>.s3.amazonaws.com',
    'bucket_endpoint' => true,
]);
```
This pattern also supports [CNAME'd bucket endpoints](http://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html#VirtualHostingCustomURLs).

**Comment by jpinner-lyft** [comment] 2015-07-15 20:13
@jeremeamia I discovered this while running tests against the pre-signed URLs generated by v3 of the library for "PutObject" calls. The previous version would create virtual-hosted style URLs while v3 generates the path-style URLs instead. In general, the system I'm integrating into expects the virtual-hosted style URLs to proxy calls to S3.

@jeskew That requires one client to be instantiated per bucket-name and fails when generating commands that do not contain a 'Bucket' parameter or when the command is in the exclusion list (e.g. GetBucketLocation).

**Comment by jpinner-lyft** [comment] 2015-07-15 20:18
If the intent of "BucketEndpointMiddleware" is to convert from path-style URLs to virtual-hosted style URLs, and for the conversion to happen via configuration in v3 instead of automatically as before, I'm happy to create a pull request.

**Comment by mtdowling** [comment] 2015-07-15 20:23
The intent of the "bucket_endpoint" option and BucketEndpointMiddleware is to allow you to create a client that is bound to a specific bucket endpoint. The only intended usecase for this option and middleware is to create presigned URLs for a CNAME bucket. You need to create a client per bucket endpoint. You do not need to use CNAME urls for normal API requests.

> If the intent of "BucketEndpointMiddleware" is to convert from path-style URLs to virtual-hosted style URLs, and for the conversion to happen via configuration in v3 instead of automatically as before, I'm happy to create a pull request.

No that is not the intent. Because we require a region and use sig-v4, we do not use virtual hosted buckets in v3. The reason we used them in v2 was to allow redirects to work when using the old "s3" signer.

**Comment by jpinner-lyft** [comment] 2015-07-15 20:32
@mtdowling thanks for clarifying the intent of the "bucket_endpoint" option.

Could you clarify how the region and sig-v4 are related to signature algorithm? Since the request is canonicalized before signing and includes both the path and host header, how does this switch to v4 affect the URL style? As I understand it, the signature processing and request routing should be independent.

**Comment by dstevenson** [comment] 2015-07-15 23:19
@jpinner-lyft Maybe you can use your own custom [Middleware](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/handlers-and-middleware.html) as a workaround for the functionality you're looking for?

**Comment by jpinner-lyft** [comment] 2015-07-15 23:30
@dstevenson I can write middleware the replicates the "BucketStyleListener" functionality from v2 -- also am happy to create a pull request that does so.

It sounds like the move away from virtual-hosted style URLs was intentional, however it seems at odds with [documentation] (http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAPI.html) for the REST API.

@mtdowling Please correct me if I'm wrong but I believe it is possible to re-introduce the automatic transform without affecting the ability to sign the requests.

**Comment by dstevenson** [comment] 2015-07-16 19:02
I think @jpinner-lyft is on to something here.

Suppose you create some client:

```
$client = new S3Client([
    "credentials" => [
        "key"    => ...,
        "secret" => ...,
    ],
    "region"   => ...,
    "version"  => ...,
    "bucket_endpoint" => true
]);
```

Using this client to generate a presignedRequest for a `GetObject` appears to yield the incorrect result:

```
$cmd = $client->getCommand('GetObject', [
  'Bucket' => 'bucket',
  'Key'    => 'key'
]);

$request = $client->createPresignedRequest($cmd, "+30 minutes");

// yields https://s3.amazonaws.com/837a32bdc0ab347012f7c7271f3a0f5a9c660e964e684f63ce4ad4c6e0aeff94?{signature stuff here...}
(string) $request->getUri();

// Host is s3.amazonaws.com
$request->getHeader("host")
```

When it should be giving us something like

```
// https://bucket.s3.amazonaws.com/837a32bdc0ab347012f7c7271f3a0f5a9c660e964e684f63ce4ad4c6e0aeff94?{signature stuff here...}
(string) $request->getUri();

// Host is bucket.s3.amazonaws.com
$request->getHeader("host")
```

**Comment by jeskew** [comment] 2015-07-16 19:52
@dstevenson `endpoint` is a conditionally required parameter there: if you pass in `'bucket_endpoint' => true` when creating an S3 client, you need to also pass in an endpoint.

The use case we're supporting with this is CNAME'd bucket endpoints, not virtual hosted bucket endpoints. We do not explicitly support virtual hosted bucket endpoints, though you can use them if you pass the virtual hosted bucket URL in as if it were a vanity endpoint *and* your bucket name meets the requirements specified by S3. It's not something that would work with every bucket.

Using virtual hosted bucket URLs can affect application performance in two ways: 1) you need to do a DNS lookup on every single bucket, and 2) requests are routed by default to us-east-1. Since the SDK requires that you specify a region anyway, as SigV4 signing keys include the region name, you're better off speaking directly to the appropriate S3 region instead of bouncing off us-east-1. This is exactly the kind of low-level detail the SDK is supposed to abstract away.

**Comment by jeskew** [comment] 2015-07-20 21:06
Closing as working as intended. Please feel free to reopen if you have any further questions.

**Closed by jeskew** 2015-07-20 21:06 UTC

**Comment by jpinner-lyft** [comment] 2015-07-20 21:09
@jeskew Thank you for the detailed explanation.
