### ISSUE TITLE
Issue with using adminInitiateAuth

### ISSUE THREAD

**Issue by awsdev543** [aws/aws-sdk-php#1057] opened 2016-07-30 13:30 UTC
Getting the error {"__type":"InvalidParameterException","message":"Missing required parameter UserName"}

$client->adminInitiateAuth([
    'AuthFlow' => 'ADMIN_NO_SRP_AUTH', // REQUIRED
    'AuthParameters' => ['UserName'=>'xxx', 'Password'=> 'xxx'],
    'ClientId' => 'xxx', // REQUIRED
     'UserPoolId' => 'xxx', // REQUIRED
]);

**Comment by cjyclaire** [comment] 2016-08-01 19:49
@awsdev543 Thanks for reporting, I could reproduce the issue in both PHP and Ruby SDK.
Since this is a newly released API and SDK doesn't customize it, I'm reaching out to service team for feedback and solution.

**Comment by cjyclaire** [comment] 2016-08-01 20:08
It looks like others are struggling with same issue [here](https://forums.aws.amazon.com/thread.jspa?threadID=236451&tstart=0).

**Comment by cjyclaire** [comment] 2016-08-01 21:06
@awsdev543  Service is working on fixing the inconsistency between docs and API, current workaround is to pass all keys in UPPERCASE in auth parameters:
```
...
'AuthParameters' => [
            'USERNAME' => 'xxx',
            'PASSWORD' => 'xxx',
        ],
...
```

**Comment by awsdev543** [comment] 2016-08-03 03:27
Thanks. Works with all uppercase auth parameters.

**Comment by cjyclaire** [comment] 2016-08-03 15:53
Closing, I'll pin the thread when doc fix is out, yet please feel free to reopen if you have further questions.

**Closed by cjyclaire** 2016-08-03 15:53 UTC
Labels: API-Issue, docs
