### ISSUE TITLE
Every .phar 2.6.16 and above fails to load on the second request

### ISSUE THREAD

**Issue by NobleUplift** [aws/aws-sdk-php#563] opened 2015-04-30 21:37 UTC
My coworker and I downloaded 2.8.2, then 2.7.0, and 2.6.16. None of the phars for these versions worked, and spat out this error:

```[Thu Apr 30 15:50:21.909040 2015] [:error] [pid 2621] [client ] PHP Warning:  require(phar://aws.phar/aws-autoloader.php): failed to open stream: phar error: invalid url or non-existent phar &quot;phar://aws.phar/aws-autoloader.php&quot; in /usr/local/lib/php/aws.phar on line 3, referer: https://
[Thu Apr 30 15:50:21.909127 2015] [:error] [pid 2621] [client ] PHP Fatal error:  require(): Failed opening required 'phar://aws.phar/aws-autoloader.php' (include_path='.:/usr/share/php:/usr/share/pear:/usr/local/lib/php:/usr/local/lib/php/db:/var/www') in /usr/local/lib/php/aws.phar on line 3, referer: https://```

We then went up from 2.6 to 2.6.9, 2.6.12, 2.16.14, and 2.6.15, at that point realizing that 2.6.15 is the most up-to-date version of the .phar we can use. We are considering the use of Composer in the future (which we are actually already using), but wanted to report our issues with these phar versions.

**Comment by jeremeamia** [comment] 2015-04-30 22:24
We have not experienced this issue with the `aws.phar`, and we run our test suite with the phar regularly. Could you provide a code sample the reproduces the issue?

**Comment by NobleUplift** [comment] 2015-04-30 22:41
I'll try to isolate the important bits because the codebase is fairly large. It's a basic S3 get:

```
			$s3 = AwsS3::getInstance();
			$contents = $s3->retrieveFileContents('json_ads/' . $zoneBannerData['token'] . '.json', 'cdn');
			echo $contents;
```

AwsS3 works as follows:

```
namespace common\aws;

class AwsS3 {
	private $client;
	
	private static $instance;
	
	public static function getInstance() {
		if (!isset(self::$instance)) {
			self::$instance = new AwsS3();
		}
		return self::$instance;
	}
	
	private function __construct() {
		AwsBootstrapper::initialize();
		$this->client = S3Client::factory(AwsConfig::getAwsCredentials());
	}
	
	...
}
```

The bootstrapper is what loads the phar, and it's just an empty class:

```
namespace common\aws;

require_once('aws.phar');

/**
 * Documentation for AWS PHP classes can be found at:
 * 		http://docs.aws.amazon.com/aws-sdk-php-2/latest/index.html
 *
 */
class AwsBootstrapper {
	public static function initialize() {
		/*
		 * The PHP 'use' keyword does not call the autoloader.
		 * Rather, the autoloader is only called when the class is found in the code.
		 * 
		 * Therefore, an empty 'initialize' method must be called so that other
		 * classes receive aws.phar.
		 */
	}
}
```

This is only one of our servers where we have this issue, and it is only initializing S3. On our web server, we initialize S3, SQS, and SES without these errors.

**Comment by mtdowling** [comment] 2015-05-01 17:20
I just spun up an EC2 instance, and tried to reproduce this issue with Apache using the simplest possible test case.

I ran the following commands and ensured that I installed the OPcache.

```
yum install php56 php56-opcache -y
cd /var/www/html
wget https://github.com/aws/aws-sdk-php/releases/download/2.8.2/aws.phar
service httpd start
```

Place the following in test.php:

```php
<?php
require __DIR__ . '/aws.phar';

$client = Aws\S3\S3Client::factory([
    'region'  => 'us-east-1',
    'version' => 'latest'
]);

echo $client->listBuckets();
```

Now hit the endpoint with cURL:

```
curl http://127.0.0.1/test.php
```

I ran this several times and did not reproduce this issue.

It is interesting that we switched to a different build tool to generate our phars starting around version 2.6.16, which is when you see this problem start to occur. However, I'm not able to reproduce this issue and we haven't seen any other complaints about this in the last 7+ months. This makes me think that there might be some weird autoloading issue going on that is either an edge case that we did not cover or an application specific error.

**Comment by NobleUplift** [comment] 2015-05-01 17:22
My coworker is the one who did the testing, so I may have missed something trying to read the code myself. I've also made a change in our loading practice for AWS (as I mentioned above) which I want to test on Monday, so I'll update you after that.

**Comment by NobleUplift** [comment] 2015-05-04 16:00
This is the version of PHP we're using:

```PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies```

I have not yet had a chance to re-run that test.

**Comment by mtdowling** [comment] 2015-05-05 18:17
The phar is not signed, so maybe your IDE just needs to be restarted?

**Comment by NobleUplift** [comment] 2015-05-12 17:10
My coworker and I were able to test the 2.7.27 aws.phar and it might have worked. I believe the cause is one or both of the following:

1. The require_once('aws.phar'); was inside of a namespace.
2. Our Autoloader was causing a conflict on the second load of AWS:

 ```
function autoloader($class) {
	$class = ltrim($class, '\\');
	$ns1 = substr($class, 0, 7);
	if ($ns1 === false) {
		return;
	} else if ($ns1 != 'ournamespace') {
		return;
	}

	$filename  = '';
	$namespace = '';

	if ($last_ns_pos = strripos($class, '\\')) {
		$namespace = strtolower(substr($class, 0, $last_ns_pos));
		$class = substr($class, $last_ns_pos + 1);
		$filename  = str_replace('\\', DIRECTORY_SEPARATOR, $namespace) . DIRECTORY_SEPARATOR;
	}

	$filename .= str_replace('_', DIRECTORY_SEPARATOR, $class) . '.php';

	if (stream_resolve_include_path($filename)) {
		require_once $filename;
	} else {
		throw new \Exception('Class at location ' . $filename . ' not found.');
	}
}

spl_autoload_register('autoloader');
```

We aren't exactly certain which version of AWS we just tested on. At a later date, we will try with the most up-to-date 2.8 branch and see if it works.

**Comment by mtdowling** [comment] 2015-05-18 21:21
@NobleUplift are you thinking that this might be an application specific error? Any further information we can act on?

**Comment by r-baker** [comment] 2015-05-26 14:37
I have had the same issue with exact same error. From my limited testing it appears to be caused by Zend Opcache. Disabling the opcache (not recommended) or adding the aws.phar path to the list of ignored files fixes this.

**Comment by NobleUplift** [comment] 2015-05-26 14:53
Thanks r-baker! If possible, could you link me or write instructions for how to do both of these? Then I can forward them to my coworker and we'll try a higher version.

**Comment by r-baker** [comment] 2015-05-26 14:59
I'm not 100% sure excluding aws.phar from the cache is the "right" thing to do. That said the AWS docs offer this as a solution for phar/APC issues: http://docs.aws.amazon.com/aws-sdk-php/v2/guide/faq.html

Create a blacklist file e.g. `/etc/php5/opcache-blacklist.txt`
```
# php.ini
opcache.blacklist_filename=/etc/php5/opcache-blacklist.txt
```
```
# opcache-blacklist.txt

**Comment by mtdowling** [comment] 2015-05-26 15:59
Are you able to use *any* phar with the opcache, or is it just the AWS phar that doesn't work? Which distro are you using? Is the suhosin patch enabled?

**Comment by r-baker** [comment] 2015-05-28 10:22
Seems to be just the AWS phar.

Running Ubuntu 14.04. Standard distro. PHP 5.6.9-1+deb.sury.org~trusty+2

**Comment by mtdowling** [comment] 2015-05-29 19:53
I'm not able to reproduce this error. Let me show you what I did and see if you can tell me if I'm missing something, and if not, perhaps show me how I can reproduce the issue exactly as you have.

1. I launched ubuntu-trusty-14.04-amd64-server-20150325 (ami-5189a661) (this is the Ubuntu image listed in the console).
2. I ran `apt-get update && apt-get install php5`, giving me the following PHP installation:

  ```
ubuntu@ip-172-30-0-236:~$ php -v
PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
  ```
3. I downloaded the latest phar into `/var/www/html`: `wget https://github.com/aws/aws-sdk-php/releases/download/2.8.8/aws.phar`
4. I created the following test script in `test.php`:

  ```php
<?php
require 'aws.phar';
$c = \Aws\Common\Aws::factory();
echo 'OK!';
  ```

5. I contacted the local Apache server using cURL: `curl http://127.0.0.1/test.php` (give "OK!"). I tried this multiple times and each time worked correctly.
6. I created the following script in `info.php` to ensure that the OPCache is working:

  ```php
<?php
var_dump(opcache_get_status());
  ```

7. I accessed `info.php` using curl and got the following:

  ```
      array(8) {
        ["opcache_enabled"]=>
        bool(true)
        ["cache_full"]=>
        bool(false)
        ["restart_pending"]=>
        bool(false)
        ["restart_in_progress"]=>
        bool(false)
        ["memory_usage"]=>
        array(4) {
          ["used_memory"]=>
          int(5745440)
          ["free_memory"]=>
          int(61363424)
          ["wasted_memory"]=>
          int(0)
          ["current_wasted_percentage"]=>
          float(0)
        }
        ["interned_strings_usage"]=>
        array(4) {
          ["buffer_size"]=>
          int(4194304)
          ["used_memory"]=>
          int(885056)
          ["free_memory"]=>
          int(3309248)
          ["number_of_strings"]=>
          int(8361)
        }
        ["opcache_statistics"]=>
        array(13) {
          ["num_cached_scripts"]=>
          int(13)
          ["num_cached_keys"]=>
          int(15)
          ["max_cached_keys"]=>
          int(3907)
          ["hits"]=>
          int(25)
          ["start_time"]=>
          int(1432928309)
          ["last_restart_time"]=>
          int(0)
          ["oom_restarts"]=>
          int(0)
          ["hash_restarts"]=>
          int(0)
          ["manual_restarts"]=>
          int(0)
          ["misses"]=>
          int(13)
          ["blacklist_misses"]=>
          int(0)
          ["blacklist_miss_ratio"]=>
          float(0)
          ["opcache_hit_rate"]=>
          float(65.789473684211)
        }
        ["scripts"]=>
        array(13) {
          ["phar:///var/www/html/aws.phar/Guzzle/Service/AbstractConfigLoader.php"]=>
          array(6) {
            ["full_path"]=>
            string(69) "phar:///var/www/html/aws.phar/Guzzle/Service/AbstractConfigLoader.php"
            ["hits"]=>
            int(2)
            ["memory_consumption"]=>
            int(22848)
            ["last_used"]=>
            string(24) "Fri May 29 19:38:34 2015"
            ["last_used_timestamp"]=>
            int(1432928314)
            ["timestamp"]=>
            int(1432859894)
          }
          ["phar:///var/www/html/aws.phar/Aws/Common/Resources/aws-config.php"]=>
          array(6) {
            ["full_path"]=>
            string(65) "phar:///var/www/html/aws.phar/Aws/Common/Resources/aws-config.php"
            ["hits"]=>
            int(2)
            ["memory_consumption"]=>
            int(17384)
            ["last_used"]=>
            string(24) "Fri May 29 19:38:34 2015"
            ["last_used_timestamp"]=>
            int(1432928314)
            ["timestamp"]=>
            int(1432859894)
          }
          ["phar:///var/www/html/aws.phar/Guzzle/Common/AbstractHasDispatcher.php"]=>
          array(6) {
            ["full_path"]=>
            string(69) "phar:///var/www/html/aws.phar/Guzzle/Common/AbstractHasDispatcher.php"
            ["hits"]=>
            int(2)
            ["memory_consumption"]=>
            int(6520)
            ["last_used"]=>
            string(24) "Fri May 29 19:38:34 2015"
            ["last_used_timestamp"]=>
            int(1432928314)
            ["timestamp"]=>
            int(1432859894)
          }
          ["phar:///var/www/html/aws.phar/aws-autoloader.php"]=>
          array(6) {
            ["full_path"]=>
            string(48) "phar:///var/www/html/aws.phar/aws-autoloader.php"
            ["hits"]=>
            int(2)
            ["memory_consumption"]=>
            int(173944)
            ["last_used"]=>
            string(24) "Fri May 29 19:38:34 2015"
            ["last_used_timestamp"]=>
            int(1432928314)
            ["timestamp"]=>
            int(1432859894)
          }
          ["phar:///var/www/html/aws.phar/Guzzle/Service/Builder/ServiceBuilderLoader.php"]=>
          array(6) {
            ["full_path"]=>
            string(77) "phar:///var/www/html/aws.phar/Guzzle/Service/Builder/ServiceBuilderLoader.php"
            ["hits"]=>
            int(2)
            ["memory_consumption"]=>
            int(10584)
            ["last_used"]=>
            string(24) "Fri May 29 19:38:34 2015"
            ["last_used_timestamp"]=>
            int(1432928314)
            ["timestamp"]=>
            int(1432859894)
          }
          ["phar:///var/www/html/aws.phar/Guzzle/Service/ConfigLoaderInterface.php"]=>
          array(6) {
            ["full_path"]=>
            string(70) "phar:///var/www/html/aws.phar/Guzzle/Service/ConfigLoaderInterface.php"
            ["hits"]=>
            int(2)
            ["memory_consumption"]=>
            int(2936)
            ["last_used"]=>
            string(24) "Fri May 29 19:38:34 2015"
            ["last_used_timestamp"]=>
            int(1432928314)
            ["timestamp"]=>
            int(1432859894)
          }
          ["phar:///var/www/html/aws.phar/Guzzle/Common/HasDispatcherInterface.php"]=>
          array(6) {
            ["full_path"]=>
            string(70) "phar:///var/www/html/aws.phar/Guzzle/Common/HasDispatcherInterface.php"
            ["hits"]=>
            int(2)
            ["memory_consumption"]=>
            int(5328)
            ["last_used"]=>
            string(24) "Fri May 29 19:38:34 2015"
            ["last_used_timestamp"]=>
            int(1432928314)
            ["timestamp"]=>
            int(1432859894)
          }
          ["/var/www/html/aws.phar"]=>
          array(6) {
            ["full_path"]=>
            string(22) "/var/www/html/aws.phar"
            ["hits"]=>
            int(2)
            ["memory_consumption"]=>
            int(1024)
            ["last_used"]=>
            string(24) "Fri May 29 19:38:34 2015"
            ["last_used_timestamp"]=>
            int(1432928314)
            ["timestamp"]=>
            int(1432928039)
          }
          ["phar:///var/www/html/aws.phar/Guzzle/Service/Builder/ServiceBuilderInterface.php"]=>
          array(6) {
            ["full_path"]=>
            string(80) "phar:///var/www/html/aws.phar/Guzzle/Service/Builder/ServiceBuilderInterface.php"
            ["hits"]=>
            int(2)
            ["memory_consumption"]=>
            int(4776)
            ["last_used"]=>
            string(24) "Fri May 29 19:38:34 2015"
            ["last_used_timestamp"]=>
            int(1432928314)
            ["timestamp"]=>
            int(1432859894)
          }
          ["phar:///var/www/html/aws.phar/Guzzle/Service/Builder/ServiceBuilder.php"]=>
          array(6) {
            ["full_path"]=>
            string(71) "phar:///var/www/html/aws.phar/Guzzle/Service/Builder/ServiceBuilder.php"
            ["hits"]=>
            int(2)
            ["memory_consumption"]=>
            int(24280)
            ["last_used"]=>
            string(24) "Fri May 29 19:38:34 2015"
            ["last_used_timestamp"]=>
            int(1432928314)
            ["timestamp"]=>
            int(1432859894)
          }
          ["/var/www/html/info.php"]=>
          array(6) {
            ["full_path"]=>
            string(22) "/var/www/html/info.php"
            ["hits"]=>
            int(1)
            ["memory_consumption"]=>
            int(880)
            ["last_used"]=>
            string(24) "Fri May 29 19:45:21 2015"
            ["last_used_timestamp"]=>
            int(1432928721)
            ["timestamp"]=>
            int(1432928386)
          }
          ["/var/www/html/test.php"]=>
          array(6) {
            ["full_path"]=>
            string(22) "/var/www/html/test.php"
            ["hits"]=>
            int(2)
            ["memory_consumption"]=>
            int(1160)
            ["last_used"]=>
            string(24) "Fri May 29 19:38:34 2015"
            ["last_used_timestamp"]=>
            int(1432928314)
            ["timestamp"]=>
            int(1432928083)
          }
          ["phar:///var/www/html/aws.phar/Aws/Common/Aws.php"]=>
          array(6) {
            ["full_path"]=>
            string(48) "phar:///var/www/html/aws.phar/Aws/Common/Aws.php"
            ["hits"]=>
            int(2)
            ["memory_consumption"]=>
            int(8680)
            ["last_used"]=>
            string(24) "Fri May 29 19:38:34 2015"
            ["last_used_timestamp"]=>
            int(1432928314)
            ["timestamp"]=>
            int(1432859894)
          }
        }
      }
  ```

8. I then upgraded PHP to PHP 5.6 using the following instructions: http://devdocs.magento.com/guides/v1.0/install-gde/prereq/php-ubuntu.html#instgde-prereq-php56-install-ubuntu
9. I restarted apache: `service apache2 restart`.
10. I contacted `test.php` using curl multiple times and it continued to work correctly.
11. I contacted `info.php` and it outputs similar OPcache data.

This shows me that the phar we use is working correctly on Ubuntu using both PHP 5.5 and 5.6. What steps do I need to take to make this fail in a similar manner to what you are observing?

**Comment by Frozenfire92** [comment] 2015-05-30 00:24
I had a similar problem and wanted to share to help any other googlers

## the environment
Ubuntu 15.04
PHP 5.6.4-4ubuntu6 (cli) (built: Apr 17 2015 15:47:51) 
Server version: Apache/2.4.10 (Ubuntu)
Server built:   Mar  9 2015 11:53:48

## the error
```
PHP Warning:  require(phar://aws.phar/aws-autoloader.php): failed to open stream: phar error: invalid url or non-existent phar &quot;phar://aws.phar/aws-autoloader.php&quot
```

## the solution
- chmod 755 /path/to/aws.phar
- add the following to /etc/php5/apache2/php.ini `opcache.enable=0`
- restart apache `service apache2 restart`

**Comment by mtdowling** [comment] 2015-05-30 00:33
Thanks for sharing, but that's not a good solution as it disables the opcache.

Did you see my walkthrough and how I was not able to reproduce the issue? Does walking through the steps I provided cause an issue for you? What about your application is different than the steps I provided?

**Comment by mtdowling** [comment] 2015-06-26 18:38
I added an alias to the phar to see if it would help. I've linked to a built phar that has the alias. Could one of you test this phar out to see if it fixes the issue?

https://s3.amazonaws.com/s3dowling/aws.phar

**Comment by Frozenfire92** [comment] 2015-06-26 18:45
Will look into it next week

**Comment by madz7z** [comment] 2015-06-30 13:58
I have the same problem after update to latest v2.8.12

**Comment by madz7z** [comment] 2015-06-30 14:34
Fix #662 worked for me.
1. Cloned 2.8 branch 
2. Applied fix from #662 
3. Built phar

**Comment by mtdowling** [comment] 2015-06-30 16:34
That's great. I'll wait on confirmation from one more reporter on this issue before merging the change and closing this issue. @Frozenfire92 / @NobleUplift

**Comment by Frozenfire92** [comment] 2015-06-30 16:40
Looking into it now!

**Comment by Frozenfire92** [comment] 2015-06-30 16:46
Nope, same issue

`PHP Fatal error:  require_once(): Failed opening required '/var/www/site/includes/aws.phar' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/site/index.php on line 10`

The line in question looks like
`require_once dirname(__FILE__) . '/includes/aws.phar';`

**Comment by mtdowling** [comment] 2015-06-30 17:02
Are you sure that's the same issue? It looks like your system can't find the phar at all. Previously the error was related to the phar attempting to include another file in the phar.

**Comment by Frozenfire92** [comment] 2015-06-30 17:29
Yes you are correct, my bad. I'm not entirely sure what is going on :confused:

**Comment by NobleUplift** [comment] 2015-06-30 20:52
My coworkers are actually at the AWS conference in Chicago this week, so I won't have the server access to test this change. Sorry guys.

**Comment by NobleUplift** [comment] 2015-07-02 16:40
My coworker and I were able to test this today using the phar posted here 6 days ago. At first, we received this error:

```php
PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Missing required client configuration options: \n\nversion: (string)\n\n  A "version" configuration value is required. Specifying a version constraint\n  ensures that your code will not be affected by a breaking change made to the\n  service. For example, when using Amazon S3, you can lock your API version to\n  "2006-03-01".\n  \n  Your build of the SDK has the following version(s) of "dynamodb": * "2012-08-10"\n  \n  You may provide "latest" to the "version" configuration value to utilize the\n  most recent available API version that your client's API provider can find.\n  Note: Using 'latest' in a production application is not recommended.\n  \n  A list of available API versions can be found on each client's API documentation\n  page: http://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html. If you are\n  unable to load a specific API version, then you may need to update your copy of\n  the SDK.' in phar:///usr/local/advanse/lib/php/aws.phar/Aws/ClientResolver.php: in phar:///usr/local/advanse/lib/php/aws.phar/Aws/ClientResolver.php on line 319
```

But that was easily fixed, and then we got this error:

```php
PHP Catchable fatal error:  Argument 2 passed to Aws\\AwsClient::getCommand() must be of the type array, integer given, called in phar:///usr/local/advanse/lib/php/aws.phar/Aws/AwsClient.php on line 167 and defined in phar:///usr/local/advanse/lib/php/aws.phar/Aws/AwsClient.php on line 211
```

Is the second error on me or inside the phar?

**Comment by mtdowling** [comment] 2015-07-02 16:42
@NobleUplift Yes, the phar is for version 3.x of the SDK. It looks like it's working as far as the phar is concerned though, so that's good news. The second issue looks like a coding issue. Can you show the code you used that triggered that error?

**Comment by mtdowling** [comment] 2015-07-02 22:10
Now that https://github.com/aws/aws-sdk-php/pull/662 has been merged and two users have shown that it fixes the issue, I'll resolve this issue. We'll have new phars packaged up with an alias in the next release.

**Comment by madz7z** [comment] 2015-07-03 13:42
Unfortunately issue is back in other place **after restarting apache**. Strange thing that it disappeared in initial place. One more thing: with or without #662 getting same results.
Had to switch to ZIP version.

**Comment by thomas83** [comment] 2015-07-28 17:26
The issue still seems to exist with the latest 3.2.1 issue.  The environment is just the same as r-baker's.

I'm not gonna write too much details here, as it's gonna be the same errors and stuff.  I just wanted to raise a headsup, that the bug is still here.

Thanks!

**Comment by georgringer** [comment] 2015-08-10 07:26
bug is still there, at least in latest 5.3 phar file

**Comment by oberman** [comment] 2015-08-18 17:49
Same happened to me (3.2.6), so this issue seems very real still.  I switched to the .zip install pattern (http://stackoverflow.com/questions/28000901/why-aws-phar-runs-once-then-wont-load-again), which works.

**Comment by jeskew** [comment] 2015-08-18 19:44
@oberman Can you provide any guidance on how to reproduce the issue?

**Comment by jeskew** [comment] 2015-08-18 23:58
@oberman Could you try with [this version of the phar](https://s3-us-west-2.amazonaws.com/s3eskew/aws.phar) linked to below? I believe it should fix the issue you're facing.

**Comment by thomas83** [comment] 2015-08-19 03:05
I guess it'd be great to have everyone try this, and wait for a few weeks down the road and see if this problem happens again (since it doesn't always happen)?

**Comment by jeskew** [comment] 2015-08-19 05:14
@thomas83 does it only happen once every few weeks in production?

**Comment by thomas83** [comment] 2015-08-19 05:23
I wouldn't say it's once every few weeks, but the issue is quite random.  It looks completely fine after I upload it to production, tested it.  Then, after a day, it would suddenly throw out this error.  Once this error happens, it will stay there until we do something about it.

Then, when our developers try to investigate, we "rename the file (eg. to .bak), and then rename it back", and it would start working again.

Pretty awkward eh?

**Comment by jeremeamia** [comment] 2015-08-19 05:34
WAT?

**Comment by thomas83** [comment] 2015-08-19 05:37
Yeah it's pretty weird.  Currently I'm forced to use the full ZIP folder package because of this issue, which has been around for quite a few versions in this SDK.

**Comment by oberman** [comment] 2015-08-19 13:37
@jeskew the linked phar didn't fail after several refreshes.  the 3.2.6 phar would fail 100% of the time on the 2nd refresh.

what was the change, out of curiosity?

**Comment by jeskew** [comment] 2015-08-19 15:57
I added a call to `Phar::mapPhar('aws.phar')` in the stub, which supposedly reads the file's manifest into memory and binds the contents of phar to `phar://aws.phar`. This seems to be done implicitly when loading a phar from the filesystem but not when a phar is loaded from opcache.

**Comment by oberman** [comment] 2015-08-19 17:24
Thanks!  I looked up the docs:
http://php.net/manual/en/phar.mapphar.php

I noticed you are using a static symbolic name (aws.phar).  There is a comment in the docs that this might cause problems for people using multiple versions of the aws.phar at the same time (*).  Could the symbol (and filename) be qualified with the version #?  I renamed my phar, just to make bookkeeping easier (e.g. aws.phar -> aws-3.2.6.phar).  But, apparently, due to the internal symbolic name, issues could remain.  

(*) Seems like an odd use case, but I have an example: I have a web host for testing that uses vhosts, each vhost could be running a different checkout and thus different aws.phar.

**Comment by jeskew** [comment] 2015-08-19 20:09
That's a good point. I updated the PR to also set a versioned alias. You wouldn't actually be able to load two different versions in the same process -- the files containing function definitions for the SDK, Guzzle, and JMESPath would conflict with each other -- but that should take care of any issues arising from a shared opcache.

Btw, could you tell me about about the environment in which you ran into this issue? We've been consistently unable to reproduce this issue on freshly provisioned Ec2 instances running either Apache or Nginx w/ php-fpm.

**Comment by oberman** [comment] 2015-08-19 20:19
-amazon-linux-ami/2014.09 (not updated, 248 packages need updating)
-An old version of Codeigniter (don't ask)
-I can post a full phpinfo, but trying to slice out what I *think* matters first:
Apache/2.4.10 (Amazon) OpenSSL/1.0.1i-fips PHP/5.5.22
apcu 	4.0.3
Phar EXT version	2.0.2
Phar API version	1.1.1
Opcache has a million values, but my ini:
zend_extension=/usr/lib64/php/5.5/modules/opcache.so
opcache.memory_consumption=128
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=4000
opcache.revalidate_freq=0
opcache.fast_shutdown=1
opcache.enable_cli=1

**Closed** 2015-08-20 22:36 UTC

**Comment by fredden** [comment] 2015-08-30 23:29
@jeskew, any chance you could add a call to `Phar::mapPhar('aws.phar')` into the stub for the v2.8 branch? We're getting this error with v2.8.19.

**Comment by jeskew** [comment] 2015-09-03 18:12
@fredden [Done](https://github.com/aws/aws-sdk-php/pull/750). That will go out in the next v2 release.

**Comment by NestorAcevedo** [comment] 2016-02-26 17:01
for any who uses AWS Phar: the main issue is in the *require_once* that invokes only once the Phar file and "let it" in memory. While, you should to use *require* or *include* moreover if you have to make more than one calling to aws.phar file.
