### ISSUE TITLE
Upload to S3 using Aws\S3\Transfer not uploading properly

### ISSUE THREAD

**Issue by adam-ut** [aws/aws-sdk-php#1982] opened 2020-03-10 15:36 UTC
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for PHP?
3.133

### Version of PHP (`php -v`)?
7.0.33

### What issue did you see?
I'm passing an iterator, GlobIterator, to Aws\S3\Transfer, so I'm only uploading compressed files to the S3 bucket. Files appear in the S3 folder with the correct name, however the content is the full path name of the file rather than the contents of the file.

Example: If the contents of the compressed file 'abc' from file /path/file.gz the contents of the file in the S3 bucket is '/path/file.gz'. The file in S3 is not really a compressed file, but rather a text file.

### Steps to reproduce
```php
$s3_client = new Aws\S3\S3Client([ ... connection details ... ]);
$s3_transfer = new Aws\S3\Transfer(
	$s3_client,
	new GlobIterator("{$source_dir}/*.gz"),
	"s3://{$destination_s3_bucket}/{$destination_path}/",
	[
	  'base_dir' => $source_dir,
	  'debug' => true,
	]
  );

$s3_transfer->transfer();
```

### Additional context
I've confirmed that GlobIterator is generating the correct listing of files. I've gotten the same results using DirectoryIterator and FilesystemIterator. If I use a directory name instead of an iterator, it works as expected and files appear to upload properly. However, I'm unable to filter on file type for upload.

**Comment by diehlaws** [comment] 2020-03-14 00:56
Hi @adam-ut, thanks for reaching out to us about this. Unfortunately I'm not able to reproduce the behavior you describe, gzipping text files and uploading them using your code snippet, then downloading them to a different directory they appear to behave as gzip files, and unzipping them then reading the contents returns the same text `echo`'d into the source files before they were zipped.

```
[data]$ for i in {1..5}; do echo "File contents of $i" > $i.txt; done
[data]$ for i in {1..5}; do gzip $i.txt; done
[data]$ ls
1.txt.gz 2.txt.gz 3.txt.gz 4.txt.gz 5.txt.gz
[data]$ cd ..
[1982]$ php s3TransferIterator.php 
Using AWS SDK for PHP version 3.133.6
Transferring ./data//1.txt.gz -> s3://alex-sdk/php/1982/1.txt.gz (PutObject)
Transferring ./data//2.txt.gz -> s3://alex-sdk/php/1982/2.txt.gz (PutObject)
Transferring ./data//3.txt.gz -> s3://alex-sdk/php/1982/3.txt.gz (PutObject)
Transferring ./data//4.txt.gz -> s3://alex-sdk/php/1982/4.txt.gz (PutObject)
[1982]$ cd data/
[data]$ mkdir download
[data]$ cd !$
cd download
[download]$ aws s3 sync s3://alex-sdk/php/1982/ .
download: s3://alex-sdk/php/1982/2.txt.gz to ./2.txt.gz            
download: s3://alex-sdk/php/1982/1.txt.gz to ./1.txt.gz            
download: s3://alex-sdk/php/1982/3.txt.gz to ./3.txt.gz             
download: s3://alex-sdk/php/1982/5.txt.gz to ./5.txt.gz             
download: s3://alex-sdk/php/1982/4.txt.gz to ./4.txt.gz             
[download]$ ls
1.txt.gz 2.txt.gz 3.txt.gz 4.txt.gz 5.txt.gz
[download]$ cat 1.txt.gz
:$l^1.txts��IUH��+I�+)V�OS0��� $[download]$ for i in {1..5}; do gunzip $i.txt.gz; done
[download]$ ls
1.txt 2.txt 3.txt 4.txt 5.txt
[download]$ for i in {1..5}; do cat $i.txt; done
File contents of 1
File contents of 2
File contents of 3
File contents of 4
File contents of 5
```

How are you downloading the files after the SDK's S3 Transfer Manager uploads them to S3? Does the `ContentLength` and `ContentType` match what you're expecting when you issue a `headObject` call to these gzip files in S3? Enabling debug logging in the `S3Client` and providing the resultant output will help us better understand what's happening from the SDK's end for the uploads.

**Comment by adam-ut** [comment] 2020-05-05 20:38
@diehlaws : I apologize for my lack of response. I was requested to focus on something else. However, I would like to revisit this. Can the issue be re-opened or would I need to open a new ticket?

**Comment by diehlaws** [comment] 2020-05-05 21:06
@adam-ut No worries, we can re-open this issue and continue working on this here. Please let me know the information requested in my previous response along with any additional context that would help us better reproduce this behavior.

**Comment by adam-ut** [comment] 2020-05-05 21:37
Thank you, @diehlaws! I've updated to 3.137.3 of the framework and tested using PHP 7.0 (vm) and PHP 7.0 and 7.4 (docker) which is yielding the same results.

Each file is over 100MB, but the files that appear in the target bucket (using the UI) are less than 100B.

When calling objectHead, I get the following details:

"ContentType": "application/octet-stream" 

however, calling file --mime-type -b <file name> on the source file yields "application/x-gzip".

Downloading the gzipped file via the UI shows the file as "text/plain"

Here's the content of the debug output:

Transferring /home/user/path/large_fileaa.gz -> s3://adam.dev.bucket/path/large_fileaa.gz (CreateMultipartUpload)
Transferring /home/user/path/large_fileab.gz -> s3://adam.dev.bucket/path/large_fileab.gz (CreateMultipartUpload)
Transferring /home/user/path/large_fileac.gz -> s3://adam.dev.bucket/path/large_fileac.gz (CreateMultipartUpload)
Transferring /home/user/path/large_filead.gz -> s3://adam.dev.bucket/path/large_filead.gz (CreateMultipartUpload)
Transferring /home/user/path/large_fileae.gz -> s3://adam.dev.bucket/path/large_fileae.gz (CreateMultipartUpload)
Transferring /home/user/path/large_filead.gz -> s3://adam.dev.bucket/path/large_filead.gz (UploadPart) : Part=1
Transferring /home/user/path/large_fileae.gz -> s3://adam.dev.bucket/path/large_fileae.gz (UploadPart) : Part=1
Transferring /home/user/path/large_fileab.gz -> s3://adam.dev.bucket/path/large_fileab.gz (UploadPart) : Part=1
Transferring /home/user/path/large_fileaa.gz -> s3://adam.dev.bucket/path/large_fileaa.gz (UploadPart) : Part=1
Transferring /home/user/path/large_fileac.gz -> s3://adam.dev.bucket/path/large_fileac.gz (UploadPart) : Part=1
Transferring /home/user/path/large_fileae.gz -> s3://adam.dev.bucket/path/large_fileae.gz (CompleteMultipartUpload)
Transferring /home/user/path/large_filead.gz -> s3://adam.dev.bucket/path/large_filead.gz (CompleteMultipartUpload)
Transferring /home/user/path/large_fileab.gz -> s3://adam.dev.bucket/path/large_fileab.gz (CompleteMultipartUpload)
Transferring /home/user/path/large_fileaa.gz -> s3://adam.dev.bucket/path/large_fileaa.gz (CompleteMultipartUpload)
Transferring /home/user/path/large_fileac.gz -> s3://adam.dev.bucket/path/large_fileac.gz (CompleteMultipartUpload)
Transferring /home/user/path/large_fileaf.gz -> s3://adam.dev.bucket/path/large_fileaf.gz (CreateMultipartUpload)
Transferring /home/user/path/large_fileag.gz -> s3://adam.dev.bucket/path/large_fileag.gz (CreateMultipartUpload)
Transferring /home/user/path/large_fileaf.gz -> s3://adam.dev.bucket/path/large_fileaf.gz (UploadPart) : Part=1
Transferring /home/user/path/large_fileah.gz -> s3://adam.dev.bucket/path/large_fileah.gz (CreateMultipartUpload)
Transferring /home/user/path/large_fileai.gz -> s3://adam.dev.bucket/path/large_fileai.gz (CreateMultipartUpload)
Transferring /home/user/path/large_fileaj.gz -> s3://adam.dev.bucket/path/large_fileaj.gz (CreateMultipartUpload)
Transferring /home/user/path/large_fileag.gz -> s3://adam.dev.bucket/path/large_fileag.gz (UploadPart) : Part=1
Transferring /home/user/path/large_fileaf.gz -> s3://adam.dev.bucket/path/large_fileaf.gz (CompleteMultipartUpload)
Transferring /home/user/path/large_fileah.gz -> s3://adam.dev.bucket/path/large_fileah.gz (UploadPart) : Part=1
Transferring /home/user/path/large_fileai.gz -> s3://adam.dev.bucket/path/large_fileai.gz (UploadPart) : Part=1
Transferring /home/user/path/large_fileaj.gz -> s3://adam.dev.bucket/path/large_fileaj.gz (UploadPart) : Part=1
Transferring /home/user/path/large_fileag.gz -> s3://adam.dev.bucket/path/large_fileag.gz (CompleteMultipartUpload)
Transferring /home/user/path/large_fileah.gz -> s3://adam.dev.bucket/path/large_fileah.gz (CompleteMultipartUpload)
Transferring /home/user/path/large_fileai.gz -> s3://adam.dev.bucket/path/large_fileai.gz (CompleteMultipartUpload)
Transferring /home/user/path/large_fileak.gz -> s3://adam.dev.bucket/path/large_fileak.gz (CreateMultipartUpload)
Transferring /home/user/path/large_fileaj.gz -> s3://adam.dev.bucket/path/large_fileaj.gz (CompleteMultipartUpload)
Transferring /home/user/path/large_fileak.gz -> s3://adam.dev.bucket/path/large_fileak.gz (UploadPart) : Part=1
Transferring /home/user/path/large_fileal.gz -> s3://adam.dev.bucket/path/large_fileal.gz (CreateMultipartUpload)
Transferring /home/user/path/large_fileam.gz -> s3://adam.dev.bucket/path/large_fileam.gz (CreateMultipartUpload)
Transferring /home/user/path/large_fileak.gz -> s3://adam.dev.bucket/path/large_fileak.gz (CompleteMultipartUpload)
Transferring /home/user/path/large_filean.gz -> s3://adam.dev.bucket/path/large_filean.gz (CreateMultipartUpload)
Transferring /home/user/path/large_fileao.gz -> s3://adam.dev.bucket/path/large_fileao.gz (CreateMultipartUpload)
Transferring /home/user/path/large_fileal.gz -> s3://adam.dev.bucket/path/large_fileal.gz (UploadPart) : Part=1
Transferring /home/user/path/large_fileam.gz -> s3://adam.dev.bucket/path/large_fileam.gz (UploadPart) : Part=1
Transferring /home/user/path/large_filean.gz -> s3://adam.dev.bucket/path/large_filean.gz (UploadPart) : Part=1
Transferring /home/user/path/large_fileao.gz -> s3://adam.dev.bucket/path/large_fileao.gz (UploadPart) : Part=1
Transferring /home/user/path/large_fileal.gz -> s3://adam.dev.bucket/path/large_fileal.gz (CompleteMultipartUpload)
Transferring /home/user/p -> s3://adam.dev.bucket/path/large_fileam.gz (CompleteMultipartUpload)
Transferring /home/user/path/large_filean.gz -> s3://adam.dev.bucket/path/large_filean.gz (CompleteMultipartUpload)
Transferring /home/user/path/large_fileao.gz -> s3://adam.dev.bucket/path/large_fileao.gz (CompleteMultipartUpload)
Transferring /home/user/path/large_fileap.gz -> s3://adam.dev.bucket/path/large_fileap.gz (CreateMultipartUpload)
Transferring /home/user/path/large_fileaq.gz -> s3://adam.dev.bucket/path/large_fileaq.gz (CreateMultipartUpload)
Transferring /home/user/path/large_filear.gz -> s3://adam.dev.bucket/path/large_filear.gz (CreateMultipartUpload)
Transferring /home/user/path/large_fileas.gz -> s3://adam.dev.bucket/path/large_fileas.gz (CreateMultipartUpload)
Transferring /home/user/path/large_fileaq.gz -> s3://adam.dev.bucket/path/large_fileaq.gz (UploadPart) : Part=1
Transferring /home/user/path/large_fileap.gz -> s3://adam.dev.bucket/path/large_fileap.gz (UploadPart) : Part=1
Transferring /home/user/path/large_fileat.gz -> s3://adam.dev.bucket/path/large_fileat.gz (CreateMultipartUpload)
Transferring /home/user/path/large_filear.gz -> s3://adam.dev.bucket/path/large_filear.gz (UploadPart) : Part=1
Transferring /home/user/path/large_fileas.gz -> s3://adam.dev.bucket/path/large_fileas.gz (UploadPart) : Part=1
Transferring /home/user/path/large_fileaq.gz -> s3://adam.dev.bucket/path/large_fileaq.gz (CompleteMultipartUpload)
Transferring /home/user/path/large_fileap.gz -> s3://adam.dev.bucket/path/large_fileap.gz (CompleteMultipartUpload)
Transferring /home/user/path/large_fileat.gz -> s3://adam.dev.bucket/path/large_fileat.gz (UploadPart) : Part=1
Transferring /home/user/path/large_filear.gz -> s3://adam.dev.bucket/path/large_filear.gz (CompleteMultipartUpload)
Transferring /home/user/path/large_fileas.gz -> s3://adam.dev.bucket/path/large_fileas.gz (CompleteMultipartUpload)
Transferring /home/user/path/large_fileau.gz -> s3://adam.dev.bucket/path/large_fileau.gz (CreateMultipartUpload)
Transferring /home/user/path/large_fileat.gz -> s3://adam.dev.bucket/path/large_fileat.gz (CompleteMultipartUpload)
Transferring /home/user/path/large_fileav.gz -> s3://adam.dev.bucket/path/large_fileav.gz (CreateMultipartUpload)
Transferring /home/user/path/large_fileau.gz -> s3://adam.dev.bucket/path/large_fileau.gz (UploadPart) : Part=1
Transferring /home/user/path/large_fileaw.gz -> s3://adam.dev.bucket/path/large_fileaw.gz (CreateMultipartUpload)
Transferring /home/user/path/large_fileax.gz -> s3://adam.dev.bucket/path/large_fileax.gz (CreateMultipartUpload)
Transferring /home/user/path/large_fileav.gz -> s3://adam.dev.bucket/path/large_fileav.gz (UploadPart) : Part=1
Transferring /home/user/path/large_fileau.gz -> s3://adam.dev.bucket/path/large_fileau.gz (CompleteMultipartUpload)
Transferring /home/user/path/large_fileaw.gz -> s3://adam.dev.bucket/path/large_fileaw.gz (UploadPart) : Part=1
Transferring /home/user/path/large_fileax.gz -> s3://adam.dev.bucket/path/large_fileax.gz (UploadPart) : Part=1
Transferring /home/user/path/large_fileav.gz -> s3://adam.dev.bucket/path/large_fileav.gz (CompleteMultipartUpload)
Transferring /home/user/path/large_fileaw.gz -> s3://adam.dev.bucket/path/large_fileaw.gz (CompleteMultipartUpload)
Transferring /home/user/path/large_fileax.gz -> s3://adam.dev.bucket/path/large_fileax.gz (CompleteMultipartUpload)

Thank you again for taking time to review this and help me understand what I'm missing.

**Comment by diehlaws** [comment] 2020-05-14 23:31
Thanks for the additional context @adam-ut. I'm able to reproduce the described behavior when using a file large enough for the S3 Transfer Manager to upload to S3 using a multipart upload instead of a single PutObject call. We'll have to look further into what's causing this behavior in the Transfer Manager.

In the meantime, you can work around this behavior by setting `mup_threshold` (multi-part threshold) in the Transfer Manager's options array to a size larger than the files you're uploading up to a maximum of 5GB (S3's size limit for a PutObject call).

**Comment by SamRemis** [comment] 2020-08-28 19:49
@adam-ut Hi Adam, just wanted to update you and let you know we are working on it now; I found the issue and am writing a patch for it.  We will close this issue when the patch is released.  
Thank you again for bringing this to our attention

**Closed** 2020-10-19 18:05 UTC
Labels: bug

**Comment by adam-ut** [comment] 2020-11-05 20:17
Confirmed that this is now functioning as intended. Thanks, @SamRemis and @diehlaws!

**Comment by SamRemis** [comment] 2020-11-06 16:34
@adam-ut  Thanks for following up!  Glad it's working for you now
