### ISSUE TITLE
PHP notice on RetryMiddleware after update to 3.134.2

### ISSUE THREAD

**Issue by franksl** [aws/aws-sdk-php#1990] opened 2020-04-03 11:06 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
Hi,
I have a phar that uses the AWS S3 client to execute some putObject methods.
After updating to the latest 3.134.2 I get this notice:

PHP Notice:  Object of class Closure could not be converted to int in phar:///mycode/vendor/aws/aws-sdk-php/src/RetryMiddleware.php on line 105

**Version of AWS SDK for PHP?**
3.134.2
* get SDK version by printing the output of `Aws\Sdk::VERSION` in your code 
* if the SDK was installed via composer you can see the version installed with `composer show -i` 

**Version of PHP (`php -v`)?**
7.1

**To Reproduce (observed behavior)**
Execute a putObject with the S3 client. I can be more specific if needed but I have to analyze the code, I can say that before this update a couple of days ago I didn't have this problem and nothing changed on my side.

**Comment by diehlaws** [comment] 2020-04-03 22:16
Hi @franksl, thanks for reaching out to us. Unfortunately I haven't been able to reproduce this on my end with a `PutObject` call that only includes `Body`, `Bucket`, and `Key` in the input parameters. 

Do you see this notice on every `PutObject` call issued via the SDK since it was updated to 3.134.2? Or does it only occur on certain `PutObject` calls?  If it is the latter, can you share the input parameters used for the call(s) where this occurs? Can you enable [debug logging](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#debug) in your S3 client and provide the (sanitized) debug output for a call that returns this notice?

Do the calls where you see this notice fail, or do you see the objects corresponding to these calls uploaded to S3 as expected?

Which version of the AWS SDK for PHP did you update from? Looking at the [changelog](https://github.com/aws/aws-sdk-php/blob/master/CHANGELOG.md) I see that version 3.134.0 introduced some [changes](https://github.com/aws/aws-sdk-php/blob/master/src/AwsClient.php#L150) to how retries are handled - if this behavior is breaking your application, you can try using the legacy retry mode by setting `'retries' => ['mode' => 'legacy']` in your S3Client, or by specifying an integer for the `retries` value (previously the default was 3 retries).

**Comment by franksl** [comment] 2020-04-07 10:57
Hi,
Sorry for the delay,
Looks like today I'm unable to reproduce the issue, I assume there were some kind of network problems at the time but I don't know  when the RetryMiddleware gets triggered.
Sorry, I think the issue can be closed, I'll get back if I'll encounter the problem again,
Thanks,
Frank

**Comment by diehlaws** [comment] 2020-04-07 22:08
Thanks for the additional information @franksl, I'm glad to hear this isn't consistent behavior. I'll go ahead and close the issue for now, if you see this come up again please do update the issue so we can re-open it and continue working with you on this.

**Closed by diehlaws** 2020-04-07 22:08 UTC
Labels: guidance, response-requested
