### ISSUE TITLE
[BUG] MultipartCopy.php. Can't use unicode special symbols.

### ISSUE THREAD

**Issue by razielvamp** [aws/aws-sdk-php#2032] opened 2020-06-03 08:17 UTC
What is Aws\S3\MultipartCopy?

It mentioned only once at bottom of this page [aws sdk page](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-multipart-upload.html)

Is that undocumented secret feature?

How can I copy between buckets?

I using this code:
```
$s3 = new Aws\S3\S3Client([
    'region' => $region,
    'version' => 'latest',
    'endpoint' => 'https://s3.'.$region.'.amazonaws.com',
    'credentials' => [
            'key'    => $AwsAccessKeyId,
            'secret' => $AwsSecretAccessKey
        ]
]);
$copier = new Aws\S3\MultipartCopy($s3,
    '/'.$from_bucket_name.'/'.$from_path,
    [
        'Bucket' => $to_bucket_name,
	'Key' => $to_path,
	'part_size' => 52428800,
	'concurrency' => 5
    ]
);
$result = $copier->copy();
```
And my questions are:
1. If $from_path = "from-path/日本語名.jpg" this code is working good, if $from_path = "from-path/日本 語名.jpg" I have get error: 
```
An exception occurred while uploading parts to a multipart upload. The following parts had errors:
- Part 1: Error executing "UploadPartCopy" on "https://TO_BUCKET_NAME.s3.ap-northeast-1.amazonaws.com/some-path/%E6%97%A5%E6%9C%AC%20%E8%AA%9E%E5%90%8D.jpg?partNumber=1&uploadId=gp0JL.gS9fwbuo3XVfkLmkRvBmLL0sWRe2.pYKQtRbaOGK9UGy63CEZrqWNZkisRpHnTtGtQ_tRNTUez5Mvhql83L953GdGQSN6rrspyEGp68PAanvM4xm3KLbLM_c2Q2PvjxnX80S7aJx6fvGxdNw--"; AWS HTTP error: Client error: `PUT https://TO_BUCKET_NAME.s3.ap-northeast-1.amazonaws.com/some-path/%E6%97%A5%E6%9C%AC%20%E8%AA%9E%E5%90%8D.jpg?partNumber=1&uploadId=gp0JL.gS9fwbuo3XVfkLmkRvBmLL0sWRe2.pYKQtRbaOGK9UGy63CEZrqWNZkisRpHnTtGtQ_tRNTUez5Mvhql83L953GdGQSN6rrspyEGp68PAanvM4xm3KLbLM_c2Q2PvjxnX80S7aJx6fvGxdNw--` resulted in a `404 Not Found` response:
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>from-path/??????  (truncated...)
 NoSuchKey (client): The specified key does not exist. - <Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>from-path/?????? ??????.jpg</Key><RequestId>573EFB48C2E5B55E</RequestId><HostId>qMCQixGHwSRllMu75mNZVR0o7ACtcXPpjQc6yH49KpI40uNRNWBAfydEqReegpJvp3woKgxgGIQ=</HostId></Error>
```
I tried to encode url: $from_path = "from-path/".rawurlencode(日本 語名.jpg"). In this way sdk encodes already encoded url one more time, and of course reencoded url is wrong.

2. What if I want to use buckets in different regions? I can set region only once when creating S3Client. Is that region using for $from_bucket or $to_bucket? Multiregion copy is unavailable?

UPDATE1:
Copy don't work with any kanji. 日本 語名.jpg and 日本語名.jpg don't work. Only english alphabet allowed.

**Comment by razielvamp** [comment] 2020-06-04 05:18
Okay. I find bug by myself.

I changed **aws/aws-sdk-php/src/S3/MultipartCopy.php**

**FROM**

```
    protected function getUploadCommands(callable $resultHandler)
    {
        $parts = ceil($this->getSourceSize() / $this->determinePartSize());

        for ($partNumber = 1; $partNumber <= $parts; $partNumber++) {
            // If we haven't already uploaded this part, yield a new part.
            if (!$this->state->hasPartBeenUploaded($partNumber)) {
                $command = $this->client->getCommand(
                    $this->info['command']['upload'],
                    $this->createPart($partNumber, $parts)
                        + $this->getState()->getId()
                );
                $command->getHandlerList()->appendSign($resultHandler, 'mup');
                yield $command;
            }
        }
    }
```

**TO**

```
    protected function getUploadCommands(callable $resultHandler)
    {
        $parts = ceil($this->getSourceSize() / $this->determinePartSize());

        for ($partNumber = 1; $partNumber <= $parts; $partNumber++) {
            // If we haven't already uploaded this part, yield a new part.
            if (!$this->state->hasPartBeenUploaded($partNumber)) {
                $command = $this->client->getCommand(
                    $this->info['command']['upload'],
                    $this->createPart($partNumber, $parts)
                        + $this->getState()->getId()
                );
                $command->getHandlerList()->appendSign($resultHandler, 'mup');
                $key_path = explode('/', $command['CopySource']);
                foreach ($key_path as $key_index => $key_value) {
                    $key_path[$key_index] = rawurlencode($key_value);
                }
                $key_path = implode('/', $key_path);
                $command['CopySource'] = $key_path;
                yield $command;
            }
        }
    }
```

And now it works with any symbols in source key.
I think my solution is not good for push into repo as is, but please check this bug.

**Comment by razielvamp** [comment] 2020-06-04 05:56
And my second question still open. Do you plan to add region parameter for source bucket?
Looks like I can set region when source path set as ARN accesspoint (another one undocumented feature), but that is not simple way.

**Comment by diehlaws** [comment] 2020-06-04 22:23
Hi @razielvamp, thanks for reaching out to us about this. `Aws\S3\MultipartCopy` is a class intended to copy larger files between buckets using S3's [`UploadPartCopy`](https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPartCopy.html) API call. Unfortunately the current implementation of the MultipartCopy client only allows copy operations between buckets in the same region. You should be able to use the S3Client's [`copyObject`](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#copyobject) call to copy objects that are small enough to not require multi-part operations between buckets, if you need to copy objects between buckets across different regions you can use our [S3 Multi-Region client](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-multiregion-client.html) in place of the standard `S3Client`.

I'll be looking into the described behavior shortly, once I have additional information I'll update the issue accordingly.

**Comment by razielvamp** [comment] 2020-06-05 03:54
@diehlaws 
Thank you for answer.

Actually I tried to use standard `S3Client` today, and it copying from `ap-northeast-1` bucket to `us-east-2` bucket without any problems even if I set `ap-northeast-1` (as client `region` parameter) only.

So, is there any difference between `S3Client` and `S3MultiRegionClient` even if both working with different region buckets?

**Comment by SamRemis** [comment] 2020-07-09 00:15
Hi @razielvamp,

Thanks for looking into the issue, your advice on how to fix it came in handy.  The first bug is fixed as of this PR: https://github.com/aws/aws-sdk-php/pull/2045

As for your second question, I wasn't able to replicate exactly what you described.  Both S3Client and S3MultiRegionClient should work for a copy small enough to be done in one part.  For larger copies, the S3Client should throw an error suggesting that you are not using the correct bucket.  

The S3MultiRegionClient will catch this error and automatically reroute the request to the appropriate region.  It is difficult to know why you were able to make a multipart copy from one region to another using an S3Client without seeing how you were calling the function.  Would you be able to provide me with the method call you used on the S3Client so that I can take a look?

**Comment by razielvamp** [comment] 2020-07-17 03:10
@SamRemis 

Thank you for bug fix.

> Would you be able to provide me with the method call you used on the S3Client so that I can take a look?

There is core of my code

```
// $from_bucket_region don't be used

try {
    $s3 = new Aws\S3\S3Client([
        'region' => $to_bucket_region,
        'version' => 'latest',
        'endpoint' => 'https://s3.'.$to_bucket_region.'.amazonaws.com',
        'credentials' => [
				'key'    => $to_bucket_keyid,
				'secret' => $to_bucket_key
            ]
    ]);
} catch (Aws\S3\Exception\S3Exception $e) {
    return "ERROR";
}

try {
	$copier = new Aws\S3\MultipartCopy($s3,
	'/'.$from_bucket_name.'/'.$from_path,
		[
			'Bucket' => $to_bucket_name,
			'Key' => $to_path,
			'part_size' => 52428800,
			'concurrency' => 5
		]);
} catch (Aws\S3\Exception\S3Exception $e) {
	return "ERROR";
}

$is_exception = false;
try {
	$result = $copier->copy();
} catch (Aws\S3\Exception\S3Exception $e) {
	$is_exception = true;
} catch (Aws\Exception\MultipartUploadException $e) {
	$is_exception = true;
	$params = $e->getState()->getId();
	$s3->abortMultipartUpload($params);
} finally {
	if ($is_exception) {
		return "ERROR";
    }
}
```
It working fine with different regions for me.

**Comment by SamRemis** [comment] 2020-07-17 03:51
@razielvamp thank you so much, I'll try to reproduce the error and get back to you :)

**Comment by SamRemis** [comment] 2020-08-01 00:17
@razielvamp  Sorry for the delay; I wasn't able to reproduce the behavior you described.  No matter how I changed the parameters, as long as I was not using a multi-region client, it would always fail in the second catch.  I wish I could explain the behavior further.

We don't suggest relying on this feature going forward as it is not officially supported by the SDK.  Thank you for your question

**Closed by SamRemis** 2020-08-01 00:17 UTC
Labels: guidance

**Comment by razielvamp** [comment] 2020-08-04 00:44
@SamRemis Thank you for answer and checking my code.
Hmm, maybe I missed something when setting buckets?.. I will try to re-check it in future.
