### ISSUE TITLE
S3Client listObjectsV2 Size maxes out at 2147483647

### ISSUE THREAD

**Issue by bferrantino** [aws/aws-sdk-php#1458] opened 2018-01-03 17:51 UTC
I am working with the AWS SDK to pull information from our S3 buckets, and I am running into some issues with the Size property. It seems that for any file larger than 2 GB, the result of listObjectsV2 is returning up to 2147483647 for the Size. This is the max value for a signed integer.

We need to be able to get the actual size of the file as it exists on S3, and I am hoping this is a simple enough fix to get implemented. If not, maybe I am going about this the wrong way? Or maybe some other option is available to get the real size of the file.

Any response is appreciated.

Thanks
Brian

**Comment by kstich** [comment] 2018-01-11 18:20
This looks like it's an issue in the model we have for S3 using the [`"Size"` shape](https://github.com/aws/aws-sdk-php/blob/master/src/data/s3/2006-03-01/api-2.json#L3978) which [is marked as an `integer`](https://github.com/aws/aws-sdk-php/blob/master/src/data/s3/2006-03-01/api-2.json#L5252). This means it would cap down to 32bit `PHP_INT_MAX` on 32bit systems - the number you're seeing. It looks like the service is returning the full size, it's just being cast to an int and capped. 

We'll either have to fix this by converting the field to use the `long` type, causing potential breaks since it was expected behavior, or add a new field (`"SizeFull"` with the correct `long` type) to this operation and others that use the `"Size"` shape.

Can you confirm that you're on a 32bit version of PHP please?

**Comment by bferrantino** [comment] 2018-01-16 17:08
Hi @kstich , Thank you for your response. I have confirmed that I am using a 32-bit version of PHP (on a 64-bit Windows OS). (`echo PHP_INT_MAX;` returns 4).

Please let me know if you need any further information from me.

Thank you
Brian

PS: I saw there was an issue referenced, and that it looks to be pending review/merge. Do you have any idea on when that would be reflected? Or if there is a way I can change it locally to at least use the updated Long type. Any help is appreciated. Thanks!

**Comment by bferrantino** [comment] 2018-01-16 17:19
I was actually able to change it locally, and it is working for me within my application. Thank you for your investigation and assistance with this. Please inform when the change is committed and I will pull in your latest code revisions through that date.

Thanks again
Brian

**Closed** 2018-01-17 20:59 UTC
Labels: In-progress, bug

**Comment by kstich** [comment] 2018-01-18 01:12
This fix was released in [version 3.50.0](https://github.com/aws/aws-sdk-php/releases/tag/3.50.0).
