### ISSUE TITLE
DynamoDB segmentation fault when deleting table and waiting for TableNotExists

### ISSUE THREAD

**Issue by cmpaul** [aws/aws-sdk-php#1121] opened 2016-11-20 18:06 UTC
In a unit test, I'm following the [documentation](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/LowLevelPHPCreateUpdateDeleteTable.html#sect-delete-table) for deleting a table in a [local DynamoDB instance](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html):

```php
$dynamodb->deleteTable('tableName');
$dynamodb->waitUntil('TableNotExists', [
    'TableName' => 'tableName',
    '@waiter' => [
        'delay' => 5,
        'maxAttempts' => 2
    ]
]);
```

This results in a Segmentation fault, which I'm able to log with `strace`:

```
...
open("/composer/vendor/aws/aws-sdk-php/src/Exception/AwsException.php", O_RDONLY) = 5
fstat(5, {st_mode=S_IFREG|0664, st_size=5214, ...}) = 0
fstat(5, {st_mode=S_IFREG|0664, st_size=5214, ...}) = 0
fstat(5, {st_mode=S_IFREG|0664, st_size=5214, ...}) = 0
fstat(5, {st_mode=S_IFREG|0664, st_size=5214, ...}) = 0
mmap(NULL, 5214, PROT_READ, MAP_SHARED, 5, 0) = 0x7f97bfd93000
munmap(0x7f97bfd93000, 5214)            = 0
close(5)                                = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x2ff9b299a8} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
```

When I place a breakpoint in the `AwsException.php` constructor, I see the following exception:

```
Error executing "DescribeTable" on "http://localhost:8000"; AWS HTTP error: Client error: `POST http://localhost:8000` resulted in a `400 Bad Request` response:
...
 ResourceNotFoundException (client): Cannot do operations on a non-existent table - {"__type":"com.amazonaws.dynamodb.v20120810#ResourceNotFoundException","message":"Cannot do operations on a non-existent table"}
```

Am I doing this incorrectly? My assumption here is that the `waitUntil('TableNotExists')` is meant to wait for this very thing.

**Comment by cjyclaire** [comment] 2016-11-21 19:03
@cmpaul Your code snippet looks good to me, `waitUntil('TableNotExists')` is checking whether delete operation has been completed. Could you double check which line cause the error? It could be caused by an incorrect name in `deleteTable` instead. For the segmentation fault, it might has to do with your OS environment or xdebug.

**Comment by cmpaul** [comment] 2016-11-21 22:51
@cjyclaire Thanks for the quick response. The odd thing is that the `deleteTable()` call works fine and the table is deleted. I think it has something to do with the `waitUntil()` -- if I remove that, no segfault. I'll try disabling xDebug and see if that helps (environment is Ubuntu 14.04, PHP 5.5.9).

**Comment by cjyclaire** [comment] 2016-11-21 22:53
@cmpaul Ah interesting, I'll take a look to see if I could reproduce it there.

**Comment by cjyclaire** [comment] 2016-11-22 21:55
@cmpaul Taking a second look, first, when deleting table, you need to do:
```
$ddb->deleteTable([
    'TableName' => 'toDelete'
]);
```
instead of passing in the string directly. Since you succeed in deleting the table, then I assume it's just a typo in your code snippet.

I couldn't reproduce the issue locally still. Yet it's worth to be noticed that this might be caused by running the same script twice, because first attempt succeed, and second attempt cannot find the table since it has been deleted.

**Comment by cmpaul** [comment] 2016-11-23 02:52
@cjyclaire Indeed, that's a typo in my original code snippet, I'm passing the `'TableName'` in the options array.

I really think the issue is with the `waitUntil` -- the stack trace I'm able to intercept indicates that it's trying to execute a `DescribeTable` (which doesn't work because the table was deleted). It may not be related to this `waitUntil`, though... I'm wondering if I have another Promise queued up in the Guzzle TaskQueue from a previous command.

I'll post here with more updates once I'm able to confirm. Thanks again for the investigation!

**Comment by cmpaul** [comment] 2016-11-26 15:06
@cjyclaire No luck in finding out the root cause. I'm still getting the error locally, though my code works fine without the `waitUntil`, so I'm just going to roll with that for now. Since you can't reproduce, I'd say it's probably related to my environment and you can go ahead and close this issue.

**Comment by cjyclaire** [comment] 2016-11-28 02:02
Thanks for getting back, closing, yet feel free to reopen with further details :)

**Closed by cjyclaire** 2016-11-28 02:02 UTC
Labels: awaiting-reply, question
