### ISSUE TITLE
ApiGatewayManagementApiException does not parse actual AWS error code from response

### ISSUE THREAD

**Issue by georgeboot** [aws/aws-sdk-php#2285] opened 2021-08-06 12:59 UTC
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
When a cal to the ApiGatewayManagementApi results in an error, the corresponding exception is not properly set-up.

**Version of AWS SDK for PHP?**
3.186.1

**Version of PHP (`php -v`)?**
8.0

**To Reproduce (observed behavior)**
```php
use Aws\ApiGatewayManagementApi\ApiGatewayManagementApiClient;

$client = new ApiGatewayManagementApiClient([/*options*/]);

try {
    $client->postToConnection([
        'ConnectionId' => 'connection-id-that-is-gone',
        'Data' => 'my data',
    ]);
} catch (ApiGatewayManagementApiException $exception) {
    if (($exception->getAwsErrorCode() === 'GoneException') {
        // handle gone
        return;
    }

    throw $exception;
}
```

Will output the following exception:
```
Aws\ApiGatewayManagementApi\Exception\ApiGatewayManagementApiException Error executing "PostToConnection" on "https://xxxxx.execute-api.us-east-1.amazonaws.com/yyyyy/@connections/connection-id-that-is-gone"; AWS HTTP error: Client error: `POST https://xxxxx.execute-api.us-east-1.amazonaws.com/yyyyy/@connections/connection-id-that-is-gone` resulted in a `410 Gone` response Unable to parse error information from response - Error parsing JSON: Syntax error
     vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php:195 Aws\WrappedHttpHandler::parseError
     vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php:97 Aws\WrappedHttpHandler::Aws\{closure}
```

**Expected behavior**
```php
use Aws\ApiGatewayManagementApi\Exception\ApiGatewayManagementApiException;

assert($exception instanceof ApiGatewayManagementApiException);
assert($exception->getAwsErrorCode() === 'GoneException');
```

**Comment by SamRemis** [comment] 2021-08-06 19:22
@georgeboot Thanks for bringing this to our attention!  I was able to reproduce this, and it looks like they don't send back the service doesn't send back a mandatory header which causes our parsing to fail.  I will open a  ticket with the team and discuss with them to see how fast they can add this header

**Comment by SamRemis** [comment] 2021-08-24 18:01
@georgeboot Looked into it a bit further, and needed a bit more info: is your API that you're using to test a WebSocket API (as opposed to REST or HTTP)?

**Comment by georgeboot** [comment] 2021-08-24 18:07
Yes indeed, a websocket api.

I'm sending messages to a websocket but need to handle the connection being gone (and the disconnect event not being executed yet).

I am currently unable to catch the gone exception as demonstrated above.

I've replicated the above scenario on a real websocket APi as I was unable to mock the error in the SDK. When appending to a `Aws\MockHandler` I still have to create the exception by hand, there is no way to get a 'real' AWS error.

**Comment by SamRemis** [comment] 2021-08-24 18:12
@georgeboot Thanks for responding so quickly!  Do you mind setting `debug => true` in your client constructor and showing me the raw response that comes out?  It should be somewhere in the middle of the log and look something like this:
  ```
  ["response"]=>
    array(4) {
      ["instance"]=>
      string(32) "000000005d59d45f00000000359e6e7b"
      ["statusCode"]=>
      int(400)
      ["headers"]=>
      array(6) {
        ["X-Amz-Security-Token"]=>
        string(7) "[TOKEN]"
        ["Server"]=>
        array(1) {
          [0]=>
          string(10) "awselb/2.0"
        }
        ["Date"]=>
        array(1) {
          [0]=>
          string(29) "Tue, 24 Aug 2021 18:10:34 GMT"
        }
        ["Content-Type"]=>
        array(1) {
          [0]=>
          string(31) "application/json; charset=utf-8"
        }
        ["Content-Length"]=>
        array(1) {
          [0]=>
          string(2) "11"
        }
        ["Connection"]=>
        array(1) {
          [0]=>
          string(10) "keep-alive"
        }
      }
      ["body"]=>
      string(11) "Bad Request"
    }
  }
  
```

**Comment by stobrien89** [comment] 2022-03-11 19:03
Hi @georgeboot,

Closing this for staleness, but let us know if you're still having issues!

**Closed by stobrien89** 2022-03-11 19:03 UTC

**Comment by nixilla** [comment] 2024-01-16 20:18
Workaround:

```php
<?php
use Aws\ApiGatewayManagementApi\Exception\ApiGatewayManagementApiException;

assert($exception instanceof ApiGatewayManagementApiException);
assert($exception->getResponse()->getStatusCode() === 410);
```
