### ISSUE TITLE
Lots of deprecation messages in symfony 5.4

### ISSUE THREAD

**Issue by jokaorgua** [aws/aws-sdk-php#2353] opened 2021-11-30 07:55 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
Lot of deprecation messages when using this SDK with Symfony 5.4

Example
```
Method "ArrayAccess::offsetExists()" might add "bool" as a native return type declaration in the future. Do the same in implementation "Aws\Api\AbstractModel" now to avoid errors or add an explicit @return annotation to suppress this message.

Method "ArrayAccess::offsetSet()" might add "void" as a native return type declaration in the future. Do the same in implementation "Aws\Endpoint\Partition" now to avoid errors or add an explicit @return annotation to suppress this message.
```

**Version of AWS SDK for PHP?**
v3.206.0

**Version of PHP (`php -v`)?**
8.0.13

**To Reproduce (observed behavior)**
Just run any tests with Symfony 5.4

**Expected behavior**
No deprecation message

**Comment by XWB** [comment] 2021-12-01 12:22
Same here, PHP 8 and Symfony 5.4:

> Method "ArrayAccess::offsetExists()" might add "bool" as a native return type declaration in the future. Do the same in implementation "Google\Model" now to avoid errors or add an explicit @return annotation to suppress this message.

> Method "Iterator::current()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Google\Collection" now to avoid errors or add an explicit @return annotation to suppress this message.

etc

Not sure where this Google model comes from, is it shipped with Symfony?

**Comment by jokaorgua** [comment] 2021-12-02 08:16
@XWB I think your errors are from google apis lib, not from the was one
But they are the same. Lack of return types

**Comment by jokaorgua** [comment] 2022-01-06 09:30
any news here?

**Comment by ES-Six** [comment] 2022-01-10 08:30
Also tested with php 8.1.1, same reported behaviour, lot of depreciations.

aws/aws-sdk-php : 3.209.1

Here is a sample of the depreciations :

Depreciation on a dependancy of aws-sdk-php :
`
User Deprecated: Method "GuzzleHttp\Promise\PromisorInterface::promise()" might add "PromiseInterface" as a native return type declaration in the future. Do the same in implementation "Aws\S3\ObjectUploader" now to avoid errors or add an explicit @return annotation to suppress this message.
`

Depreciation in aws-sdk-php itself :
`
User Deprecated: Method "IteratorAggregate::getIterator()" might add "\Traversable" as a native return type declaration in the future. Do the same in implementation "Aws\Command" now to avoid errors or add an explicit @return annotation to suppress this message.
`

`
User Deprecated: Method "ArrayAccess::offsetSet()" might add "void" as a native return type declaration in the future. Do the same in implementation "Aws\Result" now to avoid errors or add an explicit @return annotation to suppress this message.
`

**Comment by ES-Six** [comment] 2022-03-05 22:12
[D3vJ3rry](https://github.com/D3vJ3rry),
I use the latest version of aws sdk for PHP with symfony 5.4 and I did not encountered any problem with the config builder.
Wich version of Symfony are you using ?

**Comment by Blackburn29** [comment] 2022-03-21 15:48
@D3vJ3rry same issue here with symfony 5.4.6

**Comment by D3vJ3rry** [comment] 2022-03-21 16:15
> [D3vJ3rry](https://github.com/D3vJ3rry), I use the latest version of aws sdk for PHP with symfony 5.4 and I did not encountered any critical error with the config builder. Wich version of Symfony are you using ?

SF: 5.4.5
AWS SDK PHP: 3.211.0

**Comment by SamRemis** [comment] 2022-03-29 15:56
Changed the title for what I'm assuming is a typo; if I'm wrong, please correct me.  

I haven't been able to reproduce this; what tests are you running?

**Comment by ES-Six** [comment] 2022-03-31 13:03
> I've already moved to symfony 6 and I do not see any deprecation messages related to aws there. So maybe someone else could examine symfony 5.4?

I observed depreciations does not occured every time (perhaps because of cache or something), to reproduce the depreciations, you can try to :
- Clear cache
- Then trigger somethig that will use AWS SDK for PHP to upload a file to an S3 bucket
- Look at the Symfony Profiler to review all depreciations

or

- Clear cache
- Trigger somethig that will use AWS SDK for PHP to create a lambda function
- Look at the Symfony Profiler to review all depreciations

**Comment by ruudk** [comment] 2022-04-20 07:23
@ES-Six Created a [PR to fix](https://github.com/aws/aws-sdk-php/pull/2434) the deprecation for the PromiseInterface.

**Comment by ES-Six** [comment] 2022-04-20 09:00
> @ES-Six Created a [PR to fix](https://github.com/aws/aws-sdk-php/pull/2434) the deprecation for the PromiseInterface.

Thanks a lot, hope that AWS will accept it.

**Comment by stobrien89** [comment] 2022-11-17 21:39
I believe this was fixed by https://github.com/aws/aws-sdk-php/pull/2434.  Let me know if I'm mistaken!

**Closed by stobrien89** 2022-11-17 21:39 UTC
Labels: bug
