### ISSUE TITLE
Slow requests to SQS using curl_multi_exec and tick() in PHP SDK

### ISSUE THREAD

**Issue by dtirer** [aws/aws-sdk-php#1262] opened 2017-04-24 03:49 UTC
I have a Laravel application which sends data to SQS on nearly every request, using the AWS SDK for PHP. However, every so often, one of these requests takes several seconds to execute. Attached is a stack trace from New Relic. It seems that the tick() method gets called many times and the seconds just pile up. It also seems to be making several attempts to connect to the same endpoint, though they are AWS services so I can't imagine they'd unresponsive this often. Any idea why this might occur?

stack trace: https://ibb.co/f05gLk

**Comment by dgadelha** [comment] 2017-04-24 19:35
Maybe nobody will answer this, or they'll take some days, but as far as I could see from your stack trace, the HTTP requests seems to be using Promises. Probably because the HTTP request runs asynchronously. The `tick()` function might be a simple function to check if the HTTP request has succeeded and, if not yet, wait a second and check again.

So, if the scheme is really this one up there, the 5 seconds delay happening in your requests are just the client waiting for the HTTP response. Then, the Amazon servers take 5 seconds to answer you.

I suggest you to try out doing some tests to see if it's really taking ~5 seconds to give you a result (call it manually [curl, etc], check how this can be optimized or setup a background worker to send those requests for you (if they're not *essential*).

Thanks.

**Comment by dtirer** [comment] 2017-04-24 21:17
@dgadelha @imshashank thanks for your replies.  I'll have to try a test, though for some these, background the publishing to SQS may not be an option.

In general, most of the requests are pretty fast.  However, for a given endpoint, there's maybe 1-2 an hour that take a very long time.

I am making these requests from inside a VPC.  The EC2 instances are in a private subnet, but have access to the internet via a NAT Gateway.

**Comment by imshashank** [comment] 2017-04-25 18:05
@dtirer Also, these delays can be caused by factors such as lag in the network, packets being lost or a lot of uncontrollable features. The SDK will retry failed requests automatically based on the default configuration for the service.  
Please let us know what you find in your testing and please share the results.

**Comment by dtirer** [comment] 2017-04-25 18:59
@imshashank @dgadelha I'll be trying some tests today.  But today, I just noticed that a handful of requests in a given time period were taking a very long time to send messages to SQS, about 60seconds.

Here is the new relic trace for that: https://ibb.co/bDBLfk

during this time period, the requests-per-mintue were particularly low for our servers, so it doesn't seem to be traffic-related

**Comment by imshashank** [comment] 2017-04-26 21:43
@dtirer I see the newrelic logs, this looks more like an SQS issue. For further investigation, I recommend reaching out to the SQS team and letting them know that you are getting delays in the request. You can provide them with request ID and they can provide logs for the specific request.

**Comment by dtirer** [comment] 2017-04-29 17:16
@imshashank @dgadelha well im waiting to here back from AWS, however, i went on my Staging server and and new'd up the AWSClient and basically followed this example: 

http://docs.aws.amazon.com/aws-sdk-php/v3/guide/examples/sqs-examples-send-receive-messages.html

However, for the message, I replaced it with the average size of my message which is roughly 1000 bytes.

Requests were very fast. I then tried putting requests within a `for` loop and sending 100 and 200 and they were also incredibly fast.   And thats already many more than I would be experiencing concurrently. I then tried 2000 within a `for` loop and it took a few seconds to complete, but thats to be expected and is not really my use case

So I think this rules out any potential issues with my VPC setup.  The instances seems perfectly capable of making outgoing requests from the private subnet.  And the SDK seems to perform well.

I suppose this leaves 1) something on AWS's end or 2) The Laravel codebase, which wraps the PHP SDK and may be configuring things differently

**Comment by imshashank** [comment] 2017-05-15 21:31
@dtirer I am happy to help you in resolving this issue for your code. But since we have ruled that the SDK is not causing this issue, I would be closing this issue. I would recommend opening tickets with the specific AWS team and using `requestId` to debug the issue.

Please feel free to reopen this issue in future if there is something we can help you with.

**Closed by imshashank** 2017-05-15 21:31 UTC
Labels: awaiting-reply, usage-question

**Comment by dtirer** [comment] 2017-06-26 16:18
@imshashank After speaking with SQS, it seems that while some of the requests are latent on the SQS end, the cast majority seem to be slow on the PHP application end.  I'm currently trying to isolate components to see where the issue is.  So far I have tried:

1. using a barebones endpoint in my laravel app, which accesses the AWS PHP SDK directly (not using the Laravel "Queue" wrappers.  This resulted in the same issues.

2. I'm currently trying a raw PHP script, outside the Laravel application.  The script contains the exact same code as in the above example (using AWS PHP SDK directly). I'm going to let it it bake for about an hour or so and see if I still record long requests in New Relic.

I assume that if #2 above works fine, that means theres something without how Laravel handles outgoing requests which is causing the issue.

I'll report back shortly

**Comment by dtirer** [comment] 2017-07-12 15:03
@imshashank So after lots of discussions with SQS, it seems that the bulk of these issues are not SQS related.  As of it now, it seems either be the network, or the PHP SDK.

One thing I recently tried doing was adding all the CURL Stats and sending them to New Relic with the long requests.  As it turns out, connecting to SQS is very fast.  In every case, 99% of the time is taken during `time_starttransfer`.  Any idea what this might be?

**Comment by imshashank** [comment] 2017-07-12 16:53
@dtirer Is `time_starttransfer` reported in SDK logs or by newrelic? Also in newrelic you can see how long different parts of the requests are taking. It will be helpful if you can share the stack or logs that you have aggregated so far to help us understand what might be causing the problem.

**Comment by dtirer** [comment] 2017-07-12 17:36
@imshashank `time_starttransfer` is a statistic that Curl provides, since the SDK is using Curl for the requests.  The images from my previous posts above are still applicable, as far as stack trace.  But attached are some more recent ones, with the new data I've collected from the Curl stats. 

https://ibb.co/b2TXFF
https://ibb.co/gLbKvF
https://ibb.co/ncVONv
https://ibb.co/f5XsFF
https://ibb.co/nvFCFF

**Comment by dtirer** [comment] 2017-07-13 03:42
I also profiled a basic endpoint using Blackfire (https://blackfire.io).  This endpoint simply news up the AWS PHP SDK and sends 1 kb message to SQS.  Attached are some images of the results.  It seems `curl_multi_select` is called 11 times and `curl_multi_exec` is called 13 times.  And this is where all the time is being taken

https://ibb.co/nhDSXv
https://ibb.co/iL4qkF
https://ibb.co/drNbQF

**Comment by moeseth** [comment] 2017-08-10 15:25
@dtirer did you solve this issue? I'm having the same problem.

<img width="1016" alt="screen shot 2017-08-10 at 9 54 35 pm" src="https://user-images.githubusercontent.com/534443/29178082-87f88806-7e16-11e7-92d2-f60fb4c4c8b6.png">

**Comment by dtirer** [comment] 2017-08-10 15:45
@moeseth I did not, though I'm glad to see I'm not crazy :)

My conclusion was that php is not great for outbound connections. And a certain percentage of the requests just seem to take a while. 

I had also tried building a Go application that sends 5 request/minute to sqs, and I didn't experience the issue. Only the ocassional sqs latency. 

So I've since used sqs for less, and only for the cases I truly need it

**Comment by moeseth** [comment] 2017-08-10 15:48
@dtirer I did. We have been heavily relying upon sqs. Looking for a quick fix :-(

**Comment by mattfo0** [comment] 2019-04-17 21:54
Curious if anyone has a fix for above. Seeing the same.

**Comment by ammont** [comment] 2019-09-09 15:16
We're experiencing the same issue, why it's closed if it's not resolved?

**Comment by vlacour97** [comment] 2021-07-02 09:34
I have the same problem. I have ~ 1 second latency when sending SQS message from Symfony app with AWS SDK. 
The code is stored on a docker instance located on an EC2 and the queue traffic is very light. 
With curl request on this instance, the latency is only a few milliseconds.
Does anyone have a fix for this problem?

**Comment by giannign1** [comment] 2021-08-14 09:38
Same issue here :/ still no solution??

**Comment by eabarca-lanacion** [comment] 2021-09-14 22:50
Same issue here!

**Comment by ariellurodriguez** [comment] 2021-11-08 16:44
We have the same problem, we use the Laravel SQS queue driver and once a day or so this error appeared. It wasn't traffic related or due to anything we could find. It would randomly log on New Relic that a request that normally takes 17ms to complete, creating a new SQS message, timed out after a minute.

Luckily, in our case, it only happens when we create messages to SQS. So what we did was to implement a timeout and connect_timeout in laravel:

```
Config::set('queue.connections.sqs.http.timeout',10);
Config::set('queue.connections.sqs.http.connect_timeout',10);
```

By default there are 3 retries to complete the request, so even though we know it keeps failing, the message gets sent.

**Comment by FilipNikolovski** [comment] 2022-02-18 12:00
We have the same issue here, we use DynamoDB to fetch an item, and the initialization of the client and the query takes a whopping 30ms. Most of the time spent on CPU is used by `curl_multi_select` and `curl_multi_exec`. Is there any solution to this problem?

**Comment by HarshithCariappa** [comment] 2023-11-06 06:59
I am facing the same issue as @FilipNikolovski we are using DynamoDB and trying to get an item by its primary key, Most of the times its fast but we see few requests in a day takes more than a second, on checking further and profiling found that `GuzzleHttp\Handler\CurlMultiHandler::tick` here are the details, Dynamodb Metrics show that the maximum latency was 231 milliseconds only, Anyone has a solution for this? 

![image](https://github.com/aws/aws-sdk-php/assets/10757380/f150ec1b-1cb9-4d91-9d8a-1f1a4a58b23d)
