### ISSUE TITLE
Bedrock Runtime invokeModelWithResponseStream: Undefined array key "bytes"

### ISSUE THREAD

**Issue by prattcmp** [aws/aws-sdk-php#2817] opened 2023-11-09 03:06 UTC
### Describe the bug

When calling the invokeModelWithResponseStream() method from the AWS PHP SDK within a Laravel application, the EventParsingIterator expected to contain a stream of events is returning empty. This issue occurs despite the expected behavior where the iterator should yield event data. Debug logs show that when casting the iterator to an array, an empty array is obtained, and iterating over it directly does not yield any events.

### Expected Behavior

The EventParsingIterator should provide a non-empty collection of events when accessed, allowing a foreach loop to iterate over each event successfully.

### Current Behavior

Currently, when accessing the EventParsingIterator, no events are returned. Debugging with Log::debug() shows an empty structure:

`{"Aws\\Api\\Parser\\EventParsingIterator":[]}`

Attempts to iterate over the iterator result in an error:

```
ErrorException: Undefined array key "bytes" in /var/www/html/vendor/aws/aws-sdk-php/src/Api/Parser/EventParsingIterator.php:96
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/html/vendor/aws/aws-sdk-php/src/Api/Parser/EventParsingIterator.php(96): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#2 /var/www/html/vendor/aws/aws-sdk-php/src/Api/Parser/EventParsingIterator.php(39): Aws\Api\Parser\EventParsingIterator->parseEvent()
#3 /var/www/html/app/Services/TextGeneration.php(646): Aws\Api\Parser\EventParsingIterator->current()
#4 /var/www/html/app/Services/TextGeneration.php(554): App\Services\TextGeneration->call_aws_bedrock()
#5 /var/www/html/app/Services/TextGeneration.php(1083): App\Services\TextGeneration->chat()
#6 /var/www/html/app/Services/TextGeneration.php(1009): App\Services\TextGeneration->generate_stream()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(353): App\Services\TextGeneration->generate_chat_stream()
#8 /var/www/html/app/Jobs/StreamChatMessage.php(39): Illuminate\Support\Facades\Facade::__callStatic()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Jobs\StreamChatMessage->handle()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\Bus\Dispatcher->dispatchNow()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Middleware/WithoutOverlapping.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Queue\Middleware\WithoutOverlapping->handle()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\Pipeline\Pipeline->then()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(439): Illuminate\Queue\Jobs\Job->fire()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(389): Illuminate\Queue\Worker->process()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(333): Illuminate\Queue\Worker->runJob()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(137): Illuminate\Queue\Worker->runNextJob()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(120): Illuminate\Queue\Console\WorkCommand->runWorker()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand->handle()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\Container\Container->call()
#37 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\Component\Console\Command\Command->run()
#39 /var/www/html/vendor/symfony/console/Application.php(1081): Illuminate\Console\Command->run()
#40 /var/www/html/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand()
#41 /var/www/html/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\Component\Console\Application->run()
#43 /var/www/html/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#44 {main}
```

### Reproduction Steps

1. Make a call to invokeModelWithResponseStream() with the necessary parameters.
2. Log the type and contents of the EventParsingIterator that is supposed to contain the response body.
3. Try to iterate over the EventParsingIterator using a foreach loop.
4. Observe that the iterator errors and no iterations occur.

```
$bedrock = AWS::createClient('bedrock-runtime');
        $messages = $this->model_parameters['messages'];
        $invocation_params = [
            'body' => json_encode([
                                      "prompt" => "\n\nHuman: Hi, how are you?\n\nAssistant:",
                                      "max_tokens_to_sample" => 4096,
                                      "temperature" => 0.75,
                                      "top_k" => 50,
                                      "top_p" => 0.7,
                                      "stop_sequences" => ["\n\nHuman:"],
                                      "anthropic_version" => "bedrock-2023-05-31",
                                  ]),
            'modelId' => 'anthropic.claude-v2',
        ];

        $invocation_params["accept"] = "*/*";

        $response = $bedrock->invokeModelWithResponseStream($invocation_params);
        Log::debug('Full response body:', ['response' => $response['body']]);
        Log::debug('Type of response body:', ['type' => get_class($response['body'])]);

        $errors = 0;
        foreach ($response['body'] as $event) { // Error occurs here on the first iteration
            Log::debug('Current event:', ['event' => $event]); // This log message never runs

            if (isset($event['chunk'])) {
                $stream([], $event['chunk']);
            } else {
                $errors++;
                if ($errors > 10) {
                    break;
                }
            }
        }

        return true;
```

### Additional Information/Context

`invokeModel` works without streaming.

### SDK version used

3.285.1

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.1, Ubuntu, Laravel 10

**Comment by yenfryherrerafeliz** [comment] 2023-11-13 16:06
Hi @prattcmp, sorry to hear about your issues. I was able to reproduce the error that you have reported. I will add a needs-review label here to further address this issue.

Thanks!

**Comment by prattcmp** [comment] 2023-11-13 17:15
Thanks! This is blocking us from using Bedrock for streaming.

**Comment by yenfryherrerafeliz** [comment] 2023-11-15 18:28
@prattcmp we are working on providing a fix as soon as possible to this. 

Thanks!

**Comment by YujiroTakahashi** [comment] 2023-11-20 07:43
I tested the revised content with the following code. 
It waits for completion just like the invokeModel() function.  
Would asynchronous processing be required separately?

```php
<?php

include '/opt/vendor/autoload.php';

use Aws\BedrockRuntime\BedrockRuntimeClient;

$apiClient = new BedrockRuntimeClient([
    'region'  => 'us-east-1',
]);
$payload = [
    'modelId' => 'anthropic.claude-v2',
    'contentType' => 'application/json',
    'accept' => '*/*',
    'body' => json_encode([
        'prompt'=> "\n\nHuman: Please give me a PHP sample using BedrockRuntimeClient. \n\nAssistant:",
        'max_tokens_to_sample'=> 1024,
        'temperature'=> 1.0,
        'top_k'=> 100,
        'top_p'=> 0.9,
        'stop_sequences'=> [
          "\n\nHuman:"
        ],
        'anthropic_version'=> 'bedrock-2023-05-31',
    ]),
];

$result = $apiClient->invokeModelWithResponseStream($payload);
foreach ($result['body'] as $event) {
    if (isset($event['chunk'])) {
        $chunk = json_decode($event['chunk']['bytes']->getContents(), true);
        $data = json_decode(base64_decode($chunk['bytes']), true);
        ob_start();
        print_r($data);
        ob_end_flush();
        flush();
    }
}

```

```php
<?php

include '/opt/vendor/autoload.php';

use Aws\BedrockRuntime\BedrockRuntimeClient;

$apiClient = new BedrockRuntimeClient([
    'region'  => 'us-east-1',
]);
$payload = [
    'modelId' => 'anthropic.claude-v2',
    'contentType' => 'application/json',
    'accept' => '*/*',
    'body' => json_encode([
        'prompt'=> "\n\nHuman: Please give me a PHP sample using BedrockRuntimeClient. \n\nAssistant:",
        'max_tokens_to_sample'=> 1024,
        'temperature'=> 1.0,
        'top_k'=> 100,
        'top_p'=> 0.9,
        'stop_sequences'=> [
          "\n\nHuman:"
        ],
        'anthropic_version'=> 'bedrock-2023-05-31',
    ]),
];
$promise = $apiClient->invokeModelWithResponseStreamAsync($payload)->then(
    function ($result) {
        foreach ($result['body'] as $event) {
            if (isset($event['chunk'])) {
                $chunk = json_decode($event['chunk']['bytes']->getContents(), true);
                $data = json_decode(base64_decode($chunk['bytes']), true);
                ob_start();
                print_r($data);
                ob_end_flush();
                flush();
            }
        }
    },
    function ($result) {
        echo "Failed: " . $result;
    }
);
$promise->wait();
```

```
$ php stream.php
Array
(
    [completion] =>  Here
    [stop_reason] => 
    [stop] => 
)
Array
(
    [completion] =>  is a simple PHP code snippet using the BedrockRuntimeClient
    [stop_reason] => 
    [stop] => 
)
Array
(
    [completion] =>  to invoke a bedrock function:

` ` ` php
<?
    [stop_reason] => 
    [stop] => 
)
Array
(
    [completion] => php

use Bedrock\Runtime\
    [stop_reason] => 
    [stop] => 
)
Array
(
    [completion] => BedrockRuntimeClient;

$client = new Bedrock
    [stop_reason] => 
    [stop] => 
)
Array
(
    [completion] => RuntimeClient('https://bedrock.example.com'); 

$
    [stop_reason] => 
    [stop] => 
)
Array
(
    [completion] => request = [
    'moduleName
    [stop_reason] => 
    [stop] => 
)
Array
(
    [completion] => ' => 'myModule',
    'methodName' => 'helloWorld
    [stop_reason] => 
    [stop] => 
)
Array
(
    [completion] => ',
    'params'
    [stop_reason] => 
    [stop] => 
)
Array
(
    [completion] =>  => ['name' => 'John']
];

$response = $client->invoke
    [stop_reason] => 
    [stop] => 
)
Array
(
    [completion] => ($request);

print_r($response);
` ` `

The
    [stop_reason] => 
    [stop] => 
)
Array
(
    [completion] =>  key steps are:

1. Create a BedrockRuntime
    [stop_reason] => 
    [stop] => 
)
Array
(
    [completion] => Client instance, passing the Bedrock
    [stop_reason] => 
    [stop] => 
)
Array
(
    [completion] =>  URL.

2. Create the request
    [stop_reason] => 
    [stop] => 
)
Array
(
    [completion] =>  data with the module name, method name and
    [stop_reason] => 
    [stop] => 
)
Array
(
    [completion] =>  parameters. 

3. Call the invoke() method on the client, passing
    [stop_reason] => 
    [stop] => 
)
Array
(
    [completion] =>  the request.

4. The response contains the result of calling the
    [stop_reason] => 
    [stop] => 
)
Array
(
    [completion] =>  bedrock function.

Let me know if you need any
    [stop_reason] => 
    [stop] => 
)
Array
(
    [completion] =>  clarification or have additional questions!
    [stop_reason] => stop_sequence
    [stop] => 

Human:
)
```

## SDK version used
3.287.0

## Environment details
```shell
$ php -v
PHP 8.1.2-1ubuntu2.14 (cli) (built: Aug 18 2023 11:41:11) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2-1ubuntu2.14, Copyright (c), by Zend Technologies
```

**Comment by yenfryherrerafeliz** [comment] 2023-11-20 15:49
Hi @YujiroTakahashi, I do not quite understand your inquire. Could you please elaborate more so I can better help you?

Thanks!

**Comment by YujiroTakahashi** [comment] 2023-11-20 16:24
@yenfryherrerafeliz , thank you.

I want to output characters little by little for each chunk.
However, when using invokeModelWithResponseStream, the output is not per chunk, but rather waits until the end and then outputs everything.

How can I output per chunk?

**Comment by YujiroTakahashi** [comment] 2023-11-21 03:25
@yenfryherrerafeliz , thank you.

I want to output characters little by little for each chunk sent from the API. 
I want to output the chunks sent from the API immediately.
I want to get data chunk by chunk from the API.

However, when using invokeModelWithResponseStream, the chunk data waits until the stop_sequence comes.  
What should I do to get data for each chunk?
I don't want to separate into chunks, I want to get data chunk by chunk before the stop_sequence.

**Comment by YujiroTakahashi** [comment] 2023-11-22 03:40
This is the code that I tested after making changes since submitting the pull request. 
I was unable to implement streaming as a client.

```php
<?php

include '/opt/vendor/autoload.php';

use Aws\BedrockRuntime\BedrockRuntimeClient;

$apiClient = new BedrockRuntimeClient([
    'region'  => 'us-east-1',
]);
$payload = [
    'modelId' => 'anthropic.claude-v2',
    'contentType' => 'application/json',
    'accept' => '*/*',
    'body' => json_encode([
        'prompt'=> "\n\nHuman: Please give me a PHP sample using BedrockRuntimeClient. \n\nAssistant:",
        'max_tokens_to_sample'=> 1024,
        'temperature'=> 1.0,
        'top_k'=> 100,
        'top_p'=> 0.9,
        'stop_sequences'=> [
          "\n\nHuman:"
        ],
        'anthropic_version'=> 'bedrock-2023-05-31',
    ]),
];

$result = $apiClient->invokeModelWithResponseStream($payload);
foreach ($result['body'] as $event) {
    if (isset($event['chunk'])) {
        $data = json_decode($event['chunk']['bytes'], true);
        ob_start();
        print_r($data);
        ob_end_flush();
        flush();
    }
}
```

```php
<?php

include '/opt/vendor/autoload.php';

use Aws\BedrockRuntime\BedrockRuntimeClient;

$apiClient = new BedrockRuntimeClient([
    'region'  => 'us-east-1',
]);
$payload = [
    'modelId' => 'anthropic.claude-v2',
    'contentType' => 'application/json',
    'accept' => '*/*',
    'body' => json_encode([
        'prompt'=> "\n\nHuman: Please give me a PHP sample using BedrockRuntimeClient. \n\nAssistant:",
        'max_tokens_to_sample'=> 1024,
        'temperature'=> 1.0,
        'top_k'=> 100,
        'top_p'=> 0.9,
        'stop_sequences'=> [
          "\n\nHuman:"
        ],
        'anthropic_version'=> 'bedrock-2023-05-31',
    ]),
];
$promise = $apiClient->invokeModelWithResponseStreamAsync($payload);
$promise->then(
    function ($result) use ($promise) {
        foreach ($result['body'] as $event) {
            if (isset($event['chunk'])) {
                $data = json_decode($event['chunk']['bytes'], true);
                ob_start();
                print_r($data);
                ob_end_flush();
                flush();
            }
        }
        $promise->wait();
    },
    function ($reason) {
        echo "Failed: " . $reason;
    }
);
$promise->wait();
```

**Comment by yenfryherrerafeliz** [comment] 2023-11-22 16:25
Hi @YujiroTakahashi, the following [PR](https://github.com/aws/aws-sdk-php/pull/2829), which aims to fix the issue with the streaming operations, is still under review, which means is not merged yet in our code base. We are working on getting this merged as soon as possible. I will post a message in this issue once that is completed.

Thanks!

**Comment by stobrien89** [comment] 2023-12-12 20:38
Hi @prattcmp, @YujiroTakahashi,

https://github.com/aws/aws-sdk-php/pull/2829 has been merged and is available in the latest release. Can you give this a try now and let us know whether or not you're still having issues?

**Comment by YujiroTakahashi** [comment] 2023-12-13 07:32
Hi @stobrien89 ,

I verified using version 3.293.9. 
I stepped through using xdebug.
As a result, the following seem to be issues:

https://github.com/aws/aws-sdk-php/blob/master/src/IdempotencyTokenMiddleware.php#L38
https://github.com/aws/aws-sdk-php/blob/master/src/AwsClient.php#L309

https://github.com/aws/aws-sdk-php/blob/master/src/AwsClientTrait.php#L58
https://github.com/aws/aws-sdk-php/blob/master/src/AwsClientTrait.php#L63-L64


Arguments have become required when instantiating Guzzle::Promise.
https://github.com/guzzle/promises/blob/2.0/src/Promise.php#L27

Since a callback is not set here, it will always wait until all results have been returned.
With aws-sdk-js, it is possible to get data each time a chunk is received.

**Comment by yenfryherrerafeliz** [comment] 2023-12-14 04:48
Hi @YujiroTakahashi, we have addressed the issue that was originally reported here, which was related to the event parsing iterator not being able to correctly handle the responses gotten from the service. For this new inconvenient that you are experiencing, could you please open a separated issue. Could you also provide an example for how you do this with JS as you mentioned? so we can better understand your inquire.

Thanks!

**Comment by prattcmp** [comment] 2023-12-15 17:53
Everything appears to be working. Thank you!

**Comment by yenfryherrerafeliz** [comment] 2023-12-15 20:32
Closing for now. Please feel free of opening a new issue in case there is something else we can help with.

Thanks!

**Closed by yenfryherrerafeliz** 2023-12-15 20:32 UTC
Labels: closing-soon, p1
