### ISSUE TITLE
Guzzle - Monolog issue

### ISSUE THREAD

**Issue by dpgover** [aws/aws-sdk-php#939] opened 2016-03-28 14:13 UTC
Sorry in advance if this is not for this package, but I'm struggling with this issue.

I have this:
`PHP Warning:  Invalid callback Monolog\Handler\StreamHandler::customErrorHandler, cannot access private method Monolog\Handler\StreamHandler::customErrorHandler() in {..}/vendor/aws/aws-sdk-php/src/Handler/GuzzleV5/GuzzleHandler.php on line 81
PHP Catchable fatal error:  Argument 1 passed to Aws\Handler\GuzzleV5\GuzzleHandler::Aws\Handler\GuzzleV5\{closure}() must be an instance of Exception, string given, called in {..}/vendor/guzzlehttp/promises/src/Promise.php on line 199 and defined in {..}/vendor/aws/aws-sdk-php/src/Handler/GuzzleV5/GuzzleHandler.php on line 81`

and this:
`PHP Warning:  Invalid callback Monolog\Handler\StreamHandler::customErrorHandler, cannot access private method Monolog\Handler\StreamHandler::customErrorHandler() in {...}/vendor/aws/aws-sdk-php/src/S3/StreamWrapper.php on line 737
PHP Warning:  The promise was rejected with reason: Invoking the wait callback did not resolve the promise in {...}/vendor/aws/aws-sdk-php/src/S3/StreamWrapper.php on line 737`

Is this a bug with the library? Is this a bug on guzzle? Or maybe it's a bug/incompatibility with the combination of all the libraries?

thanks

**Comment by cjyclaire** [comment] 2016-03-29 19:14
Could you tell more about when is this happening actually? Did you look into what is the argument that pass in to GuzzleHandler that cause the error?

**Comment by dpgover** [comment] 2016-03-30 15:32
Not really, sorry.
I have a queue running that reads a file from S3. I supposed that sometimes that reading fails and "someone" tries to write the fail to a log... That's the only thing I know and I cant reproduce it manually. :disappointed:

**Comment by cjyclaire** [comment] 2016-03-30 22:40
Does this happens every time when reading fails? Are these all the errors that appears when reading fails? Could you somehow trace that exception to where it actually happens perhaps?

**Comment by jeskew** [comment] 2016-04-04 19:35
@dpgover Are you using the stream wrapper to write log messages to an object in S3? This may be a bug in the Guzzle V5 handler, but there's isn't enough information to determine if it is one (and if so how to reproduce and fix it).

**Comment by dpgover** [comment] 2016-04-04 19:39
That's correct. I'm using the stream wrapper to write log messages to a file in S3.
I know there's a lot of information missing about the problem. But I cannot reproduce it outside the production servers... and the error log has only the information I wrote on the issue :disappointed:

**Comment by jeskew** [comment] 2016-04-22 21:33
I think the root cause of the error is the first warning in the message `Invalid callback Monolog\Handler\StreamHandler::customErrorHandler, cannot access private method Monolog\Handler\StreamHandler::customErrorHandler()`.

Are you at any point explicitly rejecting any promises? This might also be done by a third-party library.

**Comment by jeskew** [comment] 2016-05-03 20:33
I'm going to go ahead and close this issue, as it does not appear to be a bug in the SDK. Please feel free to update or reopen if you get more information or if you have any questions or concerns.

**Closed by jeskew** 2016-05-03 20:33 UTC
