### ISSUE TITLE
DynamoDB session handling doesn't work in Elastic Beanstalk environment

### ISSUE THREAD

**Issue by vanzay** [aws/aws-sdk-php#1292] opened 2017-05-21 14:34 UTC
Hello!

I use this example https://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/dynamodb-session-handler.html

When I run my app locally it works fine. And I see a session ID in the AWS Console for Amazon DynamoDB.
But when I open my app in the Elastic Beanstalk environment it doesn't work. A session doesn't appear in DynamoDB.

**Comment by imshashank** [comment] 2017-05-22 22:46
@vanzay Sorry that you had to face this issue. Please help us better understand the error. 

It will be helpful if you can share your error stack & code snippet so that we can reproduce the issue on our end.

**Comment by vanzay** [comment] 2017-05-23 15:47
Here is some logs from the server:
> [Tue May 23 10:09:28.805533 2017] [:error] [pid 23435] [client 172.31.28.194:54830] PHP Warning:  Error writing session PHPSESSID_2pae278kvbh86v61a9upueone4: Error executing "UpdateItem" on "https://dynamodb.eu-central-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://dynamodb.eu-central-1.amazonaws.com` resulted in a `400 Bad Request` response:\n{"__type":"com.amazon.coral.service#AccessDeniedException","Message":"User: arn:aws:sts::314382625344:assumed-role/aws-e (truncated...)\n AccessDeniedException (client): User: arn:aws:sts::314382625344:assumed-role/aws-elasticbeanstalk-ec2-role/i-0d1204078bf4e29eb is not authorized to perform: dynamodb:UpdateItem on resource: arn:aws:dynamodb:eu-central-1:314382625344:table/sessions - {"__type":"com.amazon.coral.service#AccessDeniedException","Message":"User: arn:aws:sts::314382625344:assumed-role/aws-elasticbeanstalk-ec2-role/i-0d1204078bf4e29eb is not authorized to perform: dynamodb:UpdateItem on resource: arn:aws:dynamodb:eu-central-1:314382625344:table/sessions"} in /var/app/current/vendor/aws/aws-sdk-php/src/DynamoDb/StandardSessionConnection.php on line 145

It seems that app doesn't have permissions to write data to DynamoDB from Elastic Beanstalk environment.

**Comment by vanzay** [comment] 2017-05-23 15:56
I've attached AmazonDynamoDBFullAccess policy to aws-elasticbeanstalk-ec2-role and it works now.
Thanks.

**Comment by kstich** [comment] 2017-05-23 15:58
@vanzay Glad you were able to solve the problem! Since this isn't an issue with the SDK itself, we're closing the issue.

**Closed by kstich** 2017-05-23 15:58 UTC
Labels: awaiting-reply, usage-question

**Comment by PedroReichert** [comment] 2023-03-14 10:24
Greetings!
I'm having the same problem.
Funny thing is that the same code used to work on 13/01/2023.
Now I'm getting:

`AccessDeniedException (client): User: arn:aws:sts::XXXXXXXXX:assumed-role/components-asg-ecs-instance-role/i-0fd06b98a51c6b502 is not authorized to perform: dynamodb:PutItem on resource: arn:aws:dynamodb:eu-west-3:XXXXXXXXXX:table/dagobah-outbound-transactions-dev because no identity-based policy allows the dynamodb:PutItem action - {"__type":"com.amazon.coral.service#AccessDeniedException","Message":"User: arn:aws:sts::XXXXXXXXXX:assumed-role/components-asg-ecs-instance-role/i-0fd06b98a51c6b502 is not authorized to perform: dynamodb:PutItem on resource: arn:aws:dynamodb:eu-west-3:XXXXXXXXX:table/dagobah-outbound-transactions-dev because no identity-based policy allows the dynamodb:PutItem action"}`

The policy vinculated to the task allows everything to dynamo, but it looks like is getting the wrong role.
I have a SQS service implemented that works on the same principal, and it's working! Meaning is something to do with the DynamoDbClient authetication.
