### ISSUE TITLE
Error executing "HeadBucket" with v3 SDK

### ISSUE THREAD

**Issue by mdevine82** [aws/aws-sdk-php#1065] opened 2016-08-08 13:18 UTC
So I'm having an issue with moving my code from using an old version of the SDK to the latest v3. When I run through the following code, it fails with the following error:

_Error executing "HeadBucket" on "https://s3.amazonaws.com/My_Bucket_Name"; AWS HTTP error: Client error: `HEAD https://s3.amazonaws.com/My_Bucket_Name` resulted in a `403 Forbidden` response: (client): 403 Forbidden (Request-ID: 4471096CBF8C37F2)_

Here is the code I'm using, any help would be appreciated. I've boiled it down to a simple example.

```
$s3Client = new Aws\S3\S3MultiRegionClient([
        'version'     => 'latest',
        'region'      => 'us-east-1',
        'credentials' => [
            'key'    => MY KEY,
            'secret' => MY SECRET,
        ],
    ]);
 
    $bucket = My_Bucket_Name;
    $region = $s3Client->determineBucketRegion($bucket);
 
    $response = $s3Client->putObject([
        'Body' => '12345',
        'Bucket' => $bucket,
        'Key' => rand(1,10000) . '.txt',
        '@region' => $region
    ]);
```

I also posted this on the forums but didn't get a response, so I just wanted to mirror that post here which I'll also do on the flip side when we figure it out.

https://forums.aws.amazon.com/message.jspa?messageID=734219

**Comment by cjyclaire** [comment] 2016-08-08 17:39
@mdevine82 , in using `Aws\S3\S3MultiRegionClient`, you don't have to include `region` parameter in constructing the client. 

More docs about [`S3MultiRegionClient`](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-multiregion-client.html).

**Comment by mdevine82** [comment] 2016-08-08 17:53
Alright, so if I remove the region altogether from both the constructor and the putObject.  Will it do the lookup automatically and store in that internal cache?

**Comment by cjyclaire** [comment] 2016-08-08 18:13
@mdevine82 In caching the regions, you need to do something like:
```
use Aws\DoctrineCacheAdapter;
use Aws\Sdk;
use Doctrine\Common\Cache\ApcuCache;

$sdk = new Aws\Sdk([
    'version' => 'latest',
    'region' => 'us-east-1',
    'S3' => [
        'bucket_region_cache' => new DoctrineCacheAdapter(new ApcuCache),
    ],
]);
```

**Comment by cjyclaire** [comment] 2016-08-08 18:14
@mdevine82 S3 multi-region clients maintain an internal cache of the regions in which given buckets reside. By default, each client has its own in-memory cache. 
To share a cache between clients or processes, supply an instance of Aws\CacheInterface as the bucket_region_cache option to your multi-region client. [doc](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-multiregion-client.html#bucket-region-cache)

**Comment by mdevine82** [comment] 2016-08-08 18:38
I simply want to know that if I don't supply the region to any calls it will do the lookup itself.  So removing the region parameter from the **S3MultiRegionClient** and  **putObject** it will automatically do the lookup itself?

**Comment by cjyclaire** [comment] 2016-08-08 18:42
@mdevine82 Yes, it will.

**Comment by mdevine82** [comment] 2016-08-08 19:21
Great thanks, I'll run some tests and confirm it all works and then close this out.

**Comment by mdevine82** [comment] 2016-08-08 20:03
Now when I try to get a presigned URL it tosses a 403 Forbidden.  It seems like I'm so close but missing one thing.  I just used the code example here for the [preSigned](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-presigned-url.html)

This came off a putObject request that had worked with the changes you requested.

```
$cmd = $s3Client->getCommand('GetObject', [
			'Bucket' => $bucket,
			'Key'    => $url
		]);

		$request = $s3Client->createPresignedRequest($cmd, '+30 seconds');
```

**Comment by cjyclaire** [comment] 2016-08-08 20:34
@mdevine82 I couldn't reproduce the issue, here is the code when I trying to reproduce:
```
$s3Client = new Aws\S3\S3MultiRegionClient([
     'version'     => 'latest',
]);

$bucket = 's3-bucket-sandbox-test';
$region = $s3Client->determineBucketRegion($bucket);

try {
    $key = rand(1,10000) . '.txt';
    $response = $s3Client->putObject([
        'Body' => '12345',
        'Bucket' => $bucket,
        'Key' => $key,
        '@region' => $region
    ]);
    var_dump($response);
    
    $cmd = $s3Client->getCommand('GetObject', [
        'Bucket' => $bucket,
        'Key' => $key,
    ]);
    $request = $s3Client->createPresignedRequest($cmd, '+30 seconds');
    $presignedUrl = (string) $request->getUri();
    var_dump($presignedUrl);

} catch (\Aws\S3\Exception\S3Exception $e) {
    echo $e->getMessage();
}
```

It produces correct response and signed URL. Then with the signed URL, file could be retrieved correctly.

**Comment by mdevine82** [comment] 2016-08-09 14:30
Is there somewhere else I should post to look into why I'm getting a 403 even with your code on the **createPresignedRequest()** call.  I will also note that it still gives a 403 on the **determineBucketRegion()** call.  So if I remove that it actually succeeds on the **putObject**.

It seems like some sort of permissions issue but the credentials being used have full permissions

```
{
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": "*"
        }
    ]
}
```

Thanks for your help on this.

**Comment by cjyclaire** [comment] 2016-08-09 17:24
@mdevine82 Interesting, so in terms of `determineBucketRegion()`, it actually makes a `HeadBucket` request to determine the bucket region. Could you double check the bucket permission in used?

Asking on the AWS forum is how you could talk with service team directly(It seems like you already do so).

**Comment by mdevine82** [comment] 2016-08-10 13:12
Currently working with AWS Support, I've sent them the wire logs to find out what the issue is.  I'll post the resolution, to hopefully help someone else.

**Comment by mdevine82** [comment] 2016-08-11 15:46
So I'm back with some new information based on some digging with the guys over at support.

After I sent in the wire logs I got the following response back from them
> I can see that the x-amz-security-token header is being provided in the HTTP request, but I don't see the authentication header. This also explains why the server side logs show that the request came in unauthenticated.

They had me try putting the credentials into a environment variable but that didn't work.  From there I put a breakpoint into the SDK code around the CredentialProvider::env() function.  I noticed that it never ended up in here when running the following.

```
$region = $s3Client->determineBucketRegion($bucket);
```

The support person also suggested using **getBucketLocation($args)** instead and with that I noticed that the following would actually go into CredentialProvider and work correctly.

```
$region = $s3Client->getBucketLocation(['Bucket' => $bucket]);
```

Let me know what you think and if there is anything you want me to send.

**Comment by cjyclaire** [comment] 2016-08-11 17:26
@mdevine82 , thanks for getting back, it looks like a [credential](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/credentials.html) problem. At first I thought the hard-code credential configuration in code snippet is shown as testing purpose, I should have mentioned better credential practices(env, profile, IAM etc.).

`determineBucketRegion` is a PHP SDK customized method and `getBucketLocation` is a standard S3 API, I'll try to reproduce your case to see if `determineBucketRegion` doesn't catch credentials in the first place.

**Comment by cjyclaire** [comment] 2016-08-11 20:25
@mdevine82 I couldn't produce issue when trying to handle credential with environment variables or hard coded credentials with both method. If no credentials provided, `Aws\Exception\CredentialsException` is thrown.

In looking into the `CredentialProvider` being used, you could call `$s3Client->getCredentials()`, if there is problem with your credentials, Exception should be thrown.

**Comment by mdevine82** [comment] 2016-08-12 13:06
Well the strange part about it was no matter how I had the credentials input `determineBucketRegion()` would always fail and `getBucketLocation()` would always succeed.  This means if they were hardcoded or setup via environment variable.  While `$s3Client->getCredentials()`, would succeed in both instances of returning the FulfilledPromise.

**Comment by cjyclaire** [comment] 2016-08-15 17:46
@mdevine82 That's weird, apology for this late reply, yet is there still trouble with `determineBucketRegion()` even with correct credentials? Could you provide some console output here so that I could see what might go wrong?

Having `'debug' => true` in client configuration and using `determineBucketRegion`, what's the `getCredential()` output and the wire log output? Also it would be nice if you could provide error message again to see if anything changes and double check that it's `determineBucketRegion` causing the trouble.

**Comment by mdevine82** [comment] 2016-08-15 20:39
Here is the output from both calls, I removed the actual credentials from the top but both of them were identical:
 [GetBucketLocation](https://gist.github.com/mdevine82/abc4238fd6a84b0e3f2e90ab06c8ccac)

[determineBucketRegion](https://gist.github.com/mdevine82/3624f53ee637e4ad0ef7a8b0e4892aca)

**Comment by cjyclaire** [comment] 2016-08-15 23:15
@mdevine82 Could you try to update your CA bundle and make sure that it lives in correct location? Instructions can be found [here](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/faq.html#what-do-i-do-about-a-curl-ssl-certificate-error). 
From the wire log, both shows that `Hostname in DNS cache was stale` and
 `none CApath: /etc/ssl/certs * SSL connection using ECDHE-RSA-AES128-GCM-SHA256`. 

This didn't trigger an error for `getBucketLocation` because it's a standard S3 API call with `GET`, which means it has complete life cycle containing `'signer'` step that uses AWS Signature V4. 

Yet in `determineBucketRegion`, `'signer'` is [removed](https://github.com/aws/aws-sdk-php/blob/master/src/S3/S3ClientTrait.php#L166) from `handlerList` due to performance concerns, in this way, certification fails to SSL CA bundles sole with cURL (where `resolve()` depends on). That's why `HTTP/1.1 403 Forbidden` is [exposed](https://gist.github.com/mdevine82/3624f53ee637e4ad0ef7a8b0e4892aca#file-determinebucketregion-L49).

Hope this helps.

**Comment by mdevine82** [comment] 2016-08-16 13:36
Updated there CA cert bundle didn't change anything along with hardcoding the `openssl.cafile = /etc/ssl/certs/cacert.pem` parameter in my php.ini file.  I wish we could figure out what's going on with it but by this time we already have worked around the issue and don't need to use the `S3MultiRegionClient()` anymore.  I was just trying to see if I could help you resolve the issue.

If you want to ask any additional questions or things for me to try, I'm game.

**Comment by cjyclaire** [comment] 2016-09-27 17:23
Ping here, the PR contain the fix just merged, will be tagged in our release today.

**Closed by cjyclaire** 2016-09-27 17:23 UTC
Labels: PR-under-review
