### ISSUE TITLE
Facing Issue on Route 53 Subdomain creation

### ISSUE THREAD

**Issue by NowshadRuhan** [aws/aws-sdk-php#2605] opened 2022-12-20 18:24 UTC
### Describe the bug

We are facing a problem with subdomain creation using PHP Codeigniter 3 Framework. 

Error showing 

```
`An uncaught Exception was encountered
Type: Aws\Route53\Exception\Route53Exception

Message: Error executing "ChangeResourceRecordSets" on "https://route53.amazonaws.com/2013-04-01/hostedzone/Z012491213OH9Z40OQHQ8/rrset/"; AWS HTTP error: cURL error 7: Failed to connect to route53.amazonaws.com port 443: Connection timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

Filename: /opt/lampp/htdocs/signup/awsSiteBuilder/Aws/WrappedHttpHandler.php

Line Number: 195`
```

### Where I use code below:

`        $result = $client->changeResourceRecordSets(array(
            // HostedZoneId is required
            
            // ChangeBatch is required
            'ChangeBatch' => array(
                // Changes is required
                'Changes' => array(
                    array(
                        // Action is required
                        'Action' => 'CREATE',
                        // ResourceRecordSet is required
                        'ResourceRecordSet' => array(
                            // Name is required
                            'Name' => 'example.aws.com',
                            // Type is required
                            'Type' => 'A',

                            "AliasTarget"=> array(
                              "DNSName"=> "*****-******.us-east-1.elb.amazonaws.com",
                              "HostedZoneId"=> "Z35S******Q7X7K",
                              "EvaluateTargetHealth"=> false 
                            ), 
                        ),
                    ),
                ),

            ),
            'HostedZoneId' => 'Z0124********40OQHQ8',
        ));
`

### Expected Behavior

Want to create subdomain on route 53.

### Current Behavior

Showing error.

### Reproduction Steps

`   $result = $client->changeResourceRecordSets(array(
            // HostedZoneId is required
            
            // ChangeBatch is required
            'ChangeBatch' => array(
                // Changes is required
                'Changes' => array(
                    array(
                        // Action is required
                        'Action' => 'CREATE',
                        // ResourceRecordSet is required
                        'ResourceRecordSet' => array(
                            // Name is required
                            'Name' => 'example.aws.com',
                            // Type is required
                            'Type' => 'A',

                            "AliasTarget"=> array(
                              "DNSName"=> "*****-******.us-east-1.elb.amazonaws.com",
                              "HostedZoneId"=> "Z35S******Q7X7K",
                              "EvaluateTargetHealth"=> false 
                            ), 
                        ),
                    ),
                ),

            ),
            'HostedZoneId' => 'Z0124********40OQHQ8',
        ));`

### SDK version used

PHP V2

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 7.4

**Comment by stobrien89** [comment] 2022-12-20 22:08
Hi @NowshadRuhan,

I'm unable to reproduce this on V3.  V2 has been deprecated for some time now.  It does look like you're getting a correctly modeled endpoint, so I'd suspect a network issue on your end.  

We haven't supported V2 for a while now and recommend you upgrade to V3 whenever possible.  Closing for now, but let us know if you have any additional questions!

**Closed by stobrien89** 2022-12-20 22:08 UTC
Labels: bug, needs-triage
