### ISSUE TITLE
ConfigurationProvider.php warning when open_basedir is turned on

### ISSUE THREAD

**Issue by blacksaildivision** [aws/aws-sdk-php#1659] opened 2018-10-25 12:50 UTC
Hi there,
I upgraded SDK version from `3.68.1` to `3.69.13` version. When trying to use S3Client I get warning from `ConfigurationProvider` class:
```
Warning: is_readable(): open_basedir restriction in effect. File(/home/xxxx/.aws/config) is not within the allowed path(s): (/var/www/htdocs:/tmp) in /var/www/htdocs/vendor/aws/aws-sdk-php/src/ClientSideMonitoring/ConfigurationProvider.php on line 232
```
I have `open_basedir` turned on in PHP configuration limited to app root and /tmp directory. 
Client initialization looks like this:
```php
    $s3Client = new S3Client([
        'version' => 'latest',
        'region' => 'eu-central-1',
        'credentials' => [
            'key' => AWS_ACCESS_KEY_ID,
            'secret' => AWS_SECRET_ACCESS_KEY
        ],
    ]);
```
Is there any way to avoid checking if path is readable for directories outside `open_basedir` list?

**Comment by diehlaws** [comment] 2018-10-25 21:07
Hi @blacksaildivision, thanks for reaching out to us. Is there a particular reason your `~/.aws/` directory cannot be added to `open_basedir` in your PHP config? That would be the easiest way to resolve this. 

If your use case does not support this approach, another way to resolve this would be to set your `$HOME` environment variable in the session in which your application is running to a directory inside of the paths you've specified in `open_basedir` so that the SDK looks for `.aws/config` in a path that can be accessed by PHP in your application.

**Comment by diehlaws** [comment] 2018-10-31 23:48
In this case it is not `S3Client` that's trying to read `.aws/config` but a different package instead. We want the SDK to check the config file for any options that aren't otherwise specified in code, however you can override this behavior by setting the environment variable `AWS_CSM_ENABLED` to `false`.

**Comment by Finesse** [comment] 2018-11-20 11:29
I don't like that I can't set the client side monitoring (CSM) settings through the code too. I don't want my application to read something beyond its directory because I don't want an implicit data flow so I won't add the home directory to the open_basedir.

Luckily there are a few ways to disable CSM using only the application source code:

- Add the following line of code before creating the `S3Client` object:

    ```php
    putenv('AWS_CSM_ENABLED=false');
    ```

- Give the `S3Client` constructor a fake CSM cache mock which returns what you want without scanning the disk:

    ```php
    $s3Client = new Aws\S3\S3Client([
        // ...
        'csm' => new class implements Aws\CommandInterface {
            public function get($key) {
                return new Aws\ClientSideMonitoring\Configuration(false, 0); // Your configuration here
            }
            public function set($key, $value, $ttl = 0) {}
            public function remove($key) {}
        }
    ]);
    ```

    This is a dirty way but has no side effects.

**Comment by JorisDebonnet** [comment] 2019-06-14 00:56
@diehlaws, I don't agree that this is merely a _guidance_ issue or that it should be closed. I was just approached by a client telling me they can't upload files anymore. How can it be considered acceptable that this can just happen from one day to the next? Updates as mentioned in the OP should be backwards compatible. We shouldn't need to update our code to work around some behavior that was added in this plugin. This is still an issue in 3.100.3.

I used Finesse's workaround now, but don't like having to do that...
Happy to help debugging so that we can skip the workaround.

**Comment by diehlaws** [comment] 2019-06-14 19:30
Thanks for the feedback on this @Finesse, @JorisDebonnet, and @blacksaildivision. I'm re-opening the issue and marking it as a feature request, and will bring up disabling client-side monitoring via a config option for service clients in addition to the existing environment variable `AWS_CSM_ENABLED` to the rest of the team in our next sprint.

**Comment by Finesse** [comment] 2019-06-19 23:49
The issue is not resolved. There is still no straight way to disable the CSM, and the SDK tries to read the home directory if the CSM is not disabled using the tricks I described above.

**Comment by srchase** [comment] 2019-06-19 23:51
@Finesse 

I apologize.  This was tagged by mistake.

**Closed** 2019-07-01 22:48 UTC
Labels: feature-request

**Comment by howardlopez** [comment] 2019-07-01 22:52
#1834 added support for a client `csm` option that you can use to disable client-side monitoring and override the normal config provider chain, thereby avoiding the file system. For example:

```
$client = new S3Client([
    'region' => 'us-east-1',
    'version' => 'latest',
    'csm' => false
]);
```

This has been merged to master and will be included in the next release.
