### ISSUE TITLE
compatibility with localstack broke

### ISSUE THREAD

**Issue by luismontreal** [aws/aws-sdk-php#1315] opened 2017-06-28 17:08 UTC
Starting in version 3.28.0, the SDK doesn't retrieve messages from SQS in localstack

https://bitbucket.org/atlassian/localstack

$this->sqsClient->receiveMessage

only return the @metadata, the "Messages" key is missing

**Comment by kstich** [comment] 2017-06-28 17:18
@luismontreal Thanks for bringing this to our attention. There were no changes explicit to SQS in [version 3.28.0](https://github.com/aws/aws-sdk-php/releases/tag/3.28.0). [Version 3.28.1 brought verification of `MessageAttributes`](https://github.com/aws/aws-sdk-php/releases/tag/3.28.1) but will throw an exception if not valid.

Can you please provide the versions of PHP and the SDK that you are using, as well as some sample code and a sample response? I'd also recommend reaching out to the localstack team to see if something changed on their end.

**Comment by luismontreal** [comment] 2017-06-28 18:44
Many thanks for your quick reply, you were right, I got the exception now from 3.28.1

Aws\Sqs\Exception\SqsException: Attribute MD5 mismatch. Expected d41d8cd98f00b204e9800998ecf8427e, found No Attributes in /var/www/html/playground/vendor/aws/aws-sdk-php/src/Sqs/SqsClient.php on line 215

For some reason localstack always returns an MD5 of the message attributes even when I send no attributes (I'll talk to them)

example:  
[vagrant@localhost localstack]$ aws --profil local sqs send-message --queue-url http://localhost:4576/Development-Luis --message-body  'my message' --endpoint-url=http://localhost:4576

Response:
{
    "MD5OfMessageBody": "3c9d24df935626c2a7eb6ae2e483cf32", 
    "MD5OfMessageAttributes": "d41d8cd98f00b204e9800998ecf8427e", 
    "MessageId": "a47c2ba2-bd04-442b-9423-b0d468b54ced"
}

**Comment by ingluisjimenez** [comment] 2017-06-28 18:54
We are running through the same issue.

@kstich the issue is with the validation of the message attributes. When there are no message attributes, localstack returns the md5 hash for an empty string, which is "d41d8cd98f00b204e9800998ecf8427e", but the calculateMessageAttributesMd5() method in the SqsClient class returns null, as there are no message attributes, so the hash doesn't match null.

I'd say the issue should be fixed in the localstack side, as it should not be sending back `MD5OfMessageAttributes` when there are no attributes being sent.

**Comment by ingluisjimenez** [comment] 2017-06-28 18:58
returning `md5('')` in this line fixed the issue for me https://github.com/aws/aws-sdk-php/blob/master/src/Sqs/SqsClient.php#L125

Not sure how do you want to handle this case.

**Comment by luismontreal** [comment] 2017-06-28 19:04
Thanks @ingluisjimenez  I agree this should be fixed on localstack's end.  amazon doesn't return md5 of empty string

**Comment by kstich** [comment] 2017-06-28 19:08
This is correct, the field `MD5OfMessageAttributes` does not exist on a `Message` if no attributes were set. I've also posted to the issue you created on the localstack repo.

<img width="620" alt="md5ofmessageattributes" src="https://user-images.githubusercontent.com/26905335/27655424-323dd918-5bfa-11e7-8812-2044e3e4e145.png">

**Closed by kstich** 2017-06-28 19:08 UTC
Labels: usage-question
