### ISSUE TITLE
GetObject to unexistent object retries in standard retry mode

### ISSUE THREAD

**Issue by yh1224** [aws/aws-sdk-php#2496] opened 2022-07-09 07:32 UTC
### Describe the bug

When I tried to GetObject by **standard** retry mode to unexistent object, it takes a little long time because it retries.

### Expected Behavior

It doesn't retry and make fail immediately.

### Current Behavior

It retries.

### Reproduction Steps

Run this code.

```php
$s3Client = new Aws\S3\S3Client([
    "region" => "ap-northeast-1",
    "version" => "2006-03-01",
    "retries" => [
        "mode" => "standard",
        "max_attempts" => 3,
    ],
]);
$res = $s3Client->getObject(["Bucket" => $bucket, "Key" => $key]);
```

### Additional Information/Context

It doesn't retry in **legacy** retry mode.

```php
$s3Client = new Aws\S3\S3Client([
    "region" => "ap-northeast-1",
    "version" => "2006-03-01",
    "retries" => [
        "mode" => "legacy",
        "max_attempts" => 3,
    ],
]);
$res = $s3Client->getObject(["Bucket" => $bucket, "Key" => $key]);
```

Also in standrad retry mode by Python implementation (boto3).

```python
client = boto3.client(
    "s3",
    config=Config(
        retries={
            "mode": "standard",
            "total_max_attempts": 3,
        }
    )
)
res = client.get_object(Bucket=bucket, Key=key)
```

### SDK version used

3.231.2

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 7.4.30 (cli) (built: Jun  9 2022 09:30:03) ( NTS )

**Comment by yenfryherrerafeliz** [comment] 2022-07-12 16:16
Hi @yh1224, thanks for reporting this. I was able to reproduce this behavior and currently I am investigating the root cause. In the meantime I will mark this issue to be reviewed. As soon as I get any resolution regarding I will use this thread to provide the updates.

Thanks!

**Comment by stobrien89** [comment] 2022-11-10 20:19
Hi @yh1224,

Apologies for the delay.  We will need debug logs to further investigate this.   You can enable debug logging by adding `'debug' => true'` to your client configuration.  Please provide us the result and redact any sensitive information, such as account numbers.  Thanks!

**Comment by stobrien89** [comment] 2023-05-09 21:16
Hi @yh1224,

Apologies for the delay here.  A fix has been merged and is available in the latest release.  Please let us know if you have any additional questions.

**Closed by stobrien89** 2023-05-09 21:16 UTC
Labels: bug, needs-review, p3
