### ISSUE TITLE
Cannot set the OutputKey when using starttranscriptionjob

### ISSUE THREAD

**Issue by samueleastdev** [aws/aws-sdk-php#2106] opened 2020-09-28 17:10 UTC
**Describe the bug**
Cannot set the OutputKey when using starttranscriptionjob

https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-transcribe-2017-10-26.html#starttranscriptionjob

If I set the output key path it still saves the file in the root of the bucket instead of the set output location.

Here are the params I am setting.
~~~
(
    [LanguageCode] => en-US
    [Media] => Array
        (
            [MediaFileUri] => s3://bbbb-storage/aws/workmail/setup.m4v
        )

    [MediaFormat] => mp4
    [OutputBucketName] => bbbb-storage
    [OutputKey] => aws/workmail/setup.json
    [TranscriptionJobName] => setup-5f720b081e325
)
~~~
**Version of AWS SDK for PHP?**
3.112.34

**Version of PHP (`php -v`)?**
PHP 7.3.11

**Comment by ajredniwja** [comment] 2020-10-03 23:09
Hey @samueleastdev Thanks for opening this issue, I was able to reproduce the issue and can confirm it is the issue with the PHP SDK, as I was able to run everything fine with the JS SDK, while I am not sure about the root cause, I will have someone from the team work on it ASAP.

**Comment by samueleastdev** [comment] 2020-10-05 12:34
Great thanks for the update ;)

**Comment by ajredniwja** [comment] 2020-10-13 22:43
Hey @samueleastdev I did a little bit of digging and found out that I ran my tests on 3.155.0 which gave me results that you are getting, the feature was introduced by Transcribe service in `3.155.2` as it can be seen [here](https://github.com/aws/aws-sdk-php/blob/master/CHANGELOG.md#31552---2020-09-24).

So upgrading your SDK to any version to 3.155.2 or after that should solve the problem. I have tested it with `3.158.6` and it works . 

Closing this now, please reach out if that doesn't solve the problem.

**Closed by ajredniwja** 2020-10-13 22:43 UTC
Labels: bug

**Comment by samueleastdev** [comment] 2020-10-14 00:26
Updated and working thanks for your time looking into this ;)
