### ISSUE TITLE
DynamoDb Local is unresponsive after setting Authorization headers 

### ISSUE THREAD

**Issue by remipelhate** [aws/aws-sdk-php#1102] opened 2016-10-11 14:52 UTC
I presume I must be doing something wrong, however I have absolutely no idea what. I'm trying to use DynamoDb Local in a Laravel (5.2.39) application.

**Setup**
I installed DynamoDb Local on my Vagrant box as explained in [this article](http://mr80.net/5/). I did skip the installation of NodeJS and the AWS CLI, though, as I won't need 'm. After the installation, I was able to run DynamoDb (using `java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb`) and use the web shell without any issues.

I added the following configuration to Laravel's `config/services.php` file:
```php
'aws' => [
   'dynamodb' => [
        'credentials' => [
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
        ],
        'region' => env('AWS_REGION'),
        'version' => env('AWS_VERSION', 'latest'),
        'endpoint' => env('AWS_ENDPOINT', 'http://localhost:8000'),
        'debug' => env('APP_DEBUG', false),
    ],
],
```
and registered the following provider in `config/app.php`:
```php
class DynamoDbServiceProvider extends ServiceProvider
{
    protected $defer = true;

    public function register()
    {
        $this->app->singleton(DynamoDbClient::class, function ($app) {
            return new DynamoDbClient($app['config']['services']['aws']['dynamodb']);
        });
    }

    public function provides()
    {
        return [
            DynamoDbClient::class,
        ];
    }
}
```

**Issue**
Whenever I use the `DynamoDbClient` to interact with DynamoDb (for example `$client->createTable([...])`), nothing happens. When enabling debug mode (in the configuration above), I can see it gets to:
````
-> Entering step sign, name 'signer'
------------------------------------

  request.instance changed from 00000000007bba1b000000001a646944 to 00000000007bba6e000000001a646944
  request.headers.X-Amz-Date was set to array(1) {
    [0]=>
    string(16) "20161011T135449Z"
  }
  
  request.headers.Authorization was set to array(1) {
    [0]=>
    string(245) "AWS4-HMAC-SHA256 Credential=[KEY]/20161011/eu-west-1/dynamodb/aws4_request, SignedHeaders=aws-sdk-invocation-id;aws-sdk-retry;host;x-amz-date;x-amz-target, Signature=[SIGNATURE]
  }
```
Though, nothing happens after that, there's no response whatsoever (not even in log files).

At first I thought it could be due to the fake credentials I'm using for my local environment. But using real credentials has the same result.

I also tried using `http://127.0.0.1:8000` as endpoint instead of `http://localhost:8000`, which doesn't work either.

I have tried turning it all on and off (DynamoDb Local, Vagrant and my Macbook) again as well :) I'm really, really running out of ideas...

**Comment by cjyclaire** [comment] 2016-10-11 17:23
@remipelhate Thanks for the information! I couldn't reproduce it locally with SDK solo, I doubt it might not be a SDK issue. So normally, in the signer step, after the "Enter" information, there should be something like:
```php
* Rebuilt URL to: http://localhost:8000/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8000 (#0)
> POST / HTTP/1.1
Host: localhost:8000
X-Amz-Target: DynamoDB_20120810.ListTables
Content-Type: application/x-amz-json-1.0
aws-sdk-invocation-id: cebc32d4b6af36db6e619d1099796a08
aws-sdk-retry: 0/0
X-Amz-Date: 20161011T171124Z
Authorization: AWS4-HMAC-SHA256 Credential=[KEY]/20161011/us-west-2/dynamodb/aws4_request, SignedHeaders=aws-sdk-invocation-id;aws-sdk-retry;host;x-amz-date;x-amz-target, Signature=[SIGNATURE]
User-Agent: aws-sdk-php/3.19.11 GuzzleHttp/6.2.1 curl/7.50.3 PHP/7.0.11
Content-Length: 2

* upload completely sent off: 2 out of 2 bytes
< HTTP/1.1 200 OK
< Content-Type: application/x-amz-json-1.0
< x-amz-crc32: 1315925753
< x-amzn-RequestId: 8bace1da-6c08-4887-b4aa-08afc1f4696e
< Content-Length: 17
< Server: Jetty(8.1.12.v20130726)
< 
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact

<- Leaving step sign, name 'signer'
-----------------------------------
...
```
Looks like there is no logging information for connection. Since as mentioned there is no issue with the web shell, so I assume `port:8000` is running all right. Credentials shouldn't be the problem for DynamoDB local although is needed. 

May I ask which version of SDK is used? Are you using [`aws-sdk-php-laravel`](https://github.com/aws/aws-sdk-php-laravel)?

**Comment by remipelhate** [comment] 2016-10-11 17:33
Hi @cjyclaire! Thanks for responding this quickly :)! 

I'm using version 3.18.30 of the PHP SDK. I'm not using the `aws-sdk-php-laravel` package, as it has very little value for what we actually need. We're not using facades, nor do we manually resolve bindings from the IoC container. That's why we manually bind the DynamoDbClient through our own ServiceProvider. I did try using `aws-sdk-php-laravel` to see if it fixed the issue, but it didn't... I also tried running DynamoDb on different ports, but I always get the same result.

I know it's very unlikely that this is an SDK issue. I'm just hoping you guys might have an idea what I may be doing wrong. I really have no clue at all.

**Comment by cjyclaire** [comment] 2016-10-11 17:51
@remipelhate I see, I doubt that connection could be the problem yet error or exception failed to be surfaced. Could you try to configure [`timeout`](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#http) in the client to make it fall immediately to see if more errors could be surfaced?

**Comment by remipelhate** [comment] 2016-10-12 07:45
Alright, I updated the config to timeout after 1s without retries.
<details>
<summary>`config/services.php`</summary>
```php
'aws' => [
    'dynamodb' => [
        'credentials' => [
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
        ],
        'region' => env('AWS_REGION'),
        'version' => env('AWS_VERSION', 'latest'),
        'endpoint' => env('AWS_ENDPOINT', 'http://127.0.0.1:8000'),
        'debug' => env('APP_DEBUG', false),
        'retries' => 0,
        'http' => [
            'timeout' => 1,
        ],
    ],
],
```
</details>

This results in:
```
-> Entering step sign, name 'signer'
------------------------------------

  request.instance changed from 0000000030b94d34000000001acbd48c to 0000000030b94d58000000001acbd48c
  request.headers.X-Amz-Date was set to array(1) {
    [0]=>
    string(16) "20161012T073114Z"
  }
  
  request.headers.Authorization was set to array(1) {
    [0]=>
    string(231) "AWS4-HMAC-SHA256 Credential=[KEY]/20161012/eu-west-1/dynamodb/aws4_request, SignedHeaders=aws-sdk-invocation-id;host;x-amz-date;x-amz-target, Signature=[SIGNATURE]
  }
  

* Rebuilt URL to: http://127.0.0.1:8000/
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8000 (#0)
> POST / HTTP/1.1
Host: 127.0.0.1:8000
X-Amz-Target: DynamoDB_20120810.CreateTable
Content-Type: application/x-amz-json-1.0
aws-sdk-invocation-id: eda99d5d6198b4e4e2f47d4e577d2dae
X-Amz-Date: 20161012T073114Z
Authorization: AWS4-HMAC-SHA256 Credential=[KEY]/20161012/eu-west-1/dynamodb/aws4_request, SignedHeaders=aws-sdk-invocation-id;host;x-amz-date;x-amz-target, Signature=[SIGNATURE]
User-Agent: aws-sdk-php/3.18.30 GuzzleHttp/6.2.1 curl/7.35.0 PHP/5.5.9-1ubuntu4.17
Content-Length: 327

* upload completely sent off: 327 out of 327 bytes
* Operation timed out after 1004 milliseconds with 0 bytes received
* Closing connection 0
```
and eventually throws:
```
[Aws\DynamoDb\Exception\DynamoDbException]                                                                                                                                                                          
Error executing "CreateTable" on "http://127.0.0.1:8000"; AWS HTTP error: cURL error 28: Operation timed out after 1004 milliseconds with 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)  
```

```
[GuzzleHttp\Exception\ConnectException]                                                                                                   
cURL error 28: Operation timed out after 1004 milliseconds with 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

The same happens when I increase the timeout value and/or the amount of retries...

**Comment by cjyclaire** [comment] 2016-10-12 17:25
@remipelhate The error indicates `Hostname was NOT found in DNS cache`, it might has to do with cURL. Could you try to upgrade cURL? Also, could you double check that port is running ok with dynamoDB?

**Comment by remipelhate** [comment] 2016-10-13 08:21
Yes I see that, but I it eventually connects, right (`Connected to 127.0.0.1 (127.0.0.1) port 8000 (#0)`)? Also, when I set `credentials` to false in the config, I do get a 400 response:
```
[Aws\DynamoDb\Exception\DynamoDbException]                                                                                                                 
  Error executing "CreateTable" on "http://127.0.0.1:8000"; AWS HTTP error: Client error: `POST http://127.0.0.1:8000` resulted in a `400 Bad Request` resp  
  onse:                                                                                                                                                      
  {"__type":"com.amazonaws.dynamodb.v20120810#MissingAuthenticationToken","message":"Request must contain either a valid ( (truncated...)                    
   MissingAuthenticationToken (client): Request must contain either a valid (registered) AWS access key ID or X.509 certificate. - {"__type":"com.amazonaws  
  .dynamodb.v20120810#MissingAuthenticationToken","message":"Request must contain either a valid (registered) AWS access key ID or X.509 certificate."}
```

So it really looks like it was able to connect to DynamoDb local... And since I can use the web shell, I presume it works well on that port as well.

**Comment by remipelhate** [comment] 2016-10-14 09:04
@cjyclaire Ok, apparently @Ocramius has similar issues (on alpine). He installed DynamoDb Local using Docker (https://hub.docker.com/r/tray/dynamodb-local/), which now works fine. I did so too (keeping the same configuration/setup as described above) and as a matter of fact, it all magically works. So it looks like there may be something wrong with the latest version of DynamoDb Local..?

**Comment by cjyclaire** [comment] 2016-10-14 16:28
@remipelhate Hmm, interesting. Good to know it's working now. I did use the latest version of DynamoDB Local in testing, which doesn't reproduce the issue for me.

Since this doesn't look like a SDK issue, I'm closing this issue for now, yet feel free to reopen with further comments or question :)

**Closed by cjyclaire** 2016-10-14 16:28 UTC
Labels: awaiting-reply, question
