### ISSUE TITLE
3.173.0 AWS HTTP error: cURL error 6: Could not resolve host: https; Unknown error (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

### ISSUE THREAD

**Issue by sonersivri** [aws/aws-sdk-php#2190] opened 2021-02-03 12:24 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
3.173.0 version introduce bug

**Version of AWS SDK for PHP?**
3.173.0 

**Version of PHP (`php -v`)?**
7.3.19

**To Reproduce (observed behavior)**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Sammyjo20** [comment] 2021-02-03 13:05
Yep, I am are getting this issue too. Running PHP 7.4 - Using second latest version is fine.

**Comment by Jarrid** [comment] 2021-02-03 13:15
I can confirm the same thing.  It's appending the // ahead of the https://, so it looks like http://https://

**Comment by toddpadwick** [comment] 2021-02-03 13:22
We just experienced this issue as well causing the images on our site to break. We solved it temporarily by pinning the version back to `3.171.20`. But it would be good to know when it's solved and at what version so we can open it up for updates again.

**Comment by aldenw** [comment] 2021-02-03 13:28
This is the same as this issue here, https://github.com/aws/aws-sdk-php/issues/2189

**Comment by SamRemis** [comment] 2021-02-03 18:09
Since this is the same issue as the other, I'm closing this one, but taking a look right now and will have a fix pushed out ASAP.  If you'd like to follow, please look at #2189

**Closed by SamRemis** 2021-02-03 18:09 UTC
Labels: bug, needs-triage
