### ISSUE TITLE
Unable to use Dynamodb using hard-coded credentials (Bad Request 400)

### ISSUE THREAD

**Issue by pavelsc** [aws/aws-sdk-php#686] opened 2015-07-13 13:26 UTC
```
$this->dynamoDbClient = new DynamoDbClient([
	'region' => 'us-east-1',
	'version' => 'latest',
	'credentials' => [
		'key' => $awsConf['access_key_id'],
		'secret' => $awsConf['secret_access_key']
	]
]);
$result = $this->dynamoDbClient->query([
	'ExpressionAttributeValues' =>  array (
		':customer_id' => array('N' => $params['customer_id']),
		':start_date' => array('N' => $params['start_date']),
		':end_date' => array('N' => $params['end_date'])
	),
	'IndexName' => 'callDateIndex',
	'KeyConditionExpression' => 'customerId = :customer_id AND callDate BETWEEN :start_date AND :end_date',
	'TableName' => 'cdr'
]);
```

I use this query on table cdr, where primary key was set as Hash and Range (N: customerId, S: uniqueId). LSI callDateIndex has N: callDate as Range. 
This query returns 400 Bad Request. But it is possible to do this in the AWS panel through filling fields and everything works as expected.

UPD:

object(Aws\DynamoDb\Exception\DynamoDbException)#394 (15) { ["response":"Aws\Exception\AwsException":private]=> object(GuzzleHttp\Psr7\Response)#371 (6) { ["reasonPhrase":"GuzzleHttp\Psr7\Response":private]=> string(11) "Bad Request" ["statusCode":"GuzzleHttp\Psr7\Response":private]=> int(400) ["headers":"GuzzleHttp\Psr7\Response":private]=> array(5) { ["x-amzn-requestid"]=> array(1) { [0]=> string(52) "M2B0619OCNSQAC1D40CMGH4QMBVV4KQNSO5AEMVJF66Q9ASUAAJG" } ["x-amz-crc32"]=> array(1) { [0]=> string(10) "3391492866" } ["content-type"]=> array(1) { [0]=> string(26) "application/x-amz-json-1.0" } ["content-length"]=> array(1) { [0]=> string(3) "244" } ["date"]=> array(1) { [0]=> string(29) "Wed, 29 Jul 2015 10:43:18 GMT" } } ["headerLines":"GuzzleHttp\Psr7\Response":private]=> array(5) { ["x-amzn-RequestId"]=> array(1) { [0]=> string(52) "M2B0619OCNSQAC1D40CMGH4QMBVV4KQNSO5AEMVJF66Q9ASUAAJG" } ["x-amz-crc32"]=> array(1) { [0]=> string(10) "3391492866" } ["Content-Type"]=> array(1) { [0]=> string(26) "application/x-amz-json-1.0" } ["Content-Length"]=> array(1) { [0]=> string(3) "244" } ["Date"]=> array(1) { [0]=> string(29) "Wed, 29 Jul 2015 10:43:18 GMT" } } ["protocol":"GuzzleHttp\Psr7\Response":private]=> string(3) "1.1" ["stream":"GuzzleHttp\Psr7\Response":private]=> object(GuzzleHttp\Psr7\Stream)#379 (7) { ["stream":"GuzzleHttp\Psr7\Stream":private]=> resource(64) of type (stream) ["size":"GuzzleHttp\Psr7\Stream":private]=> NULL ["seekable":"GuzzleHttp\Psr7\Stream":private]=> bool(true) ["readable":"GuzzleHttp\Psr7\Stream":private]=> bool(true) ["writable":"GuzzleHttp\Psr7\Stream":private]=> bool(true) ["uri":"GuzzleHttp\Psr7\Stream":private]=> string(10) "php://temp" ["customMetadata":"GuzzleHttp\Psr7\Stream":private]=> array(0) { } } } ["request":"Aws\Exception\AwsException":private]=> object(GuzzleHttp\Psr7\Request)#354 (7) { ["method":"GuzzleHttp\Psr7\Request":private]=> string(4) "POST" ["requestTarget":"GuzzleHttp\Psr7\Request":private]=> NULL ["uri":"GuzzleHttp\Psr7\Request":private]=> object(GuzzleHttp\Psr7\Uri)#364 (7) { ["scheme":"GuzzleHttp\Psr7\Uri":private]=> string(5) "https" ["userInfo":"GuzzleHttp\Psr7\Uri":private]=> string(0) "" ["host":"GuzzleHttp\Psr7\Uri":private]=> string(32) "dynamodb.us-east-1.amazonaws.com" ["port":"GuzzleHttp\Psr7\Uri":private]=> NULL

**Comment by jeskew** [comment] 2015-07-14 00:23
Hi @pavelsc,

What version of the SDK are you using?

**Comment by pavelsc** [comment] 2015-07-14 13:30
Hi,
3.0.4 - 2015-06-11
And here is my connection code, if it may help.
```
$this->dynamoDbClient = DynamoDbClient::factory(array(
	'region' => 'us-east-1',
	'version' => 'latest',
	'credentials' => [
		'key' => $awsConf['access_key_id'],
		'secret' => $awsConf['secret_access_key']
	]
));
```

**Comment by pavelsc** [comment] 2015-07-29 10:46
new details in the top comment

**Comment by jeskew** [comment] 2015-07-29 16:55
I'm having trouble reproducing this error. Could you construct your client with `'debug' => true` to capture the request that's being sent to DynamoDb?

This is how I'm trying to recreate the error, but the query commands always executes successfully:
```php
<?php

require __DIR__ . '/../vendor/autoload.php';

$ddb = new \Aws\DynamoDb\DynamoDbClient([
    'version' => 'latest',
    'region' => 'us-east-1',
]);

$ddb->createTable([
    'TableName' => 'cdr',
    'AttributeDefinitions' => [
        [
            'AttributeName' => 'customerId',
            'AttributeType' => 'N',
        ],
        [
            'AttributeName' => 'uniqueId',
            'AttributeType' => 'S',
        ],
        [
            'AttributeName' => 'callDate',
            'AttributeType' => 'N',
        ],
    ],
    'KeySchema' => [
        [
            'AttributeName' => 'customerId',
            'KeyType' => 'HASH',
        ],
        [
            'AttributeName' => 'uniqueId',
            'KeyType' => 'RANGE',
        ],
    ],
    'LocalSecondaryIndexes' => [
        [
            'IndexName' => 'callDateIndex',
            'KeySchema' => [
                [
                    'AttributeName' => 'customerId',
                    'KeyType' => 'HASH',
                ],
                [
                    'AttributeName' => 'callDate',
                    'KeyType' => 'RANGE',
                ],
            ],
            'Projection' => [
                'ProjectionType' => 'KEYS_ONLY',
            ],
        ],
    ],
    'ProvisionedThroughput' => [
        'ReadCapacityUnits' => 1,
        'WriteCapacityUnits' => 1,
    ],
]);

$ddb->waitUntil('TableExists', [
    'TableName' => 'cdr',
]);

$result = $ddb->query([
    'ExpressionAttributeValues' => array(
        ':customer_id' => array('N' => '1'),
        ':start_date' => array('N' => (string) strtotime('yesterday')),
        ':end_date' => array('N' => (string) time())
    ),
    'IndexName' => 'callDateIndex',
    'KeyConditionExpression' => 'customerId = :customer_id AND callDate BETWEEN :start_date AND :end_date',
    'TableName' => 'cdr',
]);

$ddb->deleteTable([
    'TableName' => 'cdr',
]);

$ddb->waitUntil('TableNotExists', ['TableName' => 'cdr']);
```

**Comment by pavelsc** [comment] 2015-07-30 15:40
@jeskew you didn't use hardcoded credentials in your connection
http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/credentials.html#hardcoded-credentials

**Comment by jeskew** [comment] 2015-07-30 16:07
@pavelsc I tried that as well and got the same result. Hardcoded credentials and credentials gleaned from the environment both turn into an instance of `Aws\Credentials\Credentials` before a request is sent, so that shouldn't change the behavior of the request serializer.

**Comment by jeskew** [comment] 2015-08-10 17:00
@pavelsc Were you able to test with environmental credentials?

**Comment by jeskew** [comment] 2015-08-30 05:18
Closing as unable to reproduce. Please feel free to reopen if you run into the issue again or if you have any further questions.

**Closed by jeskew** 2015-08-30 05:18 UTC
