### ISSUE TITLE
cannot upload server certificate using iam Credential should be scoped to a valid region, not 'sa-east-1'

### ISSUE THREAD

**Issue by dardoguidobono** [aws/aws-sdk-php#493] opened 2015-02-18 14:10 UTC
Exception: Credential should be scoped to a valid region, not 'sa-east-1'. Stack:#0 /var/website_fta_4221/site/vendor/aws/aws-sdk-php/src/Aws/Common/Exception/NamespaceExceptionFactory.php(76): Aws\Common\Exception\NamespaceExceptionFactory->createException('Aws\\Iam\\Excepti...', Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Message\Response), Array)
#1 /var/website_fta_4221/site/vendor/aws/aws-sdk-php/src/Aws/Common/Exception/ExceptionListener.php(55): Aws\Common\Exception\NamespaceExceptionFactory->fromResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Message\Response))
#2 [internal function]: Aws\Common\Exception\ExceptionListener->onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 /var/website_fta_4221/site/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 /var/website_fta_4221/site/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'request.error', Object(Guzzle\Common\Event))
#5 /var/website_fta_4221/site/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(589): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('request.error', Object(Guzzle\Common\Event))
#6 /var/website_fta_4221/site/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(378): Guzzle\Http\Message\Request->processResponse(Array)
#7 /var/website_fta_4221/site/vendor/guzzle/guzzle/src/Guzzle/Http/Message/EntityEnclosingRequest.php(49): Guzzle\Http\Message\Request->setState('complete', Array)
#8 /var/website_fta_4221/site/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(290): Guzzle\Http\Message\EntityEnclosingRequest->setState('complete', Array)
#9 /var/website_fta_4221/site/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(248): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
#10 /var/website_fta_4221/site/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(231): Guzzle\Http\Curl\CurlMulti->processMessages()
#11 /var/website_fta_4221/site/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(215): Guzzle\Http\Curl\CurlMulti->executeHandles()
#12 /var/website_fta_4221/site/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(109): Guzzle\Http\Curl\CurlMulti->perform()
#13 /var/website_fta_4221/site/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMultiProxy.php(94): Guzzle\Http\Curl\CurlMulti->send()
#14 /var/website_fta_4221/site/vendor/guzzle/guzzle/src/Guzzle/Http/Client.php(284): Guzzle\Http\Curl\CurlMultiProxy->send()
#15 /var/website_fta_4221/site/vendor/aws/aws-sdk-php/src/Aws/Common/Client/AbstractClient.php(256): Guzzle\Http\Client->send(Object(Guzzle\Http\Message\EntityEnclosingRequest))
#16 /var/website_fta_4221/site/vendor/guzzle/guzzle/src/Guzzle/Service/Client.php(136): Aws\Common\Client\AbstractClient->send(Object(Guzzle\Http\Message\EntityEnclosingRequest))
#17 /var/website_fta_4221/site/vendor/guzzle/guzzle/src/Guzzle/Service/Command/AbstractCommand.php(153): Guzzle\Service\Client->execute(Object(Aws\Common\Command\QueryCommand))
#18 /var/website_fta_4221/site/vendor/guzzle/guzzle/src/Guzzle/Service/Command/AbstractCommand.php(189): Guzzle\Service\Command\AbstractCommand->execute()
#19 /var/website_fta_4221/site/vendor/guzzle/guzzle/src/Guzzle/Service/Client.php(76): Guzzle\Service\Command\AbstractCommand->getResult()
#20 /var/website_fta_4221/site/vendor/aws/aws-sdk-php/src/Aws/Common/Client/AbstractClient.php(104): Guzzle\Service\Client->__call('UploadServerCer...', Array)
#21 /var/website_fta_4221/site/sslmanager.php(169): Aws\Common\Client\AbstractClient->__call('uploadServerCer...', Array)
#22 /var/website_fta_4221/site/sslmanager.php(169): Aws\Iam\IamClient->uploadServerCertificate(Array)

**Comment by jeremeamia** [comment] 2015-02-19 23:25
IAM has a global endpoint. If you are specifying sa-east-1 as the region, it is probably signing the request with sa-east-1, which would be incorrect for IAM. I will be pushing a fix to the SDK today that should solve this problem and allow your region configuration to work. Another way to avoid the problem is to configure your IAM client to use the us-east-1 region.

**Comment by jeremeamia** [comment] 2015-02-20 00:22
Fixed by 6e8bb87.

**Closed by jeremeamia** 2015-02-20 00:22 UTC
