### ISSUE TITLE
Aws\Sqs\Exception is missing InvalidAddressException

### ISSUE THREAD

**Issue by edwardbrosens** [aws/aws-sdk-php#571] opened 2015-05-11 11:37 UTC
InvalidAddressException gets thrown, but the actual class isn't present.
Please add it to the repo.

**Comment by jeremeamia** [comment] 2015-05-11 15:55
I'm not sure I understand quite what you mean. Is there an error?

**Comment by mtdowling** [comment] 2015-05-15 21:21
Is this class being required but is not present on disk? I assume that's the problem, and the cause would be that you are using an additional autoloader that is not properly allowing other autoloaders a chance to autoload files that it does not know how to autoload. In this case, your autoloader is likely requiring classes rather than checking fist if they exist. We use `class_exists` to determine if a special case exception exists for a service. `class_exists` triggers an autoloader to check if a file exists, which should normally not cause a failure. The fix to this problem is to update your autoloaders to first check if a file exists rather than to just require it. This will allows your autoloader to work correctly with class_exists and other autoloaders.

I'll go ahead and close this issue as we haven't header back from you, but do let us know if I've mis-diagnosed the issue here.

**Closed by mtdowling** 2015-05-15 21:21 UTC
