### ISSUE TITLE
Bad HTML formatting on the description of the CloudSearchDomainClient->search function

### ISSUE THREAD

**Issue by csdaraujo** [aws/aws-sdk-php#486] opened 2015-02-13 16:34 UTC
http://docs.aws.amazon.com/aws-sdk-php/latest/class-Aws.CloudSearchDomain.CloudSearchDomainClient.html#_search

The argument **expr** for the search function has a broken HTML on it's description. I can't figura out where and how to put the the name of the expression I'm building...

Can you guys fix it? Also, can anyone give me an example on how to use this argument (with more than one expression and with names)?

Thanks!

**Comment by csdaraujo** [comment] 2015-02-13 17:18
Figured it out. It1s a plain and simple JSON object where the key is the name of the expression and the value is the expression (as string).

{
    myexpr1: 'log10(field1)/field2',
    myexpr2: 'field2*2+field3'
}

Still, I think that description can improve a lot. Can I help you guys with it?

**Comment by jeremeamia** [comment] 2015-02-13 19:00
We'll look into it and see if the issue is with the content formatting or our doc generation. Thanks for letting us know about the problem, and I'm glad you figured it out.

**Comment by mtdowling** [comment] 2015-03-18 19:07
Thanks for the report. This will be fixed in the next release and build of the SDK.

**Closed by mtdowling** 2015-03-18 19:07 UTC
