### ISSUE TITLE
S3 URLs expire before the actual expiration time

### ISSUE THREAD

**Issue by Karthi-SRV** [aws/aws-sdk-php#1333] opened 2017-07-20 04:31 UTC
At least when using V3.24.4 of the SDK it appears that signed S3 URLs expire before their actual expiration time. For example, a certain URL that was generated a minutes ago has the Expires query string field set to 300 (2017-07-20T04:18:45Z) but when requesting said URL one is greeted with the following:
```
<Error>
    <Code>AccessDenied</Code>
    <Message>Request has expired</Message>
    <X-Amz-Expires>300</X-Amz-Expires>
    <Expires>2017-07-20T04:18:45Z</Expires>
    <ServerTime>2017-07-20T04:18:55Z</ServerTime>
    <RequestId>E4952EE21FC53CD9</RequestId>
    <HostId>
        ZgJWY5yN4ZmKd3dJ/HrS7Huw0wfJyyNi7MdNJFfzL/eh3m4PmJxf7+V2Qao7CQ3O5I765/2BuqA
    </HostId>
</Error>
```
The code used for generating these URLs is along the lines of the following:

```
function getObjectUrl($path, $isPrivate = true) {
    s3 = new S3Client([
        'version' => 'latest',
        'region'  => 'ap-southeast-2'
    ]);
    $Bucket = "bucket name";
		
    $cmd = $s3->getCommand('GetObject', [
        'Bucket' => $Bucket,
        'Key'    => $path
    ]);

    $request = $s3->createPresignedRequest($cmd, '+5 minutes');

    // Get the actual presigned-url
    $presignedUrl = (string) $request->getUri();
    return $presignedUrl;
}
```

Reading the documentation I'm lead to believe this should work but reality shows otherwise. Am I perhaps overlooking something, or is this perhaps a bug in V3.24.4 of the AWS SDK?

**Comment by kstich** [comment] 2017-07-20 22:02
Hi @Karthi-SRV, I am unable to reproduce your issue. The `$presignedUrl` I receive when I run through your code is valid for the specified '+5 minutes' and, afterwards, shows a similar AccessDenied error as you see. If you need the url to be available for a longer period of time, you'll need to change the `$expires` value you pass to [`createPresignedRequest()`](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.S3.S3Client.html#_createPresignedRequest).

**Comment by Karthi-SRV** [comment] 2017-07-21 14:50
@kstich I have deployed the code in AWS EC2 instance with load balancer. When I click on a certain link it will generate the AWS $presignedUrl url  and it will redirect to it.  Till yesterday morning it was working fine and later it expired to all the link even though max 10s difference between Server time and Expires Time.

```
<Expires>2017-07-20T04:18:45Z</Expires>
<ServerTime>2017-07-20T04:18:55Z</ServerTime>

```
For Fixes
Once I changed my code with expires time as '+10 minutes' in one server, It worked perfect, at certain time in another server with '+5 minutes', it worked. Then I have reverted my code as default and I added all the server in load balancer and It works. But, I can't identify that issue why it occurs and how? I can't identify whether it a library issue or AWS issue.

**Comment by kstich** [comment] 2017-07-21 21:37
The portion of the error you are highlighting is saying that the time of the server (`<ServerTime>`) you are trying to access is 10s after the expiration (`<Expires>`) of the `$presignedUrl`; the URL isn't being accessed before it expires. If you need a longer living URL, you'll have to update the expires time to be longer (as you did in moving it to `'+10 minutes'`) or guarantee that you're accessing it before the expiration.

As this doesn't seem like an issue with the SDK, I'll be closing it.

**Closed by kstich** 2017-07-21 21:37 UTC
Labels: awaiting-reply, usage-question
