### ISSUE TITLE
S3 Stream Wrapper: copy() returns true even on failure

### ISSUE THREAD

**Issue by dortort** [aws/aws-sdk-php#944] opened 2016-03-30 14:02 UTC
An invalid or unauthorized S3 source or destination doesn't cause `copy()` function to return false.
```php
copy('/path/to/file', 's3://unauthorized-bucket/file'); // returns true
copy('s3://unauthorized-bucket/or-missing-file', '/path/to/file'); // returns true
copy('/path/to/file', 's3:///.'); // returns true
```

**Comment by cjyclaire** [comment] 2016-03-30 22:40
@dortort  Actually `S3\StreamWrapper::stream_flush` does return false when copy() encounters an error, yet copy() doesn't return that failure to user. I'll looking into this issue and update.

**Comment by jeskew** [comment] 2016-04-10 01:47
Looking further into this issue, it appears that `copy` will return `false` if there is an issue when reading from S3. When writing to S3 via the stream wrapper, `copy` calls `url_stat`, `stream_open`, `stream_write` as many times as is necessary to write all data read from the copy source, and then `stream_flush` when all bytes have been written. `copy` will only return `false` if either `stream_open` or `stream_write` does. Since the StreamWrapper does not actually write any data to S3 until `stream_flush`, `copy` will never return `false` due to a non-existent bucket or a permissions issue. According to [a PHP bug report](https://bugs.php.net/bug.php?id=53328), this is a known issue with `copy` and should be considered the expected behavior.

The stream wrapper could check that the bucket exists in `stream_open` and maybe even attempt to write an empty file to verify that the wrapper's client has sufficient permissions to write to the requested location, but that would degrade performance and introduce a potential race condition if a bucket existed at the start of a `copy` operation and was subsequently deleted. `copy` would still return `true` in that case even though the final `PutObject` command would have failed. 

Given the odd semantics of `copy`, I'm not sure this issue can be fixed in a satisfactory way. I'm inclined to just remove it from the list of supported methods in the documentation, as it only mostly works. @mtdowling, any thoughts?

**Closed** 2016-04-12 01:19 UTC
Labels: discussion, streamwrapper
