### ISSUE TITLE
HHVM compatibility update

### ISSUE THREAD

**Issue by elazar** [aws/aws-sdk-php#899] opened 2016-02-01 19:30 UTC
From the [FAQ](https://github.com/aws/aws-sdk-php/blob/master/docs/faq.rst#does-the-sdk-work-on-hhvm):

> The SDK does not currently run on HHVM, and won't be able to until the [issue with the yield syntax in HHVM](https://github.com/facebook/hhvm/issues/1627) is resolved.

The [last comment on that issue](https://github.com/facebook/hhvm/issues/1627#issuecomment-170298746) indicates that it was resolved in the HHVM 3.11 release for all cited use cases, which should include the AWS SDK as it was mentioned a [few](https://github.com/facebook/hhvm/issues/1627#issuecomment-96063660) [times](https://github.com/facebook/hhvm/issues/1627#issuecomment-115729649). I'm not seeing any [open HHVM issues](https://github.com/facebook/hhvm/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+yield) directly related to support for the `yield` keyword, at least.

The current failure on the [HHVM build of aws/aws-sdk-php](https://travis-ci.org/aws/aws-sdk-php/jobs/105810451) doesn't appear to be related to the original issue with `yield`. It would be great if we could get an SDK version with full HHVM compatibility.

**Comment by jeskew** [comment] 2016-02-01 19:46
Unfortunately, Travis only tests against HHVM 3.6.6 at the moment. The [latest failure of the current version of the SDK](https://travis-ci.org/aws/aws-sdk-php/jobs/105526927) (V3) was caused by the yield syntax incompatibility. Based on what was mentioned in the HHVM issue, I expect v3 would work on HHVM 3.11, but I don't have a good way to automatically test all releases and pull requests until Travis upgrades their HHVM runtime.

The V2 failure linked to appears to be caused by an HHVM incompatibility in PHPUnit. I haven't investigated what's causing it, but it might also be fixed in 3.11.

**Comment by elazar** [comment] 2016-02-02 16:59
@jeskew Don't know that this is an option you can consider, but it looks like it's possible to use HHVM 3.11 in a Trusty beta environment. See [this issue](https://github.com/travis-ci/travis-ci/issues/5328) for details.

**Comment by jeskew** [comment] 2016-02-02 23:00
I ran a test (#902) to see if the SDK was compatible with HHVM >=3.11. It appears that while the HHVM team fixed the syntax error that was thrown when `yield` was placed inside parentheses, yielding into generators still does not work the same in PHP and HHVM.

**Comment by jeskew** [comment] 2016-02-04 19:23
I opened [a new issue](https://github.com/facebook/hhvm/issues/6807) on HHVM, as there is still an incompatibility with the way generators work between HHVM 3.11 and Zend PHP.

**Closed** 2016-02-08 21:08 UTC
Labels: docs, third-party
