### ISSUE TITLE
DateTime::__construct(): Failed to parse time string

### ISSUE THREAD

**Issue by themsaid** [aws/aws-sdk-php#1950] opened 2020-01-13 12:28 UTC
### Version of AWS SDK for PHP?

3.132.3

### Version of PHP (`php -v`)?

php7.3

### What issue did you see?

Using `ApiGatewayV2Client::getDomainName()` with a domain name created using `ApiGatewayClient` leads to the following error:

```
DateTime::__construct(): Failed to parse time string (1578911496) at position 8 (9): Unexpected character
```

**Comment by diehlaws** [comment] 2020-01-28 18:13
Hi @themsaid, thanks for bringing this to our attention and I do apologize for the delay in response on our end. Looking at the [API model](https://github.com/aws/aws-sdk-php/blob/master/src/data/apigatewayv2/2018-11-29/api-2.json#L3124) for `ApiGatewayV2` it looks like the "CertificateUploadDate" member of the response should be returned as an ISO8601 formatted timestamp, however the service is actually returning this value as a UNIX timestamp. I've reached out to the API Gateway team internally about this to ensure the service behavior and API model match. Once I hear back from them I will update the issue accordingly.

**Comment by carlalexander** [comment] 2020-08-06 22:42
I can confirm that @SamRemis's change seems to have fixed the issue.

**Comment by SamRemis** [comment] 2020-08-07 17:32
Thanks @carlalexander!  Looks like we still had to close this issue

**Closed by SamRemis** 2020-08-07 17:32 UTC
Labels: service-api
