### ISSUE TITLE
Cognito has method to auth user on web application

### ISSUE THREAD

**Issue by IgorDePaula** [aws/aws-sdk-php#994] opened 2016-05-17 19:44 UTC
Cognito has method to auth user on web application, only mobile devices. This is a false advertising. This works only on mobile devices and not for web.

**Comment by cjyclaire** [comment] 2016-05-17 20:08
@IgorDePaula , May I ask the version of SDK that you're using? the `Amazon Cognito Identity Provider` service support is added in v3.18.0 release. Also, where did you see the description docs?

**Comment by IgorDePaula** [comment] 2016-05-17 20:16
I am using the version 3.* (on my composer). I got signup the user, confirm
him, but not login. I not found any method for login using an web app, like
a site in php.

2016-05-17 17:08 GMT-03:00 cjyclaire <notifications@github.com>:

**Comment by cjyclaire** [comment] 2016-05-17 20:36
Login options are passed in when you construct a `CognitoIdentityProvider`.
sample code would look like:
```php
$provider = new CognitoIdentityProvider(
            'poolId',
            ['region' => 'us-east-1',  'version' => 'latest'],
            [
                'www.amazon.com' => 'access-token-old',
                'graph.facebook.com' => 'access-token-fb',
            ]
        );
```

Also, please make sure that you have v3.18.0+ because this service is introduced to PHP SDK since v3.18.0.

**Comment by IgorDePaula** [comment] 2016-05-17 20:40
Ok, im my case, I do not use any external provider like facebook or google
plus, only cognito. In Cognito provider, what method I use for verify the
user login and passord?

2016-05-17 17:36 GMT-03:00 cjyclaire <notifications@github.com>:

**Comment by IgorDePaula** [comment] 2016-05-17 20:41
The doc of cognito indentity provider has any documentation.

http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.CognitoIdentity.CognitoIdentityProvider.html

2016-05-17 17:40 GMT-03:00 principe.borodin@gmail.com <
principe.borodin@gmail.com>:

**Comment by IgorDePaula** [comment] 2016-05-17 20:46
can any explain for me or other users how work authentication and signup in
php by cognito? I configured it by console. I signup users already.

2016-05-17 17:41 GMT-03:00 principe.borodin@gmail.com <
principe.borodin@gmail.com>:

**Comment by cjyclaire** [comment] 2016-05-17 20:54
@IgorDePaula Will this helps? [CognitoIdentityProviderClient](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.CognitoIdentityProvider.CognitoIdentityProviderClient.html)

**Comment by IgorDePaula** [comment] 2016-05-17 20:56
I read this page already, this classe singup users only, not log in it.

2016-05-17 17:54 GMT-03:00 cjyclaire <notifications@github.com>:

**Comment by IgorDePaula** [comment] 2016-05-17 21:08
My sdk isntallation version is versions : * 3.18.6


2016-05-17 17:56 GMT-03:00 principe.borodin@gmail.com <
principe.borodin@gmail.com>:

**Comment by cjyclaire** [comment] 2016-05-18 19:11
Great thanks for your clarification! I'm contacting service team to get more information, and will keep following up.

**Comment by IgorDePaula** [comment] 2016-05-18 19:18
I have much to thank you for attention. Sorry about that. I can not post
anything on their forum.

2016-05-18 16:12 GMT-03:00 cjyclaire <notifications@github.com>:

**Comment by cjyclaire** [comment] 2016-05-19 21:23
@IgorDePaula , just confirmed from service team, Cognito does support web apps foe developer authenticated identities workflow. Apologies for the noises on doc website, yet for this workflow, it uses the same APIs for web as on mobile. 

Once you have the login and token, you just need to call GetId and either GetOpenIdToken or GetCredentialsForIdentity with the logins map updated appropriately, and Cognito will vend credentials for you. These APIs won't care about the source of the request at all.

There is a [blog](https://mobile.awsblog.com/post/TxBVEDL5Z8JKAC/Use-Amazon-Cognito-in-your-website-for-simple-AWS-authentication) with details.
There is the public doc guide for [Developer Authenticated Identities](http://docs.aws.amazon.com/cognito/latest/developerguide/developer-authenticated-identities.html), and you can ignore the noise like"(Android and iOS only)" ;)

If all of theses still doesn't help with your question, please let me know.

**Comment by IgorDePaula** [comment] 2016-05-20 00:17
I understand that cognito service do not authenticate an user on php app
for example, only mobile app. This is correct?
Em 19/05/2016 18:50, "cjyclaire" <notifications@github.com> escreveu:

**Comment by cjyclaire** [comment] 2016-05-20 00:25
No, they do support, it uses the same APIs for web as on mobile.

**Comment by IgorDePaula** [comment] 2016-05-20 00:55
Ok, how I authenticate an user on php app for example? I do not want use an
external proider like facebook, twitter, but only cognito. How I capture
the user password and login for authenticate the user on cognito? I read
"session app" on anywhere on docs, but test another browser, for generate
another session, and not generate another session, I "logged as previous
user".

2016-05-19 21:25 GMT-03:00 cjyclaire <notifications@github.com>:

**Comment by IgorDePaula** [comment] 2016-05-20 00:57
This blog I tested, generate all steps, but I confused how authenticate
user login and user password only cognito, and not using external provider.

2016-05-19 21:55 GMT-03:00 principe.borodin@gmail.com <
principe.borodin@gmail.com>:

**Comment by cjyclaire** [comment] 2016-05-20 05:36
I fully understand your situation, I'm not suggesting using any external providers.

With developer authenticated identities, you can register and authenticate users via your own existing authentication process, while still using Amazon Cognito to synchronize user data and access AWS resources. And this process is in referred in the [doc](http://docs.aws.amazon.com/cognito/latest/developerguide/developer-authenticated-identities.html),
You need to implement an Identity Provider, then update the login map, getting a token and connect to identity. 

As I've mentioned, once you have the login and token, you just need to call GetId and either GetOpenIdToken or GetCredentialsForIdentity with the logins map updated appropriately, and Cognito will vend credentials for you. These APIs won't care about the source of the request at all.

The service team also mentioned that if you have further questions about their service, they are more than happy to help you on the forum! I believe you can register the aws developer [forum](https://forums.aws.amazon.com/forum.jspa?forumID=173&start=0) with ease.

**Comment by IgorDePaula** [comment] 2016-05-20 14:19
I appreciate very much yout attention. I know that you do not suggest use
external provider, but this process is confused.

I followed all steps on page quoted previuosly. But I do not understand
where my user is put your login and password for authenticate on my system.

I signup and confirm signup the users by api and sdk already, but where my
user will put login and password and what method from sdk/api my
application I call for this action?

If cognito storage username and password from my user, I do not need have
my own authentication process.

But by you said, I suppose that I have my own authentication process. I
signup the user on cognito and receive yout token. I storage this token on
my database. When this user is authenticate on my system, I verify you
username, password on my database and yout token on cognito. This is the
process?

How you said, I need implement the Identity Provider, what this provider
need do?

Can you show me a draft of this process, please? If no, all right, I
desist. You help me very much already.

Again, I appreciate very much yout attention.

2016-05-20 2:36 GMT-03:00 cjyclaire <notifications@github.com>:

**Comment by cjyclaire** [comment] 2016-05-20 17:42
> But by you said, I suppose that I have my own authentication process. I
signup the user on cognito and receive yout token. I storage this token on
my database. When this user is authenticate on my system, I verify you
username, password on my database and yout token on cognito. This is the
process?

Yes, that's exactly what I'm suggesting! After you have finish authentication, you can use the provider with your authentication.
Apology for those information cause confusion so far. Since this question is more about the service instead of SDK itself, I'd suggest you can discuss it directly with service team on the forum with your aws account login, they have much patience in guiding customers walking through the usage.

By the way, it's confirmed that web app flow is supported, so there is no worries for the possibility. I'm going to close this issue, yet feel free to reopen if you have further questions!

**Closed by cjyclaire** 2016-05-20 17:42 UTC
Labels: question

**Comment by IgorDePaula** [comment] 2016-05-20 17:53
Again, I appreciate very much yout attention. Thanks very much.

2016-05-20 14:42 GMT-03:00 cjyclaire <notifications@github.com>:

**Comment by t2adung** [comment] 2016-09-23 09:56
> I
signup the user on cognito and receive yout token

I have same issue. Please guide me how to get user token after signup the use on cognito. Thanks.

**Comment by engharb** [comment] 2018-01-23 07:52
Hello,
please have a look here may you will find answers about your questions

https://github.com/pmill/aws-cognito

regards,
