### ISSUE TITLE
After update Version 3.187.0 = DynamoDB Error retrieving credentials from the instance profile metadata

### ISSUE THREAD

**Issue by massimodellarovere** [aws/aws-sdk-php#2281] opened 2021-08-03 19:56 UTC
I current use this environment

aws/aws-sdk-php  3.186.4  AWS SDK for PHP - Use Amazon Web Services in your PH...
aws/aws-sdk-php-laravel  3.6.0  A simple Laravel 5/6/7/8 service provider for includ
laravel/framework v8.53.0   The Laravel Framework.
laravel/nova 3.27.0  A wonderful administration interface for Laravel.

If I execute composer update for upgrade SDK version 3.187.0 receive this. The problem is DynamoDB thatt i use for driver Cache and Session in Laravel. If change Driver from DYNAMODB to FIle.. no reveive error, but if i use dynamodb exception in all pages my application..

![image](https://user-images.githubusercontent.com/5731295/128077679-5f7556e1-04ff-4ab9-91df-6ebd46647ae9.png)

If downgrade return all OK

**Comment by SamRemis** [comment] 2021-08-03 21:15
@massimodellarovere I think I know what caused this, and am working on a fix right now.  Please stand by

**Comment by SamRemis** [comment] 2021-08-03 21:16
@massimodellarovere, just merged the fix.  Please get the latest then try again and let me know if it's fixed

**Comment by massimodellarovere** [comment] 2021-08-03 23:35
![image](https://user-images.githubusercontent.com/5731295/128099367-6ba04080-9585-47aa-b0f1-bae0c7ee560e.png)
Update with dev-master is OK .. I not receive error

**Comment by jonnycbw** [comment] 2021-08-04 12:31
@massimodellarovere This is still an issue with production, when will this be merged?

**Comment by mgilberties** [comment] 2021-08-04 12:41
@SamRemis Any idea on the ETA for this one being merged in and released as a tagged version? It's wiped a fair few systems out.

**Comment by SamRemis** [comment] 2021-08-04 13:44
@jonnycbw @mgilberties I have already merged it, so depending on how you download the release, it should have already been fixed.  I will release a tagged version to make sure it propagates faster

**Comment by mgilberties** [comment] 2021-08-04 13:56
@SamRemis  - Nice one. We were installing using composer and it doesn't appear to be pulling the latest changes without the tag. We have manually set our systems to use 3.186.1 for now. This is the error we were getting across numerous instances:
 
`[2021-08-04 12:00:51] uat.ERROR: Error retrieving credentials from the instance profile metadata service. (cURL error 6: Could not resolve host: https (see https://curl.haxx.se/libcurl/c/libcurl-errors.html$
[stacktrace]
#0 /var/app/current/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php(159): Aws\\Credentials\\InstanceProfileProvider->handleRetryableException(Object(GuzzleHttp\\Exception\\ConnectExceptio$
#1 [internal function]: Aws\\Credentials\\InstanceProfileProvider->Aws\\Credentials\\{closure}()
#2 /var/app/current/vendor/guzzlehttp/promises/src/Coroutine.php(160): Generator->throw(Object(GuzzleHttp\\Exception\\ConnectException))
#3 /var/app/current/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\\Promise\\Coroutine->_handleFailure(Object(GuzzleHttp\\Exception\\ConnectException))
#4 /var/app/current/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\\Promise\\Promise::callHandler(2, Object(GuzzleHttp\\Exception\\ConnectException), NULL)
#5 /var/app/current/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closure}()
#6 /var/app/current/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(118): GuzzleHttp\\Promise\\TaskQueue->run()
#7 /var/app/current/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(145): GuzzleHttp\\Handler\\CurlMultiHandler->tick()
#8 /var/app/current/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\\Handler\\CurlMultiHandler->execute(true)
#9 /var/app/current/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\\Promise\\Promise->invokeWaitFn()
#10 /var/app/current/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\\Promise\\Promise->waitIfPending()
#11 /var/app/current/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\\Promise\\Promise->invokeWaitList()
#12 /var/app/current/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()
#13 /var/app/current/vendor/guzzlehttp/promises/src/Coroutine.php(67): GuzzleHttp\\Promise\\Promise->wait()
#14 /var/app/current/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\\Promise\\Coroutine->GuzzleHttp\\Promise\\{closure}(true)
#15 /var/app/current/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\\Promise\\Promise->invokeWaitFn()
#16 /var/app/current/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()
#17 /var/app/current/vendor/guzzlehttp/promises/src/Coroutine.php(103): GuzzleHttp\\Promise\\Promise->wait(false)
#18 /var/app/current/vendor/guzzlehttp/promises/src/Promise.php(274): GuzzleHttp\\Promise\\Coroutine->wait(false)
#19 /var/app/current/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\\Promise\\Promise->invokeWaitList()
#20 /var/app/current/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()
#21 /var/app/current/vendor/aws/aws-sdk-php/src/S3/S3Client.php(460): GuzzleHttp\\Promise\\Promise->wait()
#22 /var/app/current/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(561): Aws\\S3\\S3Client->createPresignedRequest(Object(Aws\\Command), Object(Illuminate\\Support\\Carbon))
#23 /var/app/current/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(534): Illuminate\\Filesystem\\FilesystemAdapter->getAwsTemporaryUrl(Object(League\\Flysystem\\AwsS3v3\\AwsS3Adap$
#24 /var/app/current/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(399): Illuminate\\Filesystem\\FilesystemAdapter->temporaryUrl('project-name/even...', Object(Illuminate\\Support\\$`

**Comment by SamRemis** [comment] 2021-08-04 14:19
@mgilberties Thanks :) that's really helpful!  I wonder if this issue is releated only to presigned requests.  I will be looking into it more once the issue is definitely clear.  I did just release tag 3.187.1, so hopefully everyone should have this fixed now.

**Comment by SamRemis** [comment] 2021-08-04 14:23
Actually I spoke too soon, it looks like it's taking a bit to update on composer; I'll see what I can do to speed that up.

**Comment by SamRemis** [comment] 2021-08-04 14:36
There it goes, should be available now for 3.187.1

**Comment by SamRemis** [comment] 2021-08-04 14:37
@mgilberties please confirm this is fixed if you get the chance so I can close this issue out

**Comment by mgilberties** [comment] 2021-08-04 14:57
@SamRemis - I can confirm that we now have v3.187.1 getting picked up and everything is functioning as expected. Thanks for your quick actions and response :raised_hands:

**Comment by SamRemis** [comment] 2021-08-04 17:25
Great :) this should be working for everyone now, but I'll set this issue to closing soon just to give it a few days if anyone runs into it.

**Comment by RosiersRobin** [comment] 2021-08-06 11:57
I'm having the same issue with the latestupdate of the package. 

`Error retrieving credentials from the instance profile metadata service. (cURL error 7: Failed to connect to 169.254.169.254 port 80: Network unreachable`

**Comment by SamRemis** [comment] 2021-08-06 17:38
@RosiersRobin you're sure you're using 3.187.3? The error appears to have been fixed.  Can you CURL or ping from your machine?  The error you're getting also looks different than the one's above

**Comment by RosiersRobin** [comment] 2021-08-06 17:41
@SamRemis Yes, I'm using version 3.187.3 

The IP it's willing to go to is that 169.254.169.254 and when I ping it, it won't work, I get `PING: transmit failed. General failure.`

**Comment by SamRemis** [comment] 2021-08-06 17:47
@RosiersRobin can you ping anything at all?  And this is a new behavior?  To me it looks like an issue with internet settings on your instance, but it was working before and you haven't changed anything?

**Comment by RosiersRobin** [comment] 2021-08-07 12:00
@SamRemis It worked before, now I haven't changed a thing it it doesn't work anymore. When I ping from any other place, same issue occures. When I ping from an remote service like https://www.site24x7.com/ping-test.html it appears to be down too. So I doubt it would have to do with my network.

**Comment by massimodellarovere** [comment] 2021-08-09 20:53
@RosiersRobin I'm not 100% sure but it seems to me that the IP 169.254.169.254 direction is not reachable via Ping but only via HTTP request for retrieve Metadata. In my instance the ping return timeout no response but if i use CURL is OK

![image](https://user-images.githubusercontent.com/5731295/128772980-01802262-44ec-44d9-a0da-fbc9ef99718e.png)

**Comment by fideloper** [comment] 2021-08-11 12:39
I hit this issue this morning, running `composer update` resolved it. Note that the URL it's attempting to hit is `http://https//<some-aws-service>.amazonaws.com`

There must have been a bug where `https//` was used instead of `https://`, although it's hard to scan the commits for  a relevant fix.

**Comment by electric** [comment] 2021-09-07 04:41
I've just encountered this problem and have been trying to find out exactly why this particular commit stemmed from.

@SamRemis are you able to provide some context for the reverted change to help debug the issue?

Thanks

**Comment by SamRemis** [comment] 2021-09-07 04:47
@electric it's a bit late where I'm at, but hopefully I'll find time tomorrow to confirm.  If I recall correctly, it was exactly what the comment above yours says, a missing colon from the url scheme (https// instead of https://).

Can you set "debug" => true on your client constructor and confirm where the request is being sent?

**Comment by SamRemis** [comment] 2021-09-07 04:54
If that's what it is, please try the "composer update" command recommended above.  Please let me know if that doesn't work and I'll make sure to get it taken care of ASAP

**Comment by electric** [comment] 2021-09-07 20:17
> If that's what it is, please try the "composer update" command recommended above. Please let me know if that doesn't work and I'll make sure to get it taken care of ASAP

Thanks Sam - to confirm, a composer update did indeed fix the issue.

**Closed** 2021-12-15 19:51 UTC
