### ISSUE TITLE
Class 'Aws\EC2\Exception\EC2Exception' not found

### ISSUE THREAD

**Issue by ivankristic** [aws/aws-sdk-php#1160] opened 2017-01-23 11:58 UTC
Im trying to handle Ec2Exception so i send bad request to api just to catch exception but i get

> "FatalErrorException in ~/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php line 192:
> 
> Class 'Aws\EC2\Exception\EC2Exception' not found

```
/**
     * Parses a rejection into an AWS error.
     *
     * @param array            $err     Rejection error array.
     * @param RequestInterface $request Request that was sent.
     * @param CommandInterface $command Command being sent.
     * @param array            $stats   Transfer statistics
     *
     * @return \Exception
     */
    private function parseError(
        array $err,
        RequestInterface $request,
        CommandInterface $command,
        array $stats
    ) {
        if (!isset($err['exception'])) {
            throw new \RuntimeException('The HTTP handler was rejected without an "exception" key value pair.');
        }

        $serviceError = "AWS HTTP error: " . $err['exception']->getMessage();

        if (!isset($err['response'])) {
            $parts = ['response' => null];
        } else {
            try {
                $parts = call_user_func($this->errorParser, $err['response']);
                $serviceError .= " {$parts['code']} ({$parts['type']}): "
                    . "{$parts['message']} - " . $err['response']->getBody();
            } catch (ParserException $e) {
                $parts = [];
                $serviceError .= ' Unable to parse error information from '
                    . "response - {$e->getMessage()}";
            }

            $parts['response'] = $err['response'];
        }

        $parts['exception'] = $err['exception'];
        $parts['request'] = $request;
        $parts['connection_error'] = !empty($err['connection_error']);
        $parts['transfer_stats'] = $stats;

        return new $this->exceptionClass(
            sprintf(
                'Error executing "%s" on "%s"; %s',
                $command->getName(),
                $request->getUri(),
                $serviceError
            ),
            $command,
            $parts,
            $err['exception']
        );
    }
```

It breaks when trying to return new 

> "Aws\EC2\Exception\EC2Exception" 

instead of 

> "Aws\Ec2\Exception\Ec2Exception"

If i return hardcoded :arrow_up: class there, it works.

**Comment by imshashank** [comment] 2017-01-23 21:43
@ivankristic In the code, the class is defined as "Aws\EC2\Exception\Ec2Exception' . I will try to repro the bug locally and report my findings. 

Also is the Ec2Client creating the exception name with capital C?

**Comment by ivankristic** [comment] 2017-01-23 23:18
@imshashank 
i c/p the exception, it throws it as it is written here.

And no, the class in the code is ["Aws\Ec2\Exception\Ec2Exception"](https://github.com/aws/aws-sdk-php/blob/master/src/Ec2/Exception/Ec2Exception.php)
Its all capitalised, nothing is full uppercase

**Comment by cjyclaire** [comment] 2017-01-27 04:47
@ivankristic `Aws\Ec2\Exception\Ec2Exception` is the class you want to hit for exactly : )
I'm curious how you get 
> "FatalErrorException in ~/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php line 192:

Class 'Aws\EC2\Exception\EC2Exception' not found

So I tried to send a bad request and catches `Aws\Ec2\Exception\Ec2Exception` correctly. Could you show perhaps some code snippets that might help reproduce the error?

**Comment by ivankristic** [comment] 2017-01-27 11:32
@cjyclaire 
i know i want to hit that class, that is exactly the problem cause i get FatalError cause WrappedHttpHandler hits the wrong one.

Just create new valid `Ec2Client` instance and call `runInstances` with empty `$params` values
What ive sent was 
```
$params = [
     'ImageId' => 'null',
     'InstanceType' => 'null',
     'KeyName' => 'null',
     'Placement' => [
          'AvailabilityZone' => 'null',
          ],
     'MaxCount' => 1,
     'MinCount' => 1,
     'SecurityGroups => ['null'],
     ];
```
(_Though its irrelevant, null is string cause of HTML Form Input_)

**Comment by imshashank** [comment] 2017-02-04 00:30
@ivankristic 
Did creating the new `Ec2Client` resolve your problem or are you still getting the error.

If the error is still not resolved, can you please provide the code with inputs so that we can report it.

**Comment by cjyclaire** [comment] 2017-02-10 01:13
@ivankristic  Interestingly I still could reproduce this locally, what I do is quite simple, I create **`\Aws\Ec2\Ec2Client`** and make an API with wrong param value
``` php
try {
    $ec2->runScheduledInstances([
        'ScheduledInstanceId' => 'sdasda',
        'InstanceCount' => 1,
        'LaunchSpecification' => [
            'ImageId' => 'sdasda'
        ]
    ]);
} catch (\Aws\Ec2\Exception\Ec2Exception $e) {
    echo $e->getMessage();
}
```
It catches exception and gives error message correctly.

Also, recently our [Getting Help](https://github.com/aws/aws-sdk-php#getting-help) section has been updated, feel free to engaged in other channels as well. If you still finds it might be a bug regarding this repo, it would be great if you could share your SDK version, php version, guzzle version, OS version etc., and we can see if we could reproduce it there.

**Comment by ivankristic** [comment] 2017-02-10 11:00
@cjyclaire @imshashank 
Ok, i figured out what happens and why.
Ive made helper class that extends `Ec2Client` because there is no method to get `$instanceTypes`, and i couldnt figure out how to format valid filter params in request for AMIs to display only those provided by AWS, so i hardcoded those `$images` for myself for now until i have more time to figure those out.

Anyhow, while my class is called `EC2Helper`, i get that `FatalError`, but when i rename my class to `Ec2Helper`, i get `Ec2Exception` as i should.

```
class EC2Helper extends Ec2Client
{
    protected $key, $secret;

    protected $instanceTypes = [
        't2.nano', 't2.micro', 't2.small', 't2.medium', 't2.large', 't2.xlarge', 't2.2xlarge', 'm1.small',
        'm1.medium', 'm1.large', 'm1.xlarge', 'm3.medium', 'm3.large', 'm3.xlarge', 'm3.2xlarge', 'm4.large', 'm4.xlarge',
        'm4.2xlarge', 'm4.4xlarge', 'm4.10xlarge', 'm4.16xlarge', 'm2.xlarge', 'm2.2xlarge', 'm2.4xlarge', 'cr1.8xlarge',
        'r3.large', 'r3.xlarge', 'r3.2xlarge', 'r3.4xlarge', 'r3.8xlarge', 'r4.large', 'r4.xlarge', 'r4.2xlarge',
        'r4.4xlarge', 'r4.8xlarge', 'r4.16xlarge', 'x1.16xlarge', 'x1.32xlarge', 'i2.xlarge', 'i2.2xlarge', 'i2.4xlarge',
        'i2.8xlarge', 'hi1.4xlarge', 'hs1.8xlarge', 'c1.medium', 'c1.xlarge', 'c3.large', 'c3.xlarge', 'c3.2xlarge',
        'c3.4xlarge', 'c3.8xlarge', 'c4.large', 'c4.xlarge', 'c4.2xlarge', 'c4.4xlarge', 'c4.8xlarge', 'cc1.4xlarge',
        'cc2.8xlarge', 'g2.2xlarge', 'g2.8xlarge', 'cg1.4xlarge','p2.xlarge', 'p2.8xlarge', 'p2.16xlarge', 'd2.xlarge',
        'd2.2xlarge', 'd2.4xlarge', 'd2.8xlarge', 'f1.2xlarge', 'f1.16xlarge'
    ];

    protected $images = [
        'Amazon Linux AMI 2016.09.1 (HVM)' => 'ami-1e299d7e',
        'Red Hat Enterprise Linux 7.3 (HVM)' => 'ami-6f68cf0f',
        'SUSE Linux Enterprise Server 12 SP2 (HVM)' => 'ami-e4a30084',
        'Ubuntu Server 16.04 LTS (HVM)' => 'ami-b7a114d7',
        'Microsoft Windows Server 2016 Base' => 'ami-e69c2986',
        'Microsoft Windows Server 2016 Base with Containers' => 'ami-64982d04',
        'Microsoft Windows Server 2016 Base Nano' => 'ami-edf3448d',
        'Microsoft Windows Server 2016 with SQL Server 16 Express' => 'ami-ebc97d8b',
        'Microsoft Windows Server 2016 with SQL Server 16 Web' => 'ami-52ca7e32',
        'Microsoft Windows Server 2016 with SQL Server 16 Standard' => 'ami-37b40057',
        'Microsoft Windows Server 2012 R2 Base' => 'ami-cf9722af',
        'Microsoft Windows Server 2012 R2 with SQL Server 16 Express' => 'ami-0a3f8a6a',
        'Microsoft Windows Server 2012 R2 with SQL Server 16 Web' => 'ami-ef32878f',
        'Microsoft Windows Server 2012 R2 with SQL Server 16 Standard' => 'ami-383a8f58',
        'Microsoft Windows Server 2012 R2 with SQL Server 14 Express' => 'ami-67922707',
        'Microsoft Windows Server 2012 R2 with SQL Server 14 Web' => 'ami-44972224',
        'Microsoft Windows Server 2012 R2 with SQL Server 14 Standard' => 'ami-909722f0',
        'Microsoft Windows Server 2012 Base' => 'ami-2e92274e',
        'Microsoft Windows Server 2012 with SQL Server 12 Express' => 'ami-929c29f2',
        'Microsoft Windows Server 2012 with SQL Server 12 Web' => 'ami-289f2a48',
        'Microsoft Windows Server 2012 with SQL Server 12 Standard' => 'ami-d89d28b8',
        'Microsoft Windows Server 2008 R2 Base' => 'ami-6d91240d',
        'Microsoft Windows Server 2008 R2 with SQL Server 8 Express and IIS 7' => 'ami-bb9421db',
        'Microsoft Windows Server 2008 R2 with SQL Server 8 Web' => 'ami-7f96231f',
        'Microsoft Windows Server 2008 R2 with SQL Server 8 Standard' => 'ami-819722e1',
        'Microsoft Windows Server 2008 Base 64b' => 'ami-d1de6ab1',
        'Microsoft Windows Server 2008 Base 32b' => 'ami-84df6be4',
        'SUSE Linux Enterprise Server 11 SP4 (PV)' => 'ami-baab0fda',
        'Ubuntu Server 14.04 LTS (HVM)' => 'ami-30e65350',
        'Amazon Linux AMI 2016.09.1 (PV)' => 'ami-a3299dc3',
        'Microsoft Windows Server 2003 R2 Base 64' => 'ami-31912451',
        'Microsoft Windows Server 2003 R2 Base 32' => 'ami-bd9722dd'
    ];

    public function __construct()
    {
        $this->key = Config::get('remote.calls.AWS.key');
        $this->secret = Config::get('remote.calls.AWS.secret');

        $credentials = new Credentials($this->key, $this->secret);

        parent::__construct([
            'credentials' => $credentials,
            'region' => Config::get('remote.calls.AWS.region'),
            'version' => Config::get('remote.calls.AWS.version')
        ]);
    }

    public function describeInstanceTypes()
    {
        return $this->instanceTypes;
    }

    public function describeHardcodedImages()
    {
        return $this->images;
    }

    public function createName($input)
    {
        $params['Tags'] = [[
            'Key' => 'Name',
            'Value' => $input['Name']
        ]];
        $params['Resources'] = [
            $this->getInstanceId($input['Instance'])
        ];
        $this->createTags($params);
    }

    protected function getInstanceId($instance)
    {
        return $instance->get('Instances')[0]['InstanceId'];
    }
}
```

SDK = 3.20.13,
PHP = 5.6.4,
Guzzle = 6.2.2,
OS = Ubuntu 16.04

**Comment by cjyclaire** [comment] 2017-02-10 22:06
@ivankristic Glad that you work it out!
It's true that Ec2 doesn't provide those directly, since instance types and image types is always increasing, and api operation always requires more specific information to get expected results.

It surprises me that you are hard coding all those values, may I ask why you are doing so? Is this some feature that you would like to see? 

Closing issue for now since the issue is resolved, yet feel free to reopen or open a new issue with further explanation regarding potential feature request : )

**Closed by cjyclaire** 2017-02-10 22:07 UTC
Labels: usage-question
