### ISSUE TITLE
Nothing is copied when the file is zero bytes using the S3 StreamWrapper

### ISSUE THREAD

**Issue by amfahrj** [aws/aws-sdk-php#1724] opened 2019-02-12 19:33 UTC
If a file has zero bytes (for example, just touch a new file called foo.txt), if you then do a copy e.g.

`copy("foo,txt","s3://mybucket/foo.txt");`

Nothing is copied, but the copy function returns true (success). This is different than if you use the cli

`aws s3 cp foo.txt s3://mybucket/foo.txt`

Which does create the file.

**Comment by diehlaws** [comment] 2019-02-15 00:25
Hello @amfahrj, thanks for reaching out to us about this. We generally don't recommend using `copy` when using the S3 StreamWrapper with the AWS SDK for PHP since errors might not be properly reported due to the internals of the `copy` function in PHP. 

That being said, I'm able to reproduce the described behavior using other functions such as `file_put_contents` and `fwrite` to copy an empty file (or empty string) to S3 using the StreamWrapper. I've marked this as a feature request and will bring it up during our next sprint.

**Closed** 2019-03-07 18:11 UTC
Labels: bug

**Comment by howardlopez** [comment] 2019-03-07 18:13
@amfahrj Looks like this issue stemmed from changes in stream behavior in PHP 7+. We just merged in a fix in #1744, which will be included in the next release.
