### ISSUE TITLE
Deleting Matching Objects without leading slash causes exception since 3.209.31

### ISSUE THREAD

**Issue by frankdejonge** [aws/aws-sdk-php#2389] opened 2022-02-26 10:52 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
Version `3.209.31` on out created an invalid request body for the `Aws\S3\S3ClientInterface::deleteMatchingObjects` call. 

Exception body:

```
Aws\S3\Exception\S3Exception: Error executing "DeleteObjects" on "https://[redacted].s3.eu-central-1.amazonaws.com/?delete"; AWS HTTP error: Client error: `POST https://[redacted].s3.eu-central-1.amazonaws.com/?delete` resulted in a `400 Bad Request` response:
 <?xml version="1.0" encoding="UTF-8"?>
 <Error><Code>InvalidRequest</Code><Message>Missing required header for this reque (truncated...)
  InvalidRequest (client): Missing required header for this request: Content-MD5 OR x-amz-checksum-* - <?xml version="1.0" encoding="UTF-8"?>
 <Error><Code>InvalidRequest</Code><Message>Missing required header for this request: Content-MD5 OR x-amz-checksum-*</Message><RequestId>KA08XV3BM1PC5H62</RequestId><HostId>DRWlFA1vP7AJYNvO47uWBeru7fRH5kezgEBlsoEhIhVyVMWEY8MOHzrmaaHtLZKkURt4CIHx3X4=</HostId></Error>
 ```

**Version of AWS SDK for PHP?**
Version: 3.209.31
* get SDK version by printing the output of `Aws\Sdk::VERSION` in your code 
* if the SDK was installed via composer you can see the version installed with `composer show -i` 

**Version of PHP (`php -v`)?**
8.1.3, however it occurs in CI as well for the Flysystem probject, testing on 8.0 and 8.1.

**To Reproduce (observed behavior)**

```
<?php

use Aws\S3\S3Client;

require __DIR__ . '/vendor/autoload.php';

$key = '[redacted]';
$secret = '[redacted';
$bucket = '[redacted]]';
$region = 'eu-central-1';

$options = ['version' => 'latest', 'credentials' => compact('key', 'secret'), 'region' => $region];

$client = new S3Client($options);
$client->deleteMatchingObjects($bucket, 'something'); // exception

$client->deleteMatchingObjects($bucket, '/something'); // strangely enough, no exception
```

**Expected behavior**
Expect no exception to occur

**Comment by MrJuliuss** [comment] 2022-02-28 08:20
Hi, same issue here.

**Comment by lp-contentplus** [comment] 2022-02-28 14:25
3.209.16 works fine

**Comment by Herrick19** [comment] 2022-02-28 15:42
I have the same problem with s3 DeleteObjects and PutBucketTagging

**Comment by Herrick19** [comment] 2022-02-28 16:28
> are all of you on PHP 8.0 or higher?
On our side, we are on 7.4.27

**Comment by frankdejonge** [comment] 2022-02-28 16:30
@SamRemis I'm on PHP 8.0 and 8.1. What were the difficulties in reproducing it? Did the script I sent not produce the error for you?

**Comment by SamRemis** [comment] 2022-02-28 18:53
@frankdejonge, I was able to reproduce it with PutBucketTagging :) I must have made a copy/paste error with your script.  This should be fixed in the next tagged release in 20 minutes or so with the merging of #2390.  Please keep me updated if it is still not working for you

**Comment by SamRemis** [comment] 2022-02-28 19:15
Newest release just went out, please upgrade to 3.211.0 and let me know if the issue persists

**Comment by SamRemis** [comment] 2022-02-28 20:00
Sorry, spoke too soon a bit earlier.  3.211.0 is now out, please upgrade and confirm the fix

**Comment by frankdejonge** [comment] 2022-02-28 20:04
@SamRemis works for me!

**Comment by pablotorres-sf** [comment] 2022-02-28 20:06
3.211.0 fixed it.

**Comment by Herrick19** [comment] 2022-02-28 20:08
@SamRemis Works for me as well. Thanks for the quick fix

**Comment by SamRemis** [comment] 2022-02-28 20:40
Great :) thanks for your patience, and I apologize that this happened to begin with

**Closed by SamRemis** 2022-02-28 20:40 UTC
Labels: bug, closing-soon
