### ISSUE TITLE
Unable to establish Cognito client connection

### ISSUE THREAD

**Issue by quinnjr** [aws/aws-sdk-php#2944] opened 2024-06-17 21:02 UTC
### Describe the bug

As of roughly 2:00PM on 6/17/2024, we've been unable to establish client connections to Cognito to verify access tokens that are produced by the service.

Error output: `Could not resolve an authentication scheme: The service does not support `smithy.api#noAuth` authentication.`

### Expected Behavior

Connect to Cognito and verify access token

### Current Behavior

No connection to Cognito can be established

### Reproduction Steps

Example code:

```php
try { // Verify access token with Cognito

    // Create Cognito client
    $client = new CognitoIdentityProviderClient([
        'region' => $config['aws']['region'],
        'version' => $config['aws']['version'],
        'credentials' => $config['aws']['credentials']
    ]);

    $cognito_user = $client->getUser(['AccessToken' => $data->accessToken]);

} catch (Exception $e) {
    $response['message'] = 'Invalid access token';
    //Update tracking api call request
    update_api_request($api_id, $response);

    http_response_code(401); // Unauthorized

    $logger->addRecord(Logger::ERROR, $e->getMessage());

    echo json_encode($response, true);
    exit;
}
```

`$config['aws']['credentials']` is a correct associative array with valid access credentials.

### SDK version used

3.314.3

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.2.15, Ubuntu 22.04

**Comment by quinnjr** [comment] 2024-06-17 21:07
Confirming downgrading to [3.314.2](https://github.com/aws/aws-sdk-php/releases/tag/3.314.2) corrected the issue.

**Comment by durimjusaj** [comment] 2024-06-18 15:08
Same issue, Confirming downgrading to [3.314.2](https://github.com/aws/aws-sdk-php/releases/tag/3.314.2) corrected the issue.

**Comment by stobrien89** [comment] 2024-06-18 16:00
Hi all,

Sorry to hear about the issues.  Looking into this now.

**Comment by stobrien89** [comment] 2024-06-18 16:59
This was caused by a discrepancy in the `noAuth` value in our specification vs what was actually modeled.  We recently released a feature which allows services to model multiple auth types for the service as a whole, as well as certain operations— the `getUser` operation uses the auth type that the discrepancy lies with.  This should be fixed in today's release.

**Closed** 2024-06-18 17:38 UTC
Labels: bug, pr/work-in-progress, p0
