### ISSUE TITLE
SNS times out if simplexml extension not available

### ISSUE THREAD

**Issue by stevenmunro** [aws/aws-sdk-php#1049] opened 2016-07-26 01:34 UTC
This is a precautionary issue as I currently have a ticket open with Amazon regarding a simple script designed to send a text message to my phone resulted in over 166,000 messages being sent through the system. Unfortunately I have been stung with a massive bill.

PHP7
SDK v3

If the simplexml extension is absent from your PHP, your script may never complete, thus bombarding messages until it times out.

I have disabled/enabled simplexml multiple times and my testing has been rather conclusive.

The AWS SDK for PHP should never had proceeded with the transaction unless it had properly detected that simplexml was available in the first place. Particularly when there is a potential high cost involved.

**Comment by cjyclaire** [comment] 2016-07-26 02:02
@stevenmunro apology for the trouble, and thank you for reporting. Yet may I ask the error message when `simplexml` is disabled? When I was trying to reproducing the issue, lacking `simplexml` would result in `400 Bad Request` which will cause the script failure and this 400 Error will not be retried by SDK. And since the request is failed, it won't arrive at server-side. 
So, could you provide more details about your testing case then we could dig more into this issue?

**Comment by stevenmunro** [comment] 2016-07-26 02:05
Hi @cjyclaire 
While it was timing out the only error message that was dumped to my PHP-error.log is the following;

[26-Jul-2016 00:00:22 UTC] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/html/vendor/guzzlehttp/psr7/src/MessageTrait.php on line 147
[26-Jul-2016 00:00:22 UTC] PHP Stack trace:
[26-Jul-2016 00:00:22 UTC] PHP   1. {main}() /var/www/html/sms.php:0
[26-Jul-2016 00:00:22 UTC] PHP   2. send_sms() /var/www/html/sms.php:35
[26-Jul-2016 00:00:22 UTC] PHP   3. Aws\AwsClient->publish() /var/www/html/sms.php:28
[26-Jul-2016 00:00:22 UTC] PHP   4. Aws\AwsClient->__call() /var/www/html/sms.php:28
[26-Jul-2016 00:00:22 UTC] PHP   5. Aws\AwsClient->execute() /var/www/html/vendor/aws/aws-sdk-php/src/AwsClientTrait.php:78
[26-Jul-2016 00:00:22 UTC] PHP   6. GuzzleHttp\Promise\Promise->wait() /var/www/html/vendor/aws/aws-sdk-php/src/AwsClientTrait.php:59
[26-Jul-2016 00:00:22 UTC] PHP   7. GuzzleHttp\Promise\Promise->waitIfPending() /var/www/html/vendor/guzzlehttp/promises/src/Promise.php:62
[26-Jul-2016 00:00:22 UTC] PHP   8. GuzzleHttp\Promise\Promise->invokeWaitList() /var/www/html/vendor/guzzlehttp/promises/src/Promise.php:225
[26-Jul-2016 00:00:22 UTC] PHP   9. GuzzleHttp\Promise\Promise->waitIfPending() /var/www/html/vendor/guzzlehttp/promises/src/Promise.php:269
[26-Jul-2016 00:00:22 UTC] PHP  10. GuzzleHttp\Promise\Promise->invokeWaitList() /var/www/html/vendor/guzzlehttp/promises/src/Promise.php:225
[26-Jul-2016 00:00:22 UTC] PHP  11. GuzzleHttp\Promise\Promise->waitIfPending() /var/www/html/vendor/guzzlehttp/promises/src/Promise.php:266
[26-Jul-2016 00:00:22 UTC] PHP  12. GuzzleHttp\Promise\Promise->invokeWaitFn() /var/www/html/vendor/guzzlehttp/promises/src/Promise.php:223
[26-Jul-2016 00:00:22 UTC] PHP  13. GuzzleHttp\Handler\CurlMultiHandler->execute() /var/www/html/vendor/guzzlehttp/promises/src/Promise.php:246
[26-Jul-2016 00:00:22 UTC] PHP  14. GuzzleHttp\Handler\CurlMultiHandler->tick() /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php:123
[26-Jul-2016 00:00:22 UTC] PHP  15. GuzzleHttp\Promise\TaskQueue->run() /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php:96
[26-Jul-2016 00:00:22 UTC] PHP  16. GuzzleHttp\Promise\FulfilledPromise::GuzzleHttp\Promise\{closure}() /var/www/html/vendor/guzzlehttp/promises/src/TaskQueue.php:61
[26-Jul-2016 00:00:22 UTC] PHP  17. Aws\Middleware::Aws\{closure}() /var/www/html/vendor/guzzlehttp/promises/src/FulfilledPromise.php:39
[26-Jul-2016 00:00:22 UTC] PHP  18. Aws\Signature\SignatureV4->signRequest() /var/www/html/vendor/aws/aws-sdk-php/src/Middleware.php:127
[26-Jul-2016 00:00:22 UTC] PHP  19. Aws\Signature\SignatureV4->buildRequest() /var/www/html/vendor/aws/aws-sdk-php/src/Signature/SignatureV4.php:64
[26-Jul-2016 00:00:22 UTC] PHP  20. GuzzleHttp\Psr7\Request->__construct() /var/www/html/vendor/aws/aws-sdk-php/src/Signature/SignatureV4.php:336
[26-Jul-2016 00:00:22 UTC] PHP  21. GuzzleHttp\Psr7\Request->setHeaders() /var/www/html/vendor/guzzlehttp/psr7/src/Request.php:45
[26-Jul-2016 00:00:22 UTC] PHP  22. is_array() /var/www/html/vendor/guzzlehttp/psr7/src/MessageTrait.php:147

**Comment by stevenmunro** [comment] 2016-07-26 02:11
Here is the script


`<?php

require 'vendor/autoload.php';

function send_sms() {

  $sns = Aws\Sns\SnsClient::factory(array(
    'region' => 'ap-southeast-1',
    'version' => 'latest',
    'credentials' => array(
       'key'    => 'XXremovedXX',
       'secret' => 'XXremovedXX',
    ),
    'scheme' => 'http',
  ));

  $attributes = [
    'AWS.SNS.SMS.SMSType' => [
      'DataType' => 'String',
      'StringValue' => 'Promotional',
    ],
  ];

  $result = $sns->publish(array(
    'Message' => 'Test Message',
    'PhoneNumber' => '+XXXXXXXXXXX',
    'MessageAttributes' => $attributes
  ));

    return true;

}

send_sms();`

**Comment by stevenmunro** [comment] 2016-07-26 02:13
Sorry about the formatting. Please let me know if you need anything else.

**Comment by cjyclaire** [comment] 2016-07-26 17:16
@stevenmunro still unable to reproduce, could you run the `compatibility-test.php` file to see the output? SDK already has check for`simplexml` [here](https://github.com/aws/aws-sdk-php/blob/master/compatibility-test.php#L126), if not installed, will give [warnings](https://github.com/aws/aws-sdk-php/blob/master/compatibility-test.php#L96) accordingly.

**Comment by stevenmunro** [comment] 2016-07-26 20:52
Hi @cjyclaire 

Amazon technical support responded just hours ago that they were able to reproduce the issue in a newly created environment without the php-simplexml package installed. They have flagged the wrong behavior to the SDK team in order to provide a fix.

**Comment by cjyclaire** [comment] 2016-07-28 21:00
The PR contains fix is merged in, and will be tagged in today's release.

**Closed by cjyclaire** 2016-07-28 21:00 UTC
Labels: bug, PR
