### ISSUE TITLE
aws-sdk-php looks in wrong folder for credentials

### ISSUE THREAD

**Issue by rtowings** [aws/aws-sdk-php#1335] opened 2017-07-28 17:05 UTC
Attempting to send SMS messages using the php sdk.  Worked fine with hard-coded credentials, but after moving credentials to ~www-data/.aws/credentials received the following error:

Severity: error --> Exception: Cannot read credentials from /.aws/credentials /var/www/html/ospos/vendor/aws/aws-sdk-php/src/Credentials/CredentialProvider.php 394

Taking the error literally, I moved the credentials into root ( /.aws/credentials ) and the process worked.

Just to be sure, I verified that the apache processes are running as www-data - yup!

It appears that the PHP SDK looks in root for the credentials, rather than looking in the user's home directory.

            "name": "aws/aws-sdk-php",
            "version": "3.31.8",
            "source": {
                "type": "git",
                "url": "https://github.com/aws/aws-sdk-php.git",
                "reference": "9829a8183016df800110148b467179d67c434f90"

**Comment by rtowings** [comment] 2017-07-28 17:20
Ahhh...  The SDK attempts to get the Home directory from the environment variable $HOME and prepends the value to /.aws/credentials.  Thus, is HOME is not set the getHomeDir() returns /.aws/credentials and will attempt to find the credentials in root.

WORKAROUND is to set the HOME variable to an appropriate value before instantiating a client.

Seems like this could be handled a little better, though.

**Comment by imshashank** [comment] 2017-07-28 17:28
@rtowings Sorry for the confusion. The SDK will look at the home directory of the given user. It looks like here the process is assumed to being run by root because the `HOME` environment variable is not set.

You can set the `HOME` env variable that is used by the SDK to look for credentials file. As described here -> https://github.com/aws/aws-sdk-php/blob/33e8f7083fcb54fd926a8569cb81a0795e8c2633/src/Credentials/CredentialProvider.php#L328 

You can read more about credential chain & providers in our official SDK guide -> http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/credentials.html

Please let me know if this helps in resolving your issue.

**Comment by imshashank** [comment] 2017-07-28 17:31
@rtowings Looks like I didn't see that you have answered the question already. Please let us know if you have any recommendations to improve the credentials workflow.

Closing this issue since this looks to be resolved. Please re-open this issue if you need any more help.

**Closed by imshashank** 2017-07-28 17:31 UTC

**Comment by Bhavna93** [comment] 2018-06-29 05:48
How to set HOME variable ?

**Comment by rtowings** [comment] 2018-06-29 11:56
Hi @Bhavna93  - you need to set the HOME variable early in your process.  A good place would be in your index.php when you setup the rest of your environment.  Just add something like:

```
//HOME is required for AWS store credentials to work.
putenv('HOME=/var/www');
require '../vendor/autoload.php';

use Aws\Sms\SmsClient;
```
In this instance, the credentials would be found in /var/www/.aws/credentials - but you can set the HOME variable to anything you wish, as long as your webserver process access.

**Comment by kevinfilteau** [comment] 2018-09-15 11:41
Om macOS with MAMP is set putenv('HOME=/Users/myuser') and it worked fine to load the AWS credentials.

**Comment by WongYueKeung** [comment] 2018-10-12 08:37
using system env to store credentials is a joke..
no one can access ur access key as long as u store them in PHP code block, PHP is naturally designed to be run safely, no need external stuff, no need extra protection
simply delete the=> static function: ini around line 288
aws-sdk-php/src/Credentials/CredentialProvider.php 
remove all if stament

modify this one(at the end of ini function):
           return Promise\promise_for(
                new Credentials(
                    $data[$profile]['aws_access_key_id'],
                    $data[$profile]['aws_secret_access_key'],
                    $data[$profile]['aws_session_token']
                )
            );
to this:
           return Promise\promise_for(
                new Credentials(
                    'YOU_ACCESS_KEY',
                    'SERECT_KEY',
                    'TOKEN'
                )
            );

and done!

**Comment by SCZappy** [comment] 2020-09-10 14:57
This is still checking the wrong folder for credentials

**Comment by SamRemis** [comment] 2020-09-10 15:26
@SCZappy The behavior for where it will check for files is described here: https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_profiles.html.  If you would like to have it be set somewhere else, please use the `filename` config option.  I believe the SDK is behaving as described, but if not, please let me know and I can look into it further.

**Comment by SCZappy** [comment] 2020-09-11 22:03
@SamRemis The problem is that the SDK is retrieving the `HOME` environment variable and assumes that that has been set for the environment. Running PHP with Apache doesn't set the `HOME` environment variable by default.

In the `httpd-vhosts.conf`, I add a line like the following: 
```
SetEnv  HOME PATH_TO_HOME
```
This forces Apache to use correct value for the `HOME` environment variable. 

With a custom Python build script, I actually have that value of `PATH_TO_HOME` updated with using:
```python
os.getenv('HOME')
```

**Comment by kkjdroid** [comment] 2021-12-13 19:49
@SamRemis I'm using `CredentialProvider::ini` and providing the correct file path, but it still errors: ```PHP Fatal error:  Uncaught Aws\\Exception\\CredentialsException: Cannot read credentials from /.aws/credentials```

If I use the `put_env` call from earlier in this thread, it works, but it seems like `CredentialProvider::ini` completely ignores its argument.

**Comment by SamRemis** [comment] 2021-12-13 21:00
@kkjdroid I'd like to look into that, but could use a bit more info:
1) Are you using the default chain, or setting custom credentials or a credential provider?  If so, what arguments are you passing for the file name?
2) Which version of the SDK are you using?
3) Is there anything of note about the environment this is running on?  Is it an apache server?  What OS is it on?  etc.

**Comment by kkjdroid** [comment] 2021-12-13 21:35
1. I'm just using `CredentialProvider::ini` directly. The file path is `/var/www/keys/.aws/credentials`.
2. 3.208.1
3. Apache 2.4.41 on Ubuntu 20.04

**Comment by tedcasey** [comment] 2022-04-08 16:24
@kkjdroid  You've probably solved this already, given the time passed, but I thought I would add this for the next person that may run into this.  For me, and I must stress for a dev environment only (I use IAM roles in prod), @SCZappy provided the best solution in terms of pointing the SDK to the creds location.  It keeps the code cleaner and still allows me to run on my Mac dev machine (I use Linux for production).  **One key thing to note though**, the permissions on the credentials file in the .aws folder must be open enough to allow a user other than the logged in user (i.e. Apache) to read them.  For this I used a permissions change of this: `chmod 644 credentials`.  I did the same for the config file for good measure.  Again, this is for a local dev machine only, not on production - I can't stress that enough.

What's strange is that none of this was necessary before I upgraded to Big Sur.  Everything worked fine with Mojave.  That said, after the update, I had to re-install php with brew, use the builtin version of Apache that comes with the OS (perhaps I should have used the brew version), and continues to use the SDK which I installed with composer.  This hodge podge approach is somewhat necessary given the woeful state of linux package management on the Mac.  I mean, for crying out loud, Apple, can't you just implement YUM or apt on your underlying linux base and be done with it?

In any case, I hope this helps someone.

**Comment by gidzr** [comment] 2022-07-01 05:27
It's really frustrating.. why is it possible to programmatically point to the credentials for s3 client, but can only rely on environmental variables for lightsail client?

This works
$clientS3 = new S3Client([
	'version' => 'latest',
	'profile' => 'default',
	'region' => $myRegionTYO,
	'credentials' => $credentials, //['key'=>$key,'secret'=>$secret]
]);

BUT THIS <--- Throws Credential errors, credential can't find the .aws/credentials file.
$clientLightsail = new LightsailClient([
   'profile' => 'default',
 	'version' => 'latest',
	'region' => $myRegionTYO,
	'credentials' => $credentials, //['key'=>$key,'secret'=>$secret]
]);

soo.. I need to add scripting to amend variables in the credential file, because: 
```
putenv("AWS_ACCESS_KEY_ID=xxxx");
putenv("AWS_SECRET_ACCESS_KEY=xxxx");
putenv("AWS_DEFAULT_REGION=xxxx");
```
does not work, and I will need to change the key and secret depending on whether it's for different users or different storage bucket access.

Btw, thank you to rtowings for "putenv('HOME=/var/www');" which is a quick and dirty working ... but means writing to a text file.. bleh.

**Comment by allestaire** [comment] 2023-05-22 02:42
Why is everyone is suggesting to change HOME value?
tsk tsk
