### ISSUE TITLE
Missing required client configuration options: version: (string) 

### ISSUE THREAD

**Issue by PaddyLock** [aws/aws-sdk-php#965] opened 2016-04-13 15:21 UTC
I am getting the following error when clearing the cache after composer install;

```
    A "version" configuration value is required. Specifying a version constraint      
    ensures that your code will not be affected by a breaking change made to the      
    service. For example, when using Amazon S3, you can lock your API version to      
    "2006-03-01".                                                                     
                                                                                      
    Your build of the SDK has the following version(s) of "s3": * "2006-03-01"        
                                                                                      
    You may provide "latest" to the "version" configuration value to utilize the      
    most recent available API version that your client's API provider can find.       
    Note: Using 'latest' in a production application is not recommended.              
                                                                                      
    A list of available API versions can be found on each client's API documentation  
    page: http://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html. If you are        
    unable to load a specific API version, then you may need to update your copy of   
    the SDK.
```

I have the following packages installed

```
"aws/aws-sdk-php-symfony": "~1.0",
"aws/aws-sdk-php": "3.2.6",
```

I am creating my client like this

```
$client = new S3Client(array(
            'region' => $awsS3Region,
            'version' => '2006-03-01',
            'credentials' => array(
                'key' => $awsKey,
                'secret'  => $awsSecret,
              )
        ));
```

And I also have this in my config

```
aws:
    version: latest
    region: us-east-1
    credentials:
        key: '%aws_key%'
        secret: '%aws_secret%'
    S3:
        version: '2006-03-01'

knp_gaufrette:
    adapters:
        amazon:
            aws_s3:
                service_id: aws.s3
                bucket_name: %s3_bucket%
                options:
                    create: true
    filesystems:
        amazonS3:
            adapter: amazon

    stream_wrapper: ~
```

**Comment by jeskew** [comment] 2016-04-13 17:20
Are you creating S3 clients anywhere else? The error message posted above should only appear when no version is specified in a client's constructor. The specific configuration you're using looks very similar to the [configuration used in the bundle's test suite](https://github.com/aws/aws-sdk-php-symfony/blob/a0feab157de41f02e7ac015cb43ea055d6840119/tests/fixtures/config.yml), so that combination gets tested regularly.

**Comment by jeskew** [comment] 2016-04-19 17:34
Closing, as I'm unable to reproduce the issue. The error posted is specifically thrown when a client is constructed without a version parameter, so I believe the snippets posted are not where the error is being thrown.

**Closed by jeskew** 2016-04-19 17:34 UTC
Labels: awaiting-reply
