### ISSUE TITLE
RefreshableInstanceProfileCredentials get non-object for $client

### ISSUE THREAD

**Issue by stefandoorn** [aws/aws-sdk-php#710] opened 2015-07-31 10:17 UTC
Once in a while I notice the following error in our production logs. It happens only some (2-3) times a day.

````
Call to a member function getInstanceProfileCredentials() on a non-object in /var/www/vendor/aws/aws-sdk-php/src/Aws/Common/Credentials/RefreshableInstanceProfileCredentials.php:52
````

I tried some debugging but unfortunately I can never reproduce the problem myself and neither I really get a grip on how this would happen. Also at this moment I don't have a deeper trace, this is all is logged at the moment. I'm using version 2.8.13 of the API in production at the moment.

**Comment by jeskew** [comment] 2015-08-04 17:36
Hi @stefandoorn,

The root cause of the error you encountered is that an instance profile credentials object can't be effectively woken up from cache right now if the credentials have expired. There's an open pull request to fix this.

**Comment by stefandoorn** [comment] 2015-08-04 18:06
Hi @jeskew, 

Thanks for the clarification :) I will be happy to test it live as soon as it made it into a release.

**Comment by jeskew** [comment] 2015-08-04 22:34
A fix for this was included in today's release. Please feel free to reopen if you have any further questions.

**Closed by jeskew** 2015-08-04 22:34 UTC

**Comment by stefandoorn** [comment] 2015-08-05 07:22
Hi @jeskew, wanted to let you know I had some problems on/after deploy:

Aws\Ec2\Exception\Ec2Exception: AWS Error Code: AuthFailure, Status Code: 401, AWS Request ID: XXX, AWS Error Type: client, AWS Error Message: Authorization header or parameters are not formatted correctly., User-Agent: aws-sdk-php2/2.8.17 Guzzle/3.9.3 curl/7.40.0 PHP/5.5.26 [] []

Removing the cached credentials by hand solved things, error only happened once. Not sure if more people have this problem, but atleast good you know it happened I think :) Not sure if invalidating cache is possible on release, but would be a nice feature for sure :)

**Comment by jeskew** [comment] 2015-08-06 16:35
@stefandoorn Glad to hear clearing the cache worked. 

Unfortunately, I'm not sure we can reliably clear caches on upgrading, as Composer will only execute post-update scripts registered on a project's root, not on that project's dependencies. In v3, we use the version number as part of the cache key, and that might be something we could look into backporting.
