### ISSUE TITLE
Do multipart copies use non-sequential part numbers?

### ISSUE THREAD

**Issue by somnaderi** [aws/aws-sdk-php#2028] opened 2020-05-29 06:17 UTC
Confirm by changing [ ] to [x] below:
- [X] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers

**Version of AWS SDK for PHP?**
v3.133.10

**Version of PHP (`php -v`)?**
7.3.14-1

**Describe the question**
This may very well be an easy question, but I'm not so familiar with the internal workings, so figure I'd ask.

Running into a (seemingly) bizarre issue where my multipart uploads are failing multiple times with "NoSuchUpload" 404s (The specified upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed). 

Each failure reports hundreds of failed parts -- and a lot of the part numbers are high enough that part number x part size is much larger than the object being copied. (I'm getting part numbers in the 9000s and I have a 512MB part size).

Now, I'm copying large files (50-100GB videos), but I would have expected part numbers to be assigned sequentially. Some of the part numbers are in the 1-200 range, and then the numbers jump to the 7k range and many in the 9k range (for the same transfer).

I've done several successful copies with this code before (which has retry logic in case of "usual" failures), but in this case there were multiple copies happening simultaneously (different source/destinations for each). These were separate processes, so it seems unlikely that there would be any kind of cross talk, but figure I'd add that piece of info in case it's relevant.

Here is the code, for reference. Any help would be appreciated. Thanks!
(tried code formatting the below section and can't seem to get it to look right, so leaving it alone.)

```php
do {
    try {
        $result = $s3copier->copy();
    } catch (MultipartUploadException $e) {
        $s3copier = new MultipartCopy($s3, $sourceS3Path, [
            'state' => $e->getState(),
        ]);
        $errorMsg = $e->getMessage();
    }
    $attempts++;
} while (isset($result) !== true && $attempts <= $maxAttempts);
```

EDIT:
Just looking at the logs -- it appears there are 9822 part failed errors for this transfer. The file is about 100GB and 178 (the remaining parts) x 512MB is about 95GB. So maybe 5GB transferred before it failed...? And maybe somehow the state/retry flow attempts to check all 10000 part possibilities...?

**Comment by diehlaws** [comment] 2020-05-30 01:06
Hi @somnaderi, thanks for reaching out to us. I haven't come across the described behavior (granted I don't think I've tried copying files of this size between S3 locations using the SDK), however looking at the logic for MultipartCopy's [`getUploadCommands`](https://github.com/aws/aws-sdk-php/blob/master/src/S3/MultipartCopy.php#L101) it seems like it should be using sequential part numbers for these copy operations. I'll work on reproducing this on my end and will update the issue once I have additional information.

In the meantime, enabling [debug logging](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#debug) on your S3 client and rewiewing the resultant output would help determine whether the SDK is assigning sequential part numbers in the copy operation. Given the size of the debug log I'd suggest logging this output to a file for later review as shown below.

```php
$client = new S3Client([
    'region' => 'us-west-2',
    'version' => 'latest',
    'debug' => [
        'logfn' => function ($msg) {error_log($msg, 3, '/path/to/logfile.txt');}
    ],
]);
```

**Comment by somnaderi** [comment] 2020-09-12 19:10
Hi @diehlaws 

Sorry, totally slipped on getting back to this. There's actually a separate ticket I've submitted here (https://github.com/aws/aws-sdk-php/issues/2055) that's somewhat related, too.

Unfortunately, I'm only seeing these exception logs in our production environment. I'll look into enabling this there soon. The sequential numbering problem may only present itself when retry issues come up (as discussed in the linked issue), so it may take some time to get relevant logs to evaluate (the retry issue happens intermittently and can sometimes take a week or two to show up).

I'm okay with merging this issue with that one or closing this one, though. If you've got some cycles to help out on that one with Sam and me, that would be great, too. :) :) :)

**Comment by SamRemis** [comment] 2020-12-10 16:25
Closing this issue since most of the discussion is in #2055

**Closed by SamRemis** 2020-12-10 16:25 UTC
Labels: guidance, investigating
