### ISSUE TITLE
PostObjectV4 overwrites virtual-style URLs

### ISSUE THREAD

**Issue by jaypea** [aws/aws-sdk-php#1129] opened 2016-12-04 09:27 UTC
Hi, 

we are trying to upgrade the sdk from v2 to v3 in our big legacy app. Our complete system is based on virtual host style URLs for S3. 
So we changed the S3Client Config to like this:
```
$client = new S3Client([
    'credentials' => [
        'key' => 'sdfsdf',
        'secret' => 'sdsds',
    ],
    'region' => 'eu-west-1',
    'version' => '2006-03-01',
    'endpoint' => '<bucketName>.s3-eu-west-1.amazonaws.com',
    'bucket_endpoint' => true,
]);
```

This is the suggested workaround mentioned in this issue (https://github.com/aws/aws-sdk-php/issues/1118#issuecomment-260515622). This comment also states that the sdk would use path-style instead of virtual-style to reduce dns lookups and increase performance. 

However, inside of  `\Aws\S3\PostObjectV4` we found this:
```
    private function generateUri()
    {
        $uri = new Uri($this->client->getEndpoint());

        if ($uri->getScheme() === 'https'
            && strpos($this->bucket, '.') !== false
        ) {
            // Use path-style URLs
            $uri = $uri->withPath($this->bucket);
        } else {
            // Use virtual-style URLs
            $uri = $uri->withHost($this->bucket . '.' . $uri->getHost());
        }

        return (string) $uri;
    }
```
which would use virtual-style URLs for every non-ssl request.

In our case, it adds the bucket to the endpoint again, which was already provided in the s3client config.
So when using PostObjectV4, the resulting URL is
`http://<bucketname>.<bucketname>.s3-eu-west-1.amazonaws.com`.

Is this a bug or is there something we could configure differently?

As a workaround we could create 2 different s3client objects with different configurations, but this feels wrong somehow.

Switching to https is not an option currently, because our internal test system relies on fake-s3 , which does not do ssl.

**Comment by cjyclaire** [comment] 2016-12-05 20:04
@jaypea Thanks for the information and your efforts in upgrading, appreciate that!

So as you have observed, the discussion in #1118 refers to a general S3 workaround, which is not same as `PostObjectV4` case. In your case, you would like to have `virtual-host` style URL with `http` scheme. Then you could simply do:
``` php
    $s3 = new \Aws\S3\S3Client([
    'region' => 'us-west-2',
    'version' => 'latest',
    'scheme' => 'http'
   ]);
```
I assume this is what you are doing right now as you have mentioned using 2 `S3Client` objects with another client object configured as your code snippets.

It's true that automatic switching is provided between path style and virtual style hosting of buckets when necessary. The bug is caused by `http` situation with a customized `endpoint`, I'm working on the fix and will have a PR out shortly.

**Comment by jaypea** [comment] 2016-12-06 07:35
@cjyclaire thanks for the response and for fixing the root cause of my problem this fast.

**Comment by cjyclaire** [comment] 2016-12-06 18:51
@jaypea The fix PR has been merged, will be tagged in today's release, thank you for your patience! :)

**Closed by cjyclaire** 2016-12-06 18:51 UTC
Labels: PR-under-review
